In [1]:
### Download waste data on household waste 
### from regionalstatistik.de and compile into csv with Regions as rows
### and indicators and years as columns.

In [2]:
#41141-03-01-4
#https://www.regionalstatistik.de/genesis//online?operation=table&code=32121-01-02-4-B&bypass=true&levelindex=0&levelid=1658850132846#abreadcrumb
#include years 2007-2020 and set regions to Landkreise, download as csv

In [2]:
# import necessary libraries

import pandas as pd
import numpy as np

In [48]:
#load dataset from local file
source_df = pd.read_csv("data/32121-01-02-4-B_flat_haushaltsabfaelle.csv",delimiter=";", encoding='latin1', low_memory=False)

#remove subgroups of waste Haus- und Sperrmüll, Getrennt erfasste organische Abfälle, Getrennt erfasste Wertstoffe, Sonstige Abfälle, Biotonne, 
#remove subgroups of waste Haus- und Sperrmüll, Getrennt erfasste organische Abfälle, Getrennt erfasste Wertstoffe, Sonstige Abfälle and Insgesamt and Insgesamt
source_df = source_df[(source_df['2_Auspraegung_Code'] != 'ABFALLART100') & (source_df['2_Auspraegung_Code'] != 'ABFALLART300') & (source_df['2_Auspraegung_Code'] != 'ABFALLART400') & (source_df['2_Auspraegung_Code'] != 'ABFALLART201') & (source_df['2_Auspraegung_Code'] != 'ABFALLART202') & (source_df['2_Auspraegung_Label'] != "Insgesamt")]

#remove subgroups of waste Haus- und Sperrmüll, Getrennt erfasste organische Abfälle, Getrennt erfasste Wertstoffe, Sonstige Abfälle and Insgesamt
source_df = source_df[(source_df['2_Auspraegung_Code'] != 'ABFALLART100') & (source_df['2_Auspraegung_Code'] != 'ABFALLART300') & (source_df['2_Auspraegung_Code'] != 'ABFALLART400') & (source_df['2_Auspraegung_Label'] != "Insgesamt")]

source_df

,Statistik_Code,Statistik_Label,Zeit_Code,Zeit_Label,Zeit,1_Merkmal_Code,1_Merkmal_Label,1_Auspraegung_Code,1_Auspraegung_Label,2_Merkmal_Code,2_Merkmal_Label,2_Auspraegung_Code,2_Auspraegung_Label,AEW009__Aufkommen_an_Haushaltsabfaellen_(o.E-altgeraete)__t
2,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2020,KREISE,Kreise und kreisfreie Städte,1001,"Flensburg, kreisfreie Stadt",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,6050
9,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2020,KREISE,Kreise und kreisfreie Städte,1002,"Kiel, Landeshauptstadt, kreisfreie Stadt",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,16333
16,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2020,KREISE,Kreise und kreisfreie Städte,1003,"Lübeck, Hansestadt, kreisfreie Stadt",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,22232
23,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2020,KREISE,Kreise und kreisfreie Städte,1004,"Neumünster, kreisfreie Stadt",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,15841
30,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2020,KREISE,Kreise und kreisfreie Städte,1051,"Dithmarschen, Landkreis",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,18565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47889,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2007,KREISE,Kreise und kreisfreie Städte,16073,"Saalfeld-Rudolstadt, Kreis",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,10394
47896,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2007,KREISE,Kreise und kreisfreie Städte,16074,Saale-Holzland-Kreis,ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,-
47903,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2007,KREISE,Kreise und kreisfreie Städte,16075,Saale-Orla-Kreis,ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,7774
47910,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2007,KREISE,Kreise und kreisfreie Städte,16076,"Greiz, Kreis",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,7094
47917,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2007,KREISE,Kreise und kreisfreie Städte,16077,"Altenburger Land, Kreis",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,12946

In [50]:
waste_df = source_df.copy()

#extract year from date
waste_df['Jahr']=waste_df['Zeit'].astype(str)

#drop unnecessary columns
waste_df.drop(columns=['Zeit','Statistik_Code', 'Statistik_Label', 'Zeit_Code', 'Zeit_Label', 
       '1_Merkmal_Code', '1_Merkmal_Label', 
       '2_Merkmal_Code', '2_Merkmal_Label',
       '2_Auspraegung_Code'],inplace=True)

#rename columns
waste_df.rename(columns={'1_Auspraegung_Code':'AGS','1_Auspraegung_Label':'Name','2_Auspraegung_Label':'Abfall','AEW009__Aufkommen_an_Haushaltsabfaellen_(o.E-altgeraete)__t':'Anzahl'},inplace=True)

#replace '-' with 0 and '.' with 'NaN according to Zeichnerklärung
waste_df['Anzahl'].replace('-','0',inplace=True)
waste_df['Anzahl'] = waste_df['Anzahl'].apply(pd.to_numeric,errors='coerce')

waste_df['AGS']=waste_df['AGS'].replace("DG",0)

waste_df

,AGS,Name,Abfall,Anzahl,Jahr
2,1001,"Flensburg, kreisfreie Stadt",Getrennt erfasste organische Abfälle,6050.0,2020
9,1002,"Kiel, Landeshauptstadt, kreisfreie Stadt",Getrennt erfasste organische Abfälle,16333.0,2020
16,1003,"Lübeck, Hansestadt, kreisfreie Stadt",Getrennt erfasste organische Abfälle,22232.0,2020
23,1004,"Neumünster, kreisfreie Stadt",Getrennt erfasste organische Abfälle,15841.0,2020
30,1051,"Dithmarschen, Landkreis",Getrennt erfasste organische Abfälle,18565.0,2020
...,...,...,...,...,...
47889,16073,"Saalfeld-Rudolstadt, Kreis",Getrennt erfasste organische Abfälle,10394.0,2007
47896,16074,Saale-Holzland-Kreis,Getrennt erfasste organische Abfälle,0.0,2007
47903,16075,Saale-Orla-Kreis,Getrennt erfasste organische Abfälle,7774.0,2007
47910,16076,"Greiz, Kreis",Getrennt erfasste organische Abfälle,7094.0,2007
47917,16077,"Altenburger Land, Kreis",Getrennt erfasste organische Abfälle,12946.0,2007

In [51]:
#pivot dataframe to show waste and years as columns
pt_df = waste_df.pivot(index=['AGS','Name'],columns=['Abfall','Jahr'],values=['Anzahl'])

#rename columns
pt_df.rename(columns={'Getrennt erfasste organische Abfälle':'organicwaste'},inplace=True)

pt_df

                                                        Anzahl           \
Abfall                                            organicwaste
Jahr                                                      2020     2019
AGS      Name
1001     Flensburg, kreisfreie Stadt                    6050.0   5922.0
1002     Kiel, Landeshauptstadt, kreisfreie Stadt      16333.0  16035.0
1003     Lübeck, Hansestadt, kreisfreie Stadt          22232.0  20058.0
1004     Neumünster, kreisfreie Stadt                  15841.0  17900.0
1051     Dithmarschen, Landkreis                       18565.0  17681.0
...                                                        ...      ...
11008008 Berlin-Neukölln                                   NaN      NaN
11009009 Berlin-Treptow-Köpenick                           NaN      NaN
11010010 Berlin-Marzahn-Hellersdorf                        NaN      NaN
11011011 Berlin-Lichtenberg                                NaN      NaN
11012012 Berlin-Reinickendorf                              NaN      NaN

                                                                              \
Abfall
Jahr                                                  2018     2017     2016
AGS      Name
1001     Flensburg, kreisfreie Stadt                5764.0   5974.0   6074.0
1002     Kiel, Landeshauptstadt, kreisfreie Stadt  15174.0  16425.0  16200.0
1003     Lübeck, Hansestadt, kreisfreie Stadt      18789.0  19080.0  18796.0
1004     Neumünster, kreisfreie Stadt              13074.0  17226.0  10673.0
1051     Dithmarschen, Landkreis                   17026.0  17736.0  17546.0
...                                                    ...      ...      ...
11008008 Berlin-Neukölln                               NaN      NaN      0.0
11009009 Berlin-Treptow-Köpenick                       NaN      NaN      0.0
11010010 Berlin-Marzahn-Hellersdorf                    NaN      NaN      0.0
11011011 Berlin-Lichtenberg                            NaN      NaN      0.0
11012012 Berlin-Reinickendorf                          NaN      NaN      0.0

                                                                              \
Abfall
Jahr                                                  2015     2014     2013
AGS      Name
1001     Flensburg, kreisfreie Stadt                7217.0   5477.0   4844.0
1002     Kiel, Landeshauptstadt, kreisfreie Stadt  16217.0  16082.0  15590.0
1003     Lübeck, Hansestadt, kreisfreie Stadt      18491.0  18798.0  17251.0
1004     Neumünster, kreisfreie Stadt              12110.0  12243.0  11635.0
1051     Dithmarschen, Landkreis                   16935.0  16014.0  15257.0
...                                                    ...      ...      ...
11008008 Berlin-Neukölln                               0.0      0.0      0.0
11009009 Berlin-Treptow-Köpenick                       0.0      0.0      0.0
11010010 Berlin-Marzahn-Hellersdorf                    0.0      0.0      0.0
11011011 Berlin-Lichtenberg                            0.0      0.0      0.0
11012012 Berlin-Reinickendorf                          0.0      0.0      0.0

                                                                              \
Abfall
Jahr                                                  2012     2011     2010
AGS      Name
1001     Flensburg, kreisfreie Stadt                5098.0   5584.0   5325.0
1002     Kiel, Landeshauptstadt, kreisfreie Stadt  14951.0  15309.0  13976.0
1003     Lübeck, Hansestadt, kreisfreie Stadt      19048.0  19544.0  23052.0
1004     Neumünster, kreisfreie Stadt              11053.0  11701.0  11724.0
1051     Dithmarschen, Landkreis                   17044.0  17311.0  16463.0
...                                                    ...      ...      ...
11008008 Berlin-Neukölln                               0.0      0.0      0.0
11009009 Berlin-Treptow-Köpenick                       0.0      0.0      0.0
11010010 Berlin-Marzahn-Hellersdorf                    0.0      0.0      0.0
11011011 Berlin-Lichtenberg                            0.0      0.0      0.0
11012012 Berlin-Reinickendorf                          0.0      0.0      0.0


Abfall
Jahr                                                  2009     2008     2007
AGS      Name
1001     Flensburg, kreisfreie Stadt                5963.0   5396.0   5308.0
1002     Kiel, Landeshauptstadt, kreisfreie Stadt  14141.0  13474.0  12748.0
1003     Lübeck, Hansestadt, kreisfreie Stadt      22418.0  22400.0  21633.0
1004     Neumünster, kreisfreie Stadt              13936.0  13766.0  12892.0
1051     Dithmarschen, Landkreis                   17117.0  16832.0  16856.0
...                                                    ...      ...      ...
11008008 Berlin-Neukölln                               0.0      0.0      0.0
11009009 Berlin-Treptow-Köpenick                       0.0      0.0      0.0
11010010 Berlin-Marzahn-Hellersdorf                    0.0      0.0      0.0
11011011 Berlin-Lichtenberg                            0.0      0.0      0.0
11012012 Berlin-Reinickendorf                          0.0      0.0      0.0

[489 rows x 14 columns]

In [52]:
#collapse levels of column names and join waste type to year
pt_df.columns = pt_df.columns.map('_'.join)

#sort columns so indicators are together
pt_df.columns=sorted(pt_df.columns)

#prepend all columns with indicator name
pt_df=pt_df.add_prefix('waste_count_')

#convert AGS to numeric and set as new index
pt_df.reset_index(inplace=True)
pt_df['AGS'] = pd.to_numeric(pt_df['AGS'])
pt_df.set_index('AGS',inplace=True)
pt_df.sort_index(ascending=True,inplace=True)

#strip whitespace from region names
pt_df['Name']=pt_df['Name'].str.strip()

pt_df

,Name,waste_count_Anzahl_organicwaste_2007,waste_count_Anzahl_organicwaste_2008,waste_count_Anzahl_organicwaste_2009,waste_count_Anzahl_organicwaste_2010,waste_count_Anzahl_organicwaste_2011,waste_count_Anzahl_organicwaste_2012,waste_count_Anzahl_organicwaste_2013,waste_count_Anzahl_organicwaste_2014,waste_count_Anzahl_organicwaste_2015,waste_count_Anzahl_organicwaste_2016,waste_count_Anzahl_organicwaste_2017,waste_count_Anzahl_organicwaste_2018,waste_count_Anzahl_organicwaste_2019,waste_count_Anzahl_organicwaste_2020
AGS,,,,,,,,,,,,,,,
1001,"Flensburg, kreisfreie Stadt",6050.0,5922.0,5764.0,5974.0,6074.0,7217.0,5477.0,4844.0,5098.0,5584.0,5325.0,5963.0,5396.0,5308.0
1002,"Kiel, Landeshauptstadt, kreisfreie Stadt",16333.0,16035.0,15174.0,16425.0,16200.0,16217.0,16082.0,15590.0,14951.0,15309.0,13976.0,14141.0,13474.0,12748.0
1003,"Lübeck, Hansestadt, kreisfreie Stadt",22232.0,20058.0,18789.0,19080.0,18796.0,18491.0,18798.0,17251.0,19048.0,19544.0,23052.0,22418.0,22400.0,21633.0
1004,"Neumünster, kreisfreie Stadt",15841.0,17900.0,13074.0,17226.0,10673.0,12110.0,12243.0,11635.0,11053.0,11701.0,11724.0,13936.0,13766.0,12892.0
1051,"Dithmarschen, Landkreis",18565.0,17681.0,17026.0,17736.0,17546.0,16935.0,16014.0,15257.0,17044.0,17311.0,16463.0,17117.0,16832.0,16856.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11008008,Berlin-Neukölln,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11009009,Berlin-Treptow-Köpenick,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11010010,Berlin-Marzahn-Hellersdorf,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11011011,Berlin-Lichtenberg,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11012012,Berlin-Reinickendorf,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
#save dataframe to file
pt_df.to_csv("data/final_data_landkreis_waste_organicwaste.csv")