In [40]:
### Download energy consumption data for Deutschland
### from https://ag-energiebilanzen.de/ and compile into csv with Regions as rows
### and years as columns.

In [41]:
### https://ag-energiebilanzen.de/daten-und-fakten/bilanzen-1990-bis-2020/?wpv-jahresbereich-bilanz=2011-2020
### Download Excel files Bilanz and Satellitenbilanz for each year, select Sheet "TJ", copy Zeile 8 into new document
### preprocess by combining columns as in Data for Bundesländer

In [42]:
#import necessary libraries

import pandas as pd

In [43]:
#list of regions

regions = {"Deutschland":0,
           "Baden-Württemberg":8,
           "Bayern":9,"Berlin":11,
           "Brandenburg":12,
           "Bremen":4,
           "Hamburg":2,
           "Hessen":6,
           "Mecklenburg-Vorpommern":13,
           "Niedersachsen":3,
           "Nordrhein-Westfalen":5,
           "Rheinland-Pfalz":7,"Saarland":10,"Sachsen":14,"Sachsen-Anhalt":15,"Schleswig-Holstein":1,"Thüringen":16}

regions

{'Deutschland': 0,
 'Baden-Württemberg': 8,
 'Bayern': 9,
 'Berlin': 11,
 'Brandenburg': 12,
 'Bremen': 4,
 'Hamburg': 2,
 'Hessen': 6,
 'Mecklenburg-Vorpommern': 13,
 'Niedersachsen': 3,
 'Nordrhein-Westfalen': 5,
 'Rheinland-Pfalz': 7,
 'Saarland': 10,
 'Sachsen': 14,
 'Sachsen-Anhalt': 15,
 'Schleswig-Holstein': 1,
 'Thüringen': 16}

In [44]:
#read renewables data from csv
de_df = pd.read_csv("data/deutschland_erneuerbare.csv",delimiter=",")

#clean up labels
de_df.rename({"Klärgas,Deponiegas":"Klärgas, Deponiegas"},axis=1,inplace=True)

#drop unnecessary columns
de_df.drop(columns=["Zeilenname","Zeile"],inplace=True)

de_df

,Jahr,Wasserkraft,Windkraft,Solarenergie,Biomasse,"Klärgas, Deponiegas",Sonstige erneuerbare Energien,Summe
0,2020,65940.0,475569.0,178185,692083.000000,454568.000000,105453.0000,1.971798e+06
1,2019,71030.0,453219.0,167011,670399.000000,445543.000000,97251.0000,1.904453e+06
2,2018,64707.0,395824.0,164823,634186.000000,449382.000000,93198.0000,1.802120e+06
3,2017,72540.0,380102.0,141845,642589.000000,476561.000000,83822.0000,1.797459e+06
4,2016,73966.0,288248.0,137153,627164.000000,469404.000000,80310.0000,1.676245e+06
5,2015,68317.0,285143.0,139415,621918.000000,454668.000000,74323.0000,1.643784e+06
6,2014,70513.0,206486.0,129803,604039.000000,439277.000000,68421.0000,1.518539e+06
7,2013,82792.8,186148.8,111636,645783.445199,410517.535325,61777.4744,1.498656e+06
8,2012,78318.0,182412.0,94968,587288.464440,382286.550100,59536.0800,1.384809e+06
9,2011,63622.8,175978.8,69624,679372.006000,430920.558959,42987.2000,1.462505e+06

In [45]:
#read non-renewable energies from csv
dee_df = pd.read_csv("data/deutschland_primaerenergie.csv",delimiter=",")

#clean up labels
dee_df.rename({"Sonstige Energieträger":"Andere Energieträger","Mineralöle und Mineralöl Produkte":"Mineralöle und Mineralöl produkte"},axis=1,inplace=True)

#drop unnecessary columns
dee_df.drop(columns=["Energiebilanz der Bundesrepublik 2020","Zeile"],inplace=True)

dee_df

,Jahr,Steinkohle,Braunkohle,Mineralöle und Mineralöl produkte,Gase,Gesamt Erneuerbare Energieträger,Stromaustauschsaldo,Kernenergie,Andere Energieträger,Summe
0,2020,895778.114,957741.584,4086816.243,3144335.962,1971798,-67982.4,702349.091,204074,1.189491e+07
1,2019,1084226.000,1162958.000,4511394.000,3221866.000,1904453,-117605.0,818952.000,218297,1.280454e+07
2,2018,1428156.000,1480539.000,4451801.000,3098631.000,1802120,-175446.0,829136.000,214105,1.312904e+07
3,2017,1502051.000,1507296.000,4671315.000,3166586.000,1797459,-188852.0,832623.000,234513,1.352299e+07
4,2016,1693073.000,1510693.000,4566079.000,3067552.000,1676245,-181890.0,923276.000,235586,1.349062e+07
5,2015,1728706.000,1565495.000,4491499.000,2780634.000,1643784,-173817.0,1001297.000,223911,1.326151e+07
6,2014,1759260.000,1573962.000,4492772.000,2671682.000,1518539,-121993.0,1059583.000,225782,1.317959e+07
7,2013,1839516.000,1628719.000,4627899.000,3073548.000,1498656,-115899.0,1061345.000,207824,1.382161e+07
8,2012,1725320.000,1644547.000,4526545.000,2933220.000,1384809,-83121.0,1085011.000,230726,1.344706e+07
9,2011,1714525.000,1564323.000,4524525.000,2923374.000,1462506,-22576.0,1177858.000,254801,1.359933e+07

In [46]:
#merge renewable and non-renewable energy dataframes
merged_df = pd.merge(de_df,dee_df,on=["Jahr"],how="outer")
merged_df

,Jahr,Wasserkraft,Windkraft,Solarenergie,Biomasse,"Klärgas, Deponiegas",Sonstige erneuerbare Energien,Summe_x,Steinkohle,Braunkohle,Mineralöle und Mineralöl produkte,Gase,Gesamt Erneuerbare Energieträger,Stromaustauschsaldo,Kernenergie,Andere Energieträger,Summe_y
0,2020,65940.0,475569.0,178185,692083.000000,454568.000000,105453.0000,1.971798e+06,895778.114,957741.584,4086816.243,3144335.962,1971798,-67982.4,702349.091,204074,1.189491e+07
1,2019,71030.0,453219.0,167011,670399.000000,445543.000000,97251.0000,1.904453e+06,1084226.000,1162958.000,4511394.000,3221866.000,1904453,-117605.0,818952.000,218297,1.280454e+07
2,2018,64707.0,395824.0,164823,634186.000000,449382.000000,93198.0000,1.802120e+06,1428156.000,1480539.000,4451801.000,3098631.000,1802120,-175446.0,829136.000,214105,1.312904e+07
3,2017,72540.0,380102.0,141845,642589.000000,476561.000000,83822.0000,1.797459e+06,1502051.000,1507296.000,4671315.000,3166586.000,1797459,-188852.0,832623.000,234513,1.352299e+07
4,2016,73966.0,288248.0,137153,627164.000000,469404.000000,80310.0000,1.676245e+06,1693073.000,1510693.000,4566079.000,3067552.000,1676245,-181890.0,923276.000,235586,1.349062e+07
5,2015,68317.0,285143.0,139415,621918.000000,454668.000000,74323.0000,1.643784e+06,1728706.000,1565495.000,4491499.000,2780634.000,1643784,-173817.0,1001297.000,223911,1.326151e+07
6,2014,70513.0,206486.0,129803,604039.000000,439277.000000,68421.0000,1.518539e+06,1759260.000,1573962.000,4492772.000,2671682.000,1518539,-121993.0,1059583.000,225782,1.317959e+07
7,2013,82792.8,186148.8,111636,645783.445199,410517.535325,61777.4744,1.498656e+06,1839516.000,1628719.000,4627899.000,3073548.000,1498656,-115899.0,1061345.000,207824,1.382161e+07
8,2012,78318.0,182412.0,94968,587288.464440,382286.550100,59536.0800,1.384809e+06,1725320.000,1644547.000,4526545.000,2933220.000,1384809,-83121.0,1085011.000,230726,1.344706e+07
9,2011,63622.8,175978.8,69624,679372.006000,430920.558959,42987.2000,1.462505e+06,1714525.000,1564323.000,4524525.000,2923374.000,1462506,-22576.0,1177858.000,254801,1.359933e+07

In [47]:
#test values
print(merged_df['Gesamt Erneuerbare Energieträger'].equals(merged_df['Summe_x']))

False

In [48]:
#Sums are not equal due to small rounding errors in original data

In [49]:
#calculate aggregate values for renewable and non-renewable energies
merged_df["Gesamt Nichterneuerbar"] = merged_df["Summe_y"]-merged_df["Gesamt Erneuerbare Energieträger"]
merged_df["Anteil Erneuerbar"] = merged_df["Gesamt Erneuerbare Energieträger"] / merged_df["Summe_y"] * 100

#rename totals column
merged_df.drop(columns=['Summe_x'],inplace=True)
merged_df.rename(columns={'Summe_y':'Insgesamt'},inplace=True)

#change year column to string to facilitate renaming columns after pivot
merged_df['Jahr'] = merged_df['Jahr'].astype(str)

merged_df

,Jahr,Wasserkraft,Windkraft,Solarenergie,Biomasse,"Klärgas, Deponiegas",Sonstige erneuerbare Energien,Steinkohle,Braunkohle,Mineralöle und Mineralöl produkte,Gase,Gesamt Erneuerbare Energieträger,Stromaustauschsaldo,Kernenergie,Andere Energieträger,Insgesamt,Gesamt Nichterneuerbar,Anteil Erneuerbar
0,2020,65940.0,475569.0,178185,692083.000000,454568.000000,105453.0000,895778.114,957741.584,4086816.243,3144335.962,1971798,-67982.4,702349.091,204074,1.189491e+07,9.923113e+06,16.576821
1,2019,71030.0,453219.0,167011,670399.000000,445543.000000,97251.0000,1084226.000,1162958.000,4511394.000,3221866.000,1904453,-117605.0,818952.000,218297,1.280454e+07,1.090009e+07,14.873260
2,2018,64707.0,395824.0,164823,634186.000000,449382.000000,93198.0000,1428156.000,1480539.000,4451801.000,3098631.000,1802120,-175446.0,829136.000,214105,1.312904e+07,1.132692e+07,13.726210
3,2017,72540.0,380102.0,141845,642589.000000,476561.000000,83822.0000,1502051.000,1507296.000,4671315.000,3166586.000,1797459,-188852.0,832623.000,234513,1.352299e+07,1.172553e+07,13.291876
4,2016,73966.0,288248.0,137153,627164.000000,469404.000000,80310.0000,1693073.000,1510693.000,4566079.000,3067552.000,1676245,-181890.0,923276.000,235586,1.349062e+07,1.181437e+07,12.425265
5,2015,68317.0,285143.0,139415,621918.000000,454668.000000,74323.0000,1728706.000,1565495.000,4491499.000,2780634.000,1643784,-173817.0,1001297.000,223911,1.326151e+07,1.161773e+07,12.395150
6,2014,70513.0,206486.0,129803,604039.000000,439277.000000,68421.0000,1759260.000,1573962.000,4492772.000,2671682.000,1518539,-121993.0,1059583.000,225782,1.317959e+07,1.166105e+07,11.521901
7,2013,82792.8,186148.8,111636,645783.445199,410517.535325,61777.4744,1839516.000,1628719.000,4627899.000,3073548.000,1498656,-115899.0,1061345.000,207824,1.382161e+07,1.232295e+07,10.842848
8,2012,78318.0,182412.0,94968,587288.464440,382286.550100,59536.0800,1725320.000,1644547.000,4526545.000,2933220.000,1384809,-83121.0,1085011.000,230726,1.344706e+07,1.206225e+07,10.298230
9,2011,63622.8,175978.8,69624,679372.006000,430920.558959,42987.2000,1714525.000,1564323.000,4524525.000,2923374.000,1462506,-22576.0,1177858.000,254801,1.359933e+07,1.213683e+07,10.754247

In [50]:
merged_df['Land']='Deutschland'
merged_df.columns

Index(['Jahr', 'Wasserkraft', 'Windkraft', 'Solarenergie', 'Biomasse',
       'Klärgas, Deponiegas', 'Sonstige erneuerbare Energien', 'Steinkohle',
       'Braunkohle', 'Mineralöle und Mineralöl produkte', 'Gase',
       'Gesamt Erneuerbare Energieträger', 'Stromaustauschsaldo',
       'Kernenergie', 'Andere Energieträger', 'Insgesamt',
       'Gesamt Nichterneuerbar', 'Anteil Erneuerbar', 'Land'],
      dtype='object')

In [51]:
#pivot table to have regions in rows and years and energy type in columns
final_df = merged_df.pivot(index = 'Land', columns = ['Jahr'], values= ['Insgesamt', 'Steinkohle', 'Braunkohle',
       'Mineralöle und Mineralöl produkte', 'Gase',
       'Gesamt Erneuerbare Energieträger', 'Stromaustauschsaldo',
       'Kernenergie', 'Andere Energieträger', 'Klärgas, Deponiegas',
       'Wasserkraft', 'Windkraft', 'Solarenergie', 'Biomasse',
       'Sonstige erneuerbare Energien', 'Gesamt Nichterneuerbar',
       'Anteil Erneuerbar'])

#collapse levels of column names and join energy type to year
final_df.columns = final_df.columns.map('_'.join)

#prepend all columns with indicator name
final_df=final_df.add_prefix('energy_primaryconsumption_')

final_df

,energy_primaryconsumption_Insgesamt_2011,energy_primaryconsumption_Insgesamt_2012,energy_primaryconsumption_Insgesamt_2013,energy_primaryconsumption_Insgesamt_2014,energy_primaryconsumption_Insgesamt_2015,energy_primaryconsumption_Insgesamt_2016,energy_primaryconsumption_Insgesamt_2017,energy_primaryconsumption_Insgesamt_2018,energy_primaryconsumption_Insgesamt_2019,energy_primaryconsumption_Insgesamt_2020,...,energy_primaryconsumption_Anteil Erneuerbar_2011,energy_primaryconsumption_Anteil Erneuerbar_2012,energy_primaryconsumption_Anteil Erneuerbar_2013,energy_primaryconsumption_Anteil Erneuerbar_2014,energy_primaryconsumption_Anteil Erneuerbar_2015,energy_primaryconsumption_Anteil Erneuerbar_2016,energy_primaryconsumption_Anteil Erneuerbar_2017,energy_primaryconsumption_Anteil Erneuerbar_2018,energy_primaryconsumption_Anteil Erneuerbar_2019,energy_primaryconsumption_Anteil Erneuerbar_2020
Land,,,,,,,,,,,,,,,,,,,,,
Deutschland,13599334.0,13447059.0,13821608.0,13179587.0,13261510.0,13490618.0,13522990.0,13129043.0,12804543.0,1.189491e+07,...,10.754247,10.29823,10.842848,11.521901,12.39515,12.425265,13.291876,13.72621,14.87326,16.576821

In [52]:
#add AGS ids from the regions dictionary using the region names
final_df['AGS']=final_df.index.map(regions)

#set AGS as index and copy region names to first column
first_column=final_df.index
final_df.set_index('AGS', inplace=True)
final_df.insert(0,'Name',first_column)

final_df

,Name,energy_primaryconsumption_Insgesamt_2011,energy_primaryconsumption_Insgesamt_2012,energy_primaryconsumption_Insgesamt_2013,energy_primaryconsumption_Insgesamt_2014,energy_primaryconsumption_Insgesamt_2015,energy_primaryconsumption_Insgesamt_2016,energy_primaryconsumption_Insgesamt_2017,energy_primaryconsumption_Insgesamt_2018,energy_primaryconsumption_Insgesamt_2019,...,energy_primaryconsumption_Anteil Erneuerbar_2011,energy_primaryconsumption_Anteil Erneuerbar_2012,energy_primaryconsumption_Anteil Erneuerbar_2013,energy_primaryconsumption_Anteil Erneuerbar_2014,energy_primaryconsumption_Anteil Erneuerbar_2015,energy_primaryconsumption_Anteil Erneuerbar_2016,energy_primaryconsumption_Anteil Erneuerbar_2017,energy_primaryconsumption_Anteil Erneuerbar_2018,energy_primaryconsumption_Anteil Erneuerbar_2019,energy_primaryconsumption_Anteil Erneuerbar_2020
AGS,,,,,,,,,,,,,,,,,,,,,
0,Deutschland,13599334.0,13447059.0,13821608.0,13179587.0,13261510.0,13490618.0,13522990.0,13129043.0,12804543.0,...,10.754247,10.29823,10.842848,11.521901,12.39515,12.425265,13.291876,13.72621,14.87326,16.576821

In [53]:
#save dataframe to file
final_df.to_csv("data/final_data_deutschland_energy_primaryconsumption.csv")