In [338]:
#load final data file for mobility indicator
#and use most current data to create ranking
#document whether the landkreis belongs to the top, middle or bottom third

In [339]:
# import necessary libraries
import numpy as np
import pandas as pd

## 1. Landkreise

In [340]:
#dictionary to assign thirds based on rank
bins=[1,133,266,399]
names=['oberen Drittel','mittleren Drittel','unteren Drittel']

In [341]:
#load list of current landkreise
kreise_akt = pd.read_csv("../general_data/gerics_landkreis_names_for_ranking.csv")
kreise_akt = kreise_akt[['AGS','Gerics_Name','Gerics_Bundesland']].copy()

kreise_liste = kreise_akt['AGS'].to_list()

kreise_akt

       AGS          Gerics_Name    Gerics_Bundesland
0     5124            Wuppertal  Nordrhein-Westfalen
1    16073  Saalfeld-Rudolstadt            Thüringen
2    16072            Sonneberg            Thüringen
3    16071        Weimarer Land            Thüringen
4    16070            Ilm-Kreis            Thüringen
..     ...                  ...                  ...
396   5116      Mönchengladbach  Nordrhein-Westfalen
397   5562       Recklinghausen  Nordrhein-Westfalen
398   7338    Rhein-Pfalz-Kreis      Rheinland-Pfalz
399   5162    Rhein-Kreis Neuss  Nordrhein-Westfalen
400   5166              Viersen  Nordrhein-Westfalen

[401 rows x 3 columns]

In [342]:
#load dataset from local file
enr_kreise = pd.read_csv("data/final_data_landkreis_energy_industryenergy.csv")
enr_kreise.head(20)

,AGS,Name,energy_industry_consumption_Erdgas_2003,energy_industry_consumption_Erdgas_2004,energy_industry_consumption_Erdgas_2005,energy_industry_consumption_Erdgas_2006,energy_industry_consumption_Erdgas_2007,energy_industry_consumption_Erdgas_2008,energy_industry_consumption_Erdgas_2009,energy_industry_consumption_Erdgas_2010,...,energy_industry_consumption_Anteil_Fossil_2012,energy_industry_consumption_Anteil_Fossil_2013,energy_industry_consumption_Anteil_Fossil_2014,energy_industry_consumption_Anteil_Fossil_2015,energy_industry_consumption_Anteil_Fossil_2016,energy_industry_consumption_Anteil_Fossil_2017,energy_industry_consumption_Anteil_Fossil_2018,energy_industry_consumption_Anteil_Fossil_2019,energy_industry_consumption_Anteil_Fossil_2020,Unit
0,0,Deutschland,1.013851e+09,1.035524e+09,1.042020e+09,1.038921e+09,1.067395e+09,1.063796e+09,961175019.0,1.083953e+09,...,45.318605,46.530801,45.645344,46.271690,48.188767,48.872186,47.390331,47.037428,48.401421,Tsd. MJ
1,1,Schleswig-Holstein,1.671949e+07,1.595202e+07,1.649519e+07,1.624940e+07,1.728819e+07,1.759618e+07,17799405.0,2.159016e+07,...,66.588986,48.244199,58.151228,52.925903,58.170039,65.338006,58.660758,59.462441,59.075141,Tsd. MJ
2,2,Hamburg,2.083285e+07,2.269981e+07,1.969420e+07,2.205925e+07,2.176798e+07,2.145118e+07,18353140.0,2.125804e+07,...,30.459476,34.906157,33.241896,34.323086,36.172832,37.344883,38.805590,36.917671,36.391664,Tsd. MJ
3,3,Niedersachsen,1.382405e+08,1.406649e+08,1.494298e+08,1.391713e+08,1.378556e+08,1.382421e+08,127744815.0,1.380326e+08,...,54.170371,38.946753,36.857894,37.755971,35.694607,36.760066,34.846765,35.099053,36.467798,Tsd. MJ
4,4,Bremen,1.379781e+07,1.342768e+07,1.190057e+07,1.350348e+07,1.351306e+07,1.355372e+07,11043752.0,1.261753e+07,...,75.906546,77.779960,14.039173,12.519915,12.592543,14.951455,14.194956,14.352792,14.325108,Tsd. MJ
5,5,Nordrhein-Westfalen,2.807067e+08,2.774706e+08,2.625846e+08,2.535090e+08,2.806044e+08,2.817708e+08,233367326.0,2.602855e+08,...,43.801470,46.174056,44.202159,44.230784,49.220593,51.741548,47.892469,45.677625,50.078271,Tsd. MJ
6,6,Hessen,5.604089e+07,5.402528e+07,5.620296e+07,5.577374e+07,5.525396e+07,5.177774e+07,42261400.0,4.734789e+07,...,42.333348,42.531913,42.310099,42.561408,43.013843,46.526447,46.527594,46.919691,47.042816,Tsd. MJ
7,7,Rheinland-Pfalz,1.098838e+08,1.102685e+08,1.227501e+08,1.182339e+08,1.162946e+08,1.200617e+08,127010817.0,1.506895e+08,...,47.895874,48.927187,48.581329,49.455552,51.123433,48.452741,50.390416,51.419627,53.899586,Tsd. MJ
8,8,"Baden-Württemberg, Land",7.786167e+07,8.062984e+07,8.351528e+07,8.328592e+07,8.612030e+07,8.729802e+07,77873772.0,8.215965e+07,...,35.643226,36.495020,36.154966,37.269686,36.427260,36.567758,36.098879,36.110980,36.010339,Tsd. MJ
9,9,Bayern,1.141887e+08,1.248360e+08,1.236809e+08,1.246059e+08,1.259879e+08,1.219521e+08,113348258.0,1.370715e+08,...,44.397384,43.561785,44.119681,45.329387,44.762994,45.074592,41.179799,41.330194,43.621644,Tsd. MJ
10,10,Saarland,8.941282e+06,1.037069e+07,1.067650e+07,1.113344e+07,1.059451e+07,1.190176e+07,10657172.0,1.207192e+07,...,63.533028,63.262631,61.832029,61.120148,60.524439,62.173095,9.631425,63.720529,62.854170,Tsd. MJ
11,11,Berlin,3.881270e+06,3.679908e+06,3.388890e+06,4.662937e+06,5.997800e+06,5.741925e+06,4403581.0,4.782369e+06,...,48.854192,48.391541,40.663059,42.337879,36.718566,37.661926,39.964266,39.975420,38.322684,Tsd. MJ
12,12,Brandenburg,3.088019e+07,3.306067e+07,2.911481e+07,4.038347e+07,3.359762e+07,3.341006e+07,30220403.0,3.299168e+07,...,35.000941,18.015449,17.599828,17.045271,17.311244,17.795214,17.953348,18.808469,35.691672,Tsd. MJ
13,13,Mecklenburg-Vorpommern,6.890377e+06,6.903438e+06,6.617945e+06,6.525760e+06,6.577080e+06,6.589558e+06,6419580.0,7.462858e+06,...,40.761146,38.858756,37.661437,38.901700,39.721800,39.163014,40.255761,40.868755,42.230654,Tsd. MJ
14,14,Sachsen,3.595346e+07,3.833151e+07,3.850557e+07,3.971019e+07,4.020010e+07,3.963566e+07,34836018.0,3.934794e+07,...,28.867177,31.567689,30.462903,32.978222,31.580185,30.920005,31.110080,35.626629,29.455292,Tsd. MJ
15,15,Sachsen-Anhalt,8.229662e+07,8.591186e+07,8.929265e+07,9.156509e+07,9.647984e+07,9.391787e+07,89101497.0,9.625267e+07,...,50.240909,49.014396,48.528791,46.951925,48.313781,48.122991,49.135721,49.233924,48.529817,Tsd. MJ
16,16,Thüringen,1.673571e+07,1.729094e+07,1.817021e+07,1.879666e+07,1.926179e+07,1.889586e+07,16734081.0,1.999074e+07,...,40.024862,38.918515,39.342194,38.830176,38.957748,40.304031,39.443248,39.203790,39.096760,Tsd. MJ
17,31,"Braunschweig, Stat. Region",2.461062e+07,2.357890e+07,2.355205e+07,2.337744e+07,2.373541e+07,2.335937e+07,19767384.0,2.358803e+07,...,16.490072,16.567785,15.592156,18.340222,16.001981,16.272641,NaN,NaN,NaN,Tsd. MJ
18,32,"Hannover, Stat. Region",2.968349e+07,3.000715e+07,3.352292e+07,3.042189e+07,2.967761e+07,2.980594e+07,26514189.0,2.771066e+07,...,56.245799,54.039752,54.939330,50.613374,56.404327,56.729080,55.359543,55.153620,56.987350,Tsd. MJ
19,33,"Lüneburg, Stat. Region",3.161179e+07,3.300651e+07,3.342900e+07,2.740791e+07,2.628697e+07,2.685335e+07,26743808.0,3.073955e+07,...,53.439411,57.184406,49.676136,45.707122,46.770998,42.779448,NaN,NaN,NaN,Tsd. MJ

In [343]:
enr_filter = enr_kreise[enr_kreise['AGS'].isin(kreise_liste)].copy().reset_index(drop=True)
enr_filter

,AGS,Name,energy_industry_consumption_Erdgas_2003,energy_industry_consumption_Erdgas_2004,energy_industry_consumption_Erdgas_2005,energy_industry_consumption_Erdgas_2006,energy_industry_consumption_Erdgas_2007,energy_industry_consumption_Erdgas_2008,energy_industry_consumption_Erdgas_2009,energy_industry_consumption_Erdgas_2010,...,energy_industry_consumption_Anteil_Fossil_2012,energy_industry_consumption_Anteil_Fossil_2013,energy_industry_consumption_Anteil_Fossil_2014,energy_industry_consumption_Anteil_Fossil_2015,energy_industry_consumption_Anteil_Fossil_2016,energy_industry_consumption_Anteil_Fossil_2017,energy_industry_consumption_Anteil_Fossil_2018,energy_industry_consumption_Anteil_Fossil_2019,energy_industry_consumption_Anteil_Fossil_2020,Unit
0,1001,"Flensburg, kreisfreie Stadt",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.098210,1.909765,2.229251,1.902391,2.235159,1.932101,2.375554,1.725703,1.513574,Tsd. MJ
1,1002,"Kiel, Landeshauptstadt, kreisfreie Stadt",290230.0,280784.0,257216.0,211772.0,242025.0,211546.0,187041.0,157457.0,...,23.100952,34.114924,25.269589,NaN,NaN,NaN,NaN,NaN,NaN,Tsd. MJ
2,1003,"Lübeck, Hansestadt, kreisfreie Stadt",1137701.0,1177485.0,1159562.0,1140148.0,1072777.0,1010287.0,852204.0,885690.0,...,54.134119,55.153998,53.601548,54.449220,53.990810,53.779804,53.831384,54.311320,54.527728,Tsd. MJ
3,1004,"Neumünster, kreisfreie Stadt",215630.0,179838.0,247827.0,219980.0,214524.0,187991.0,206886.0,220766.0,...,41.853989,42.195788,NaN,51.648182,51.093401,52.413384,54.987644,57.542670,59.395097,Tsd. MJ
4,1051,"Dithmarschen, Landkreis",4346109.0,3724942.0,4491184.0,4580027.0,5968665.0,5864909.0,6929893.0,8503683.0,...,49.846012,49.268608,43.756718,43.981814,44.742330,43.314341,45.425871,45.099824,46.346526,Tsd. MJ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,16073,"Saalfeld-Rudolstadt, Kreis",2053782.0,2112690.0,NaN,2024082.0,1997135.0,2046345.0,1739795.0,1877018.0,...,26.105595,26.919802,25.855693,25.152610,25.437667,25.511068,22.590440,22.767905,23.392663,Tsd. MJ
395,16074,Saale-Holzland-Kreis,704217.0,649464.0,764766.0,827080.0,738184.0,1002646.0,731433.0,861809.0,...,52.248747,56.838759,55.890507,48.152241,56.216800,55.942046,57.037797,56.008589,54.634141,Tsd. MJ
396,16075,Saale-Orla-Kreis,1319632.0,1044440.0,1062754.0,1079436.0,984387.0,890090.0,946935.0,1103122.0,...,8.898911,8.776728,8.454489,8.641901,10.175402,9.969400,11.121372,10.917198,10.538495,Tsd. MJ
397,16076,"Greiz, Kreis",827129.0,943773.0,950639.0,963235.0,1198611.0,1079776.0,959442.0,1156630.0,...,73.439363,73.867253,72.839068,34.635666,35.382495,36.203051,36.841713,38.698614,34.897605,Tsd. MJ
398,16077,"Altenburger Land, Kreis",240813.0,255737.0,257623.0,624921.0,688703.0,348654.0,366252.0,439740.0,...,37.673621,38.909880,35.558650,37.806811,37.186915,36.076405,35.849376,38.480050,39.247177,Tsd. MJ

In [344]:
#check to see if data on any landkreise missing
missing = [x for x in kreise_liste if x not in enr_kreise['AGS'].to_list()]
missing

[11000, 2000]

In [345]:
#load gerics names and replace
enr_filter= enr_filter.merge(kreise_akt, on='AGS',how='left').drop(columns='Name')
enr_filter

,AGS,energy_industry_consumption_Erdgas_2003,energy_industry_consumption_Erdgas_2004,energy_industry_consumption_Erdgas_2005,energy_industry_consumption_Erdgas_2006,energy_industry_consumption_Erdgas_2007,energy_industry_consumption_Erdgas_2008,energy_industry_consumption_Erdgas_2009,energy_industry_consumption_Erdgas_2010,energy_industry_consumption_Erdgas_2011,...,energy_industry_consumption_Anteil_Fossil_2014,energy_industry_consumption_Anteil_Fossil_2015,energy_industry_consumption_Anteil_Fossil_2016,energy_industry_consumption_Anteil_Fossil_2017,energy_industry_consumption_Anteil_Fossil_2018,energy_industry_consumption_Anteil_Fossil_2019,energy_industry_consumption_Anteil_Fossil_2020,Unit,Gerics_Name,Gerics_Bundesland
0,1001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.229251,1.902391,2.235159,1.932101,2.375554,1.725703,1.513574,Tsd. MJ,Flensburg,Schleswig-Holstein
1,1002,290230.0,280784.0,257216.0,211772.0,242025.0,211546.0,187041.0,157457.0,209748.0,...,25.269589,NaN,NaN,NaN,NaN,NaN,NaN,Tsd. MJ,Kiel,Schleswig-Holstein
2,1003,1137701.0,1177485.0,1159562.0,1140148.0,1072777.0,1010287.0,852204.0,885690.0,812604.0,...,53.601548,54.449220,53.990810,53.779804,53.831384,54.311320,54.527728,Tsd. MJ,Lübeck,Schleswig-Holstein
3,1004,215630.0,179838.0,247827.0,219980.0,214524.0,187991.0,206886.0,220766.0,291674.0,...,NaN,51.648182,51.093401,52.413384,54.987644,57.542670,59.395097,Tsd. MJ,Neumünster,Schleswig-Holstein
4,1051,4346109.0,3724942.0,4491184.0,4580027.0,5968665.0,5864909.0,6929893.0,8503683.0,9172863.0,...,43.756718,43.981814,44.742330,43.314341,45.425871,45.099824,46.346526,Tsd. MJ,Dithmarschen,Schleswig-Holstein
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,16073,2053782.0,2112690.0,NaN,2024082.0,1997135.0,2046345.0,1739795.0,1877018.0,1918528.0,...,25.855693,25.152610,25.437667,25.511068,22.590440,22.767905,23.392663,Tsd. MJ,Saalfeld-Rudolstadt,Thüringen
395,16074,704217.0,649464.0,764766.0,827080.0,738184.0,1002646.0,731433.0,861809.0,835482.0,...,55.890507,48.152241,56.216800,55.942046,57.037797,56.008589,54.634141,Tsd. MJ,Saale-Holzland-Kreis,Thüringen
396,16075,1319632.0,1044440.0,1062754.0,1079436.0,984387.0,890090.0,946935.0,1103122.0,1078134.0,...,8.454489,8.641901,10.175402,9.969400,11.121372,10.917198,10.538495,Tsd. MJ,Saale-Orla-Kreis,Thüringen
397,16076,827129.0,943773.0,950639.0,963235.0,1198611.0,1079776.0,959442.0,1156630.0,908594.0,...,72.839068,34.635666,35.382495,36.203051,36.841713,38.698614,34.897605,Tsd. MJ,Greiz,Thüringen
398,16077,240813.0,255737.0,257623.0,624921.0,688703.0,348654.0,366252.0,439740.0,394340.0,...,35.558650,37.806811,37.186915,36.076405,35.849376,38.480050,39.247177,Tsd. MJ,Altenburger Land,Thüringen

In [346]:
print(enr_filter.columns)

Index(['AGS', 'energy_industry_consumption_Erdgas_2003',
       'energy_industry_consumption_Erdgas_2004',
       'energy_industry_consumption_Erdgas_2005',
       'energy_industry_consumption_Erdgas_2006',
       'energy_industry_consumption_Erdgas_2007',
       'energy_industry_consumption_Erdgas_2008',
       'energy_industry_consumption_Erdgas_2009',
       'energy_industry_consumption_Erdgas_2010',
       'energy_industry_consumption_Erdgas_2011',
       ...
       'energy_industry_consumption_Anteil_Fossil_2014',
       'energy_industry_consumption_Anteil_Fossil_2015',
       'energy_industry_consumption_Anteil_Fossil_2016',
       'energy_industry_consumption_Anteil_Fossil_2017',
       'energy_industry_consumption_Anteil_Fossil_2018',
       'energy_industry_consumption_Anteil_Fossil_2019',
       'energy_industry_consumption_Anteil_Fossil_2020', 'Unit', 'Gerics_Name',
       'Gerics_Bundesland'],
      dtype='object', length=184)

In [347]:
column_list = [x for x in enr_filter.columns if '_2020' in x if '_Anteil_' not in x]
column_list.extend(['AGS','Gerics_Name',
 'Gerics_Bundesland'])
column_list

['energy_industry_consumption_Erdgas_2020',
 'energy_industry_consumption_Erneuerbare Energien_2020',
 'energy_industry_consumption_Heizöl_2020',
 'energy_industry_consumption_Kohle_2020',
 'energy_industry_consumption_Sonstige Energieträger_2020',
 'energy_industry_consumption_Strom_2020',
 'energy_industry_consumption_Wärme_2020',
 'energy_industry_consumption_insgesamt_2020',
 'AGS',
 'Gerics_Name',
 'Gerics_Bundesland']

In [348]:
enr_energien = enr_filter[column_list].copy()
enr_energien['Insgesamt'] = enr_energien['energy_industry_consumption_insgesamt_2020']
enr_energien['Erneuerbare'] = enr_energien[ 'energy_industry_consumption_Erneuerbare Energien_2020']
enr_energien['Fossil'] = enr_energien[['energy_industry_consumption_Heizöl_2020','energy_industry_consumption_Kohle_2020']].sum(axis=1)
enr_energien['Andere'] = enr_energien[['energy_industry_consumption_Sonstige Energieträger_2020','energy_industry_consumption_Strom_2020','energy_industry_consumption_Wärme_2020']].sum(axis=1)
enr_energien['Geheim'] = enr_energien['energy_industry_consumption_insgesamt_2020']-enr_energien[['Fossil','Andere','Erneuerbare']].sum(axis=1)
enr_energien['Erneuerbare_Anteil'] = enr_energien['Erneuerbare']*100/enr_energien['Insgesamt']
enr_energien['Fossil_Anteil'] = enr_energien['Fossil']*100/enr_energien['Insgesamt']
enr_energien['Andere_Anteil'] = enr_energien['Andere']*100/enr_energien['Insgesamt']
enr_energien['Geheim_Anteil'] = enr_energien['Geheim']*100/enr_energien['Insgesamt']
enr_energien['Geheim_Anteil'].fillna('100',inplace=True)
enr_energien =  enr_energien[['AGS', 'Gerics_Name','Gerics_Bundesland','Erneuerbare_Anteil','Fossil_Anteil','Andere_Anteil','Geheim_Anteil','Insgesamt']]
enr_energien.sort_values('Fossil_Anteil',ascending=True,inplace=True)
enr_energien

,AGS,Gerics_Name,Gerics_Bundesland,Erneuerbare_Anteil,Fossil_Anteil,Andere_Anteil,Geheim_Anteil,Insgesamt
338,12071,Spree-Neiße,Brandenburg,NaN,0.0,30.748508,69.251492,12284671.0
35,3354,Lüchow-Dannenberg,Niedersachsen,0.0,0.0,45.294145,54.705855,1042563.0
139,6635,Waldeck-Frankenberg,Hessen,NaN,0.0,45.630159,54.369841,5730552.0
302,9679,Würzburg,Bayern,NaN,0.0,20.298686,79.701314,2788481.0
93,5562,Recklinghausen,Nordrhein-Westfalen,NaN,0.0,33.114183,66.885817,60207126.0
...,...,...,...,...,...,...,...,...
325,12053,Frankfurt (Oder),Brandenburg,NaN,NaN,NaN,100,NaN
331,12064,Märkisch-Oderland,Brandenburg,NaN,NaN,NaN,100,NaN
333,12066,Oberspreewald-Lausitz,Brandenburg,NaN,NaN,NaN,100,NaN
335,12068,Ostprignitz-Ruppin,Brandenburg,NaN,NaN,NaN,100,NaN
340,12073,Uckermark,Brandenburg,NaN,NaN,NaN,100,NaN

In [349]:
#add ranking
enr_energien['rank'] = ""
enr_energien['third'] = ""
enr_energien

,AGS,Gerics_Name,Gerics_Bundesland,Erneuerbare_Anteil,Fossil_Anteil,Andere_Anteil,Geheim_Anteil,Insgesamt,rank,third
338,12071,Spree-Neiße,Brandenburg,NaN,0.0,30.748508,69.251492,12284671.0,,
35,3354,Lüchow-Dannenberg,Niedersachsen,0.0,0.0,45.294145,54.705855,1042563.0,,
139,6635,Waldeck-Frankenberg,Hessen,NaN,0.0,45.630159,54.369841,5730552.0,,
302,9679,Würzburg,Bayern,NaN,0.0,20.298686,79.701314,2788481.0,,
93,5562,Recklinghausen,Nordrhein-Westfalen,NaN,0.0,33.114183,66.885817,60207126.0,,
...,...,...,...,...,...,...,...,...,...,...
325,12053,Frankfurt (Oder),Brandenburg,NaN,NaN,NaN,100,NaN,,
331,12064,Märkisch-Oderland,Brandenburg,NaN,NaN,NaN,100,NaN,,
333,12066,Oberspreewald-Lausitz,Brandenburg,NaN,NaN,NaN,100,NaN,,
335,12068,Ostprignitz-Ruppin,Brandenburg,NaN,NaN,NaN,100,NaN,,
340,12073,Uckermark,Brandenburg,NaN,NaN,NaN,100,NaN,,

In [350]:
enr_final = enr_energien.copy()
enr_final.columns=['AGS', 'Name','Bundesland','energy_Erneuerbare_Anteil','energy_Fossil_Anteil','energy_Andere_Anteil','energy_Geheim_Anteil','energy_Insgesamt', 'energy_rank','energy_third']
enr_final

,AGS,Name,Bundesland,energy_Erneuerbare_Anteil,energy_Fossil_Anteil,energy_Andere_Anteil,energy_Geheim_Anteil,energy_Insgesamt,energy_rank,energy_third
338,12071,Spree-Neiße,Brandenburg,NaN,0.0,30.748508,69.251492,12284671.0,,
35,3354,Lüchow-Dannenberg,Niedersachsen,0.0,0.0,45.294145,54.705855,1042563.0,,
139,6635,Waldeck-Frankenberg,Hessen,NaN,0.0,45.630159,54.369841,5730552.0,,
302,9679,Würzburg,Bayern,NaN,0.0,20.298686,79.701314,2788481.0,,
93,5562,Recklinghausen,Nordrhein-Westfalen,NaN,0.0,33.114183,66.885817,60207126.0,,
...,...,...,...,...,...,...,...,...,...,...
325,12053,Frankfurt (Oder),Brandenburg,NaN,NaN,NaN,100,NaN,,
331,12064,Märkisch-Oderland,Brandenburg,NaN,NaN,NaN,100,NaN,,
333,12066,Oberspreewald-Lausitz,Brandenburg,NaN,NaN,NaN,100,NaN,,
335,12068,Ostprignitz-Ruppin,Brandenburg,NaN,NaN,NaN,100,NaN,,
340,12073,Uckermark,Brandenburg,NaN,NaN,NaN,100,NaN,,

In [351]:
#load bundesland data and merge und bundesland name
blen_df = pd.read_csv("data/final_data_bundesland_energy_primaryconsumption.csv")
blen_df = blen_df.fillna(method='ffill',axis=1)
blen_short = blen_df[['Name','energy_primaryconsumption_Anteil Erneuerbar_2020']].copy()
blen_short.columns=['Bundesland','energy_Anteil_Erneuerbar_Bundesland']
blen_short

                Bundesland energy_Anteil_Erneuerbar_Bundesland
0       Schleswig-Holstein                           29.882406
1                  Hamburg                            5.639384
2            Niedersachsen                           22.507307
3                   Bremen                            7.684384
4      Nordrhein-Westfalen                            5.823425
5                   Hessen                           11.013179
6          Rheinland-Pfalz                           14.531998
7        Baden-Württemberg                           14.170586
8                   Bayern                           20.126032
9                 Saarland                            4.069594
10                  Berlin                            6.109197
11             Brandenburg                           20.836697
12  Mecklenburg-Vorpommern                           41.470171
13                 Sachsen                            9.977345
14          Sachsen-Anhalt                           19.124589
15               Thüringen                           23.429499

In [352]:
enr_merged = enr_final.merge(blen_short,on='Bundesland',how='left')
enr_merged

,AGS,Name,Bundesland,energy_Erneuerbare_Anteil,energy_Fossil_Anteil,energy_Andere_Anteil,energy_Geheim_Anteil,energy_Insgesamt,energy_rank,energy_third,energy_Anteil_Erneuerbar_Bundesland
0,12071,Spree-Neiße,Brandenburg,NaN,0.0,30.748508,69.251492,12284671.0,,,20.836697
1,3354,Lüchow-Dannenberg,Niedersachsen,0.0,0.0,45.294145,54.705855,1042563.0,,,22.507307
2,6635,Waldeck-Frankenberg,Hessen,NaN,0.0,45.630159,54.369841,5730552.0,,,11.013179
3,9679,Würzburg,Bayern,NaN,0.0,20.298686,79.701314,2788481.0,,,20.126032
4,5562,Recklinghausen,Nordrhein-Westfalen,NaN,0.0,33.114183,66.885817,60207126.0,,,5.823425
...,...,...,...,...,...,...,...,...,...,...,...
394,12053,Frankfurt (Oder),Brandenburg,NaN,NaN,NaN,100,NaN,,,20.836697
395,12064,Märkisch-Oderland,Brandenburg,NaN,NaN,NaN,100,NaN,,,20.836697
396,12066,Oberspreewald-Lausitz,Brandenburg,NaN,NaN,NaN,100,NaN,,,20.836697
397,12068,Ostprignitz-Ruppin,Brandenburg,NaN,NaN,NaN,100,NaN,,,20.836697
398,12073,Uckermark,Brandenburg,NaN,NaN,NaN,100,NaN,,,20.836697

## 2. Bundesländer

In [353]:
#dictionary to assign thirds based on rank
bl_bins=[1,5,11,16]
bl_names=['oberen Drittel','mittleren Drittel','unteren Drittel']

In [354]:
blenr_filter = enr_kreise[enr_kreise['AGS']<17].copy()
blenr_filter.replace('Baden-Württemberg, Land','Baden-Württemberg',inplace=True)
blenr_filter['Bundesland'] = blenr_filter['Name']
blenr_filter

,AGS,Name,energy_industry_consumption_Erdgas_2003,energy_industry_consumption_Erdgas_2004,energy_industry_consumption_Erdgas_2005,energy_industry_consumption_Erdgas_2006,energy_industry_consumption_Erdgas_2007,energy_industry_consumption_Erdgas_2008,energy_industry_consumption_Erdgas_2009,energy_industry_consumption_Erdgas_2010,...,energy_industry_consumption_Anteil_Fossil_2013,energy_industry_consumption_Anteil_Fossil_2014,energy_industry_consumption_Anteil_Fossil_2015,energy_industry_consumption_Anteil_Fossil_2016,energy_industry_consumption_Anteil_Fossil_2017,energy_industry_consumption_Anteil_Fossil_2018,energy_industry_consumption_Anteil_Fossil_2019,energy_industry_consumption_Anteil_Fossil_2020,Unit,Bundesland
0,0,Deutschland,1.013851e+09,1.035524e+09,1.042020e+09,1.038921e+09,1.067395e+09,1.063796e+09,961175019.0,1.083953e+09,...,46.530801,45.645344,46.271690,48.188767,48.872186,47.390331,47.037428,48.401421,Tsd. MJ,Deutschland
1,1,Schleswig-Holstein,1.671949e+07,1.595202e+07,1.649519e+07,1.624940e+07,1.728819e+07,1.759618e+07,17799405.0,2.159016e+07,...,48.244199,58.151228,52.925903,58.170039,65.338006,58.660758,59.462441,59.075141,Tsd. MJ,Schleswig-Holstein
2,2,Hamburg,2.083285e+07,2.269981e+07,1.969420e+07,2.205925e+07,2.176798e+07,2.145118e+07,18353140.0,2.125804e+07,...,34.906157,33.241896,34.323086,36.172832,37.344883,38.805590,36.917671,36.391664,Tsd. MJ,Hamburg
3,3,Niedersachsen,1.382405e+08,1.406649e+08,1.494298e+08,1.391713e+08,1.378556e+08,1.382421e+08,127744815.0,1.380326e+08,...,38.946753,36.857894,37.755971,35.694607,36.760066,34.846765,35.099053,36.467798,Tsd. MJ,Niedersachsen
4,4,Bremen,1.379781e+07,1.342768e+07,1.190057e+07,1.350348e+07,1.351306e+07,1.355372e+07,11043752.0,1.261753e+07,...,77.779960,14.039173,12.519915,12.592543,14.951455,14.194956,14.352792,14.325108,Tsd. MJ,Bremen
5,5,Nordrhein-Westfalen,2.807067e+08,2.774706e+08,2.625846e+08,2.535090e+08,2.806044e+08,2.817708e+08,233367326.0,2.602855e+08,...,46.174056,44.202159,44.230784,49.220593,51.741548,47.892469,45.677625,50.078271,Tsd. MJ,Nordrhein-Westfalen
6,6,Hessen,5.604089e+07,5.402528e+07,5.620296e+07,5.577374e+07,5.525396e+07,5.177774e+07,42261400.0,4.734789e+07,...,42.531913,42.310099,42.561408,43.013843,46.526447,46.527594,46.919691,47.042816,Tsd. MJ,Hessen
7,7,Rheinland-Pfalz,1.098838e+08,1.102685e+08,1.227501e+08,1.182339e+08,1.162946e+08,1.200617e+08,127010817.0,1.506895e+08,...,48.927187,48.581329,49.455552,51.123433,48.452741,50.390416,51.419627,53.899586,Tsd. MJ,Rheinland-Pfalz
8,8,Baden-Württemberg,7.786167e+07,8.062984e+07,8.351528e+07,8.328592e+07,8.612030e+07,8.729802e+07,77873772.0,8.215965e+07,...,36.495020,36.154966,37.269686,36.427260,36.567758,36.098879,36.110980,36.010339,Tsd. MJ,Baden-Württemberg
9,9,Bayern,1.141887e+08,1.248360e+08,1.236809e+08,1.246059e+08,1.259879e+08,1.219521e+08,113348258.0,1.370715e+08,...,43.561785,44.119681,45.329387,44.762994,45.074592,41.179799,41.330194,43.621644,Tsd. MJ,Bayern
10,10,Saarland,8.941282e+06,1.037069e+07,1.067650e+07,1.113344e+07,1.059451e+07,1.190176e+07,10657172.0,1.207192e+07,...,63.262631,61.832029,61.120148,60.524439,62.173095,9.631425,63.720529,62.854170,Tsd. MJ,Saarland
11,11,Berlin,3.881270e+06,3.679908e+06,3.388890e+06,4.662937e+06,5.997800e+06,5.741925e+06,4403581.0,4.782369e+06,...,48.391541,40.663059,42.337879,36.718566,37.661926,39.964266,39.975420,38.322684,Tsd. MJ,Berlin
12,12,Brandenburg,3.088019e+07,3.306067e+07,2.911481e+07,4.038347e+07,3.359762e+07,3.341006e+07,30220403.0,3.299168e+07,...,18.015449,17.599828,17.045271,17.311244,17.795214,17.953348,18.808469,35.691672,Tsd. MJ,Brandenburg
13,13,Mecklenburg-Vorpommern,6.890377e+06,6.903438e+06,6.617945e+06,6.525760e+06,6.577080e+06,6.589558e+06,6419580.0,7.462858e+06,...,38.858756,37.661437,38.901700,39.721800,39.163014,40.255761,40.868755,42.230654,Tsd. MJ,Mecklenburg-Vorpommern
14,14,Sachsen,3.595346e+07,3.833151e+07,3.850557e+07,3.971019e+07,4.020010e+07,3.963566e+07,34836018.0,3.934794e+07,...,31.567689,30.462903,32.978222,31.580185,30.920005,31.110080,35.626629,29.455292,Tsd. MJ,Sachsen
15,15,Sachsen-Anhalt,8.229662e+07,8.591186e+07,8.929265e+07,9.156509e+07,9.647984e+07,9.391787e+07,89101497.0,9.625267e+07,...,49.014396,48.528791,46.951925,48.313781,48.122991,49.135721,49.233924,48.529817,Tsd. MJ,Sachsen-Anhalt
16,16,Thüringen,1.673571e+07,1.729094e+07,1.817021e+07,1.879666e+07,1.926179e+07,1.889586e+07,16734081.0,1.999074e+07,...,38.918515,39.342194,38.830176,38.957748,40.304031,39.443248,39.203790,39.096760,Tsd. MJ,Thüringen

In [355]:
blcolumn_list = [x for x in enr_filter.columns if '_2020' in x if '_Anteil_' not in x]
blcolumn_list.extend(['AGS','Name',
 'Bundesland'])
blcolumn_list

['energy_industry_consumption_Erdgas_2020',
 'energy_industry_consumption_Erneuerbare Energien_2020',
 'energy_industry_consumption_Heizöl_2020',
 'energy_industry_consumption_Kohle_2020',
 'energy_industry_consumption_Sonstige Energieträger_2020',
 'energy_industry_consumption_Strom_2020',
 'energy_industry_consumption_Wärme_2020',
 'energy_industry_consumption_insgesamt_2020',
 'AGS',
 'Name',
 'Bundesland']

In [356]:
blenr_energien = blenr_filter[blcolumn_list].copy()
blenr_energien['Insgesamt'] = blenr_energien['energy_industry_consumption_insgesamt_2020']
blenr_energien['Erneuerbare'] = blenr_energien[ 'energy_industry_consumption_Erneuerbare Energien_2020']
blenr_energien['Fossil'] = blenr_energien[['energy_industry_consumption_Heizöl_2020','energy_industry_consumption_Kohle_2020']].sum(axis=1)
blenr_energien['Andere'] = blenr_energien[['energy_industry_consumption_Sonstige Energieträger_2020','energy_industry_consumption_Strom_2020','energy_industry_consumption_Wärme_2020']].sum(axis=1)
blenr_energien['Geheim'] = blenr_energien['energy_industry_consumption_insgesamt_2020']-blenr_energien[['Fossil','Andere','Erneuerbare']].sum(axis=1)
blenr_energien['Erneuerbare_Anteil'] = blenr_energien['Erneuerbare']*100/blenr_energien['Insgesamt']
blenr_energien['Fossil_Anteil'] = blenr_energien['Fossil']*100/blenr_energien['Insgesamt']
blenr_energien['Andere_Anteil'] = blenr_energien['Andere']*100/blenr_energien['Insgesamt']
blenr_energien['Geheim_Anteil'] = blenr_energien['Geheim']*100/blenr_energien['Insgesamt']
blenr_energien['Geheim_Anteil'].fillna('100',inplace=True)
blenr_energien =  blenr_energien[['AGS', 'Name','Bundesland','Erneuerbare_Anteil','Fossil_Anteil','Andere_Anteil','Geheim_Anteil','Insgesamt']]

dl_energien = blenr_energien.loc[0]
blenr_energien = blenr_energien[blenr_energien['AGS']>0]

blenr_energien.sort_values('Erneuerbare_Anteil',ascending=False,inplace=True)
blenr_energien

,AGS,Name,Bundesland,Erneuerbare_Anteil,Fossil_Anteil,Andere_Anteil,Geheim_Anteil,Insgesamt
13,13,Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,19.402524,4.435924,38.366818,37.794734,2.273968e+07
16,16,Thüringen,Thüringen,18.109447,5.166604,42.793793,33.930156,6.223697e+07
12,12,Brandenburg,Brandenburg,10.237775,18.196733,54.070553,17.494939,1.853040e+08
8,8,Baden-Württemberg,Baden-Württemberg,8.903675,5.661642,55.085986,30.348697,2.703744e+08
15,15,Sachsen-Anhalt,Sachsen-Anhalt,7.963333,9.980885,23.227930,58.827853,2.618106e+08
6,6,Hessen,Hessen,4.369994,5.297397,48.587189,41.745420,1.189712e+08
14,14,Sachsen,Sachsen,3.625151,2.877107,66.919557,26.578185,1.589058e+08
3,3,Niedersachsen,Niedersachsen,1.913769,0.718475,25.043390,72.324366,3.757796e+08
5,5,Nordrhein-Westfalen,Nordrhein-Westfalen,1.757968,26.890968,48.163761,23.187303,1.263838e+09
7,7,Rheinland-Pfalz,Rheinland-Pfalz,1.641835,1.528496,44.458579,52.371090,3.036483e+08
10,10,Saarland,Saarland,0.530663,50.033834,36.615167,12.820336,1.059797e+08
2,2,Hamburg,Hamburg,0.033292,0.000000,31.086575,68.880132,6.892881e+07
1,1,Schleswig-Holstein,Schleswig-Holstein,NaN,2.135283,18.202897,79.661820,8.464664e+07
4,4,Bremen,Bremen,NaN,0.193507,10.484845,89.321648,7.806551e+07
9,9,Bayern,Bayern,NaN,5.430847,35.479654,59.089499,3.749460e+08
11,11,Berlin,Berlin,NaN,0.000000,55.952654,44.047346,1.093438e+07

In [357]:
blenr_energien['rank'] = ""
blenr_energien['third'] = ""
blenr_energien

,AGS,Name,Bundesland,Erneuerbare_Anteil,Fossil_Anteil,Andere_Anteil,Geheim_Anteil,Insgesamt,rank,third
13,13,Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,19.402524,4.435924,38.366818,37.794734,2.273968e+07,,
16,16,Thüringen,Thüringen,18.109447,5.166604,42.793793,33.930156,6.223697e+07,,
12,12,Brandenburg,Brandenburg,10.237775,18.196733,54.070553,17.494939,1.853040e+08,,
8,8,Baden-Württemberg,Baden-Württemberg,8.903675,5.661642,55.085986,30.348697,2.703744e+08,,
15,15,Sachsen-Anhalt,Sachsen-Anhalt,7.963333,9.980885,23.227930,58.827853,2.618106e+08,,
6,6,Hessen,Hessen,4.369994,5.297397,48.587189,41.745420,1.189712e+08,,
14,14,Sachsen,Sachsen,3.625151,2.877107,66.919557,26.578185,1.589058e+08,,
3,3,Niedersachsen,Niedersachsen,1.913769,0.718475,25.043390,72.324366,3.757796e+08,,
5,5,Nordrhein-Westfalen,Nordrhein-Westfalen,1.757968,26.890968,48.163761,23.187303,1.263838e+09,,
7,7,Rheinland-Pfalz,Rheinland-Pfalz,1.641835,1.528496,44.458579,52.371090,3.036483e+08,,
10,10,Saarland,Saarland,0.530663,50.033834,36.615167,12.820336,1.059797e+08,,
2,2,Hamburg,Hamburg,0.033292,0.000000,31.086575,68.880132,6.892881e+07,,
1,1,Schleswig-Holstein,Schleswig-Holstein,NaN,2.135283,18.202897,79.661820,8.464664e+07,,
4,4,Bremen,Bremen,NaN,0.193507,10.484845,89.321648,7.806551e+07,,
9,9,Bayern,Bayern,NaN,5.430847,35.479654,59.089499,3.749460e+08,,
11,11,Berlin,Berlin,NaN,0.000000,55.952654,44.047346,1.093438e+07,,

In [358]:
blenr_merged = blenr_energien.merge(blen_short,on='Bundesland',how='left')
blenr_merged

,AGS,Name,Bundesland,Erneuerbare_Anteil,Fossil_Anteil,Andere_Anteil,Geheim_Anteil,Insgesamt,rank,third,energy_Anteil_Erneuerbar_Bundesland
0,13,Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,19.402524,4.435924,38.366818,37.794734,2.273968e+07,,,41.470171
1,16,Thüringen,Thüringen,18.109447,5.166604,42.793793,33.930156,6.223697e+07,,,23.429499
2,12,Brandenburg,Brandenburg,10.237775,18.196733,54.070553,17.494939,1.853040e+08,,,20.836697
3,8,Baden-Württemberg,Baden-Württemberg,8.903675,5.661642,55.085986,30.348697,2.703744e+08,,,14.170586
4,15,Sachsen-Anhalt,Sachsen-Anhalt,7.963333,9.980885,23.227930,58.827853,2.618106e+08,,,19.124589
5,6,Hessen,Hessen,4.369994,5.297397,48.587189,41.745420,1.189712e+08,,,11.013179
6,14,Sachsen,Sachsen,3.625151,2.877107,66.919557,26.578185,1.589058e+08,,,9.977345
7,3,Niedersachsen,Niedersachsen,1.913769,0.718475,25.043390,72.324366,3.757796e+08,,,22.507307
8,5,Nordrhein-Westfalen,Nordrhein-Westfalen,1.757968,26.890968,48.163761,23.187303,1.263838e+09,,,5.823425
9,7,Rheinland-Pfalz,Rheinland-Pfalz,1.641835,1.528496,44.458579,52.371090,3.036483e+08,,,14.531998
10,10,Saarland,Saarland,0.530663,50.033834,36.615167,12.820336,1.059797e+08,,,4.069594
11,2,Hamburg,Hamburg,0.033292,0.000000,31.086575,68.880132,6.892881e+07,,,5.639384
12,1,Schleswig-Holstein,Schleswig-Holstein,NaN,2.135283,18.202897,79.661820,8.464664e+07,,,29.882406
13,4,Bremen,Bremen,NaN,0.193507,10.484845,89.321648,7.806551e+07,,,7.684384
14,9,Bayern,Bayern,NaN,5.430847,35.479654,59.089499,3.749460e+08,,,20.126032
15,11,Berlin,Berlin,NaN,0.000000,55.952654,44.047346,1.093438e+07,,,6.109197

In [359]:
#load bundesland data and merge und bundesland name
dlen_df = pd.read_csv("data/final_data_deutschland_energy_primaryconsumption.csv")
dlen_short = dlen_df[['Name','energy_primaryconsumption_Anteil Erneuerbar_2020']].copy()
dlen_short.columns=['Name','energy_Anteil_Erneuerbar_Bundesland']
dlen_short

          Name  energy_Anteil_Erneuerbar_Bundesland
0  Deutschland                            16.576821

In [362]:
dl_energien['rank'] = ""
dl_energien['third'] = ""
dl_energien['energy_Anteil_Erneuerbar_Bundesland'] = dlen_short['energy_Anteil_Erneuerbar_Bundesland'][0]
dl_energien

AGS                                               0
Name                                    Deutschland
Bundesland                              Deutschland
Erneuerbare_Anteil                         4.099327
Fossil_Anteil                             17.211819
Andere_Anteil                             47.499251
Geheim_Anteil                             31.189602
Insgesamt                              3747109390.0
rank
third
energy_Anteil_Erneuerbar_Bundesland       16.576821
Name: 0, dtype: object

In [363]:
blenr_merged=blenr_merged.append(dl_energien)
blenr_merged

,AGS,Name,Bundesland,Erneuerbare_Anteil,Fossil_Anteil,Andere_Anteil,Geheim_Anteil,Insgesamt,rank,third,energy_Anteil_Erneuerbar_Bundesland
0,13,Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,19.402524,4.435924,38.366818,37.794734,2.273968e+07,,,41.470171
1,16,Thüringen,Thüringen,18.109447,5.166604,42.793793,33.930156,6.223697e+07,,,23.429499
2,12,Brandenburg,Brandenburg,10.237775,18.196733,54.070553,17.494939,1.853040e+08,,,20.836697
3,8,Baden-Württemberg,Baden-Württemberg,8.903675,5.661642,55.085986,30.348697,2.703744e+08,,,14.170586
4,15,Sachsen-Anhalt,Sachsen-Anhalt,7.963333,9.980885,23.227930,58.827853,2.618106e+08,,,19.124589
5,6,Hessen,Hessen,4.369994,5.297397,48.587189,41.745420,1.189712e+08,,,11.013179
6,14,Sachsen,Sachsen,3.625151,2.877107,66.919557,26.578185,1.589058e+08,,,9.977345
7,3,Niedersachsen,Niedersachsen,1.913769,0.718475,25.043390,72.324366,3.757796e+08,,,22.507307
8,5,Nordrhein-Westfalen,Nordrhein-Westfalen,1.757968,26.890968,48.163761,23.187303,1.263838e+09,,,5.823425
9,7,Rheinland-Pfalz,Rheinland-Pfalz,1.641835,1.528496,44.458579,52.371090,3.036483e+08,,,14.531998
10,10,Saarland,Saarland,0.530663,50.033834,36.615167,12.820336,1.059797e+08,,,4.069594
11,2,Hamburg,Hamburg,0.033292,0.000000,31.086575,68.880132,6.892881e+07,,,5.639384
12,1,Schleswig-Holstein,Schleswig-Holstein,NaN,2.135283,18.202897,79.661820,8.464664e+07,,,29.882406
13,4,Bremen,Bremen,NaN,0.193507,10.484845,89.321648,7.806551e+07,,,7.684384
14,9,Bayern,Bayern,NaN,5.430847,35.479654,59.089499,3.749460e+08,,,20.126032
15,11,Berlin,Berlin,NaN,0.000000,55.952654,44.047346,1.093438e+07,,,6.109197
0,0,Deutschland,Deutschland,4.099327,17.211819,47.499251,31.189602,3.747109e+09,,,16.576821

In [365]:
blenr_final = blenr_merged.copy()
blenr_final.columns=['AGS', 'Name','Bundesland','energy_Erneuerbare_Anteil','energy_Fossil_Anteil','energy_Andere_Anteil','energy_Geheim_Anteil','energy_Insgesamt', 'energy_rank','energy_third','energy_Anteil_Erneuerbar_Bundesland']
blenr_final

,AGS,Name,Bundesland,energy_Erneuerbare_Anteil,energy_Fossil_Anteil,energy_Andere_Anteil,energy_Geheim_Anteil,energy_Insgesamt,energy_rank,energy_third,energy_Anteil_Erneuerbar_Bundesland
0,13,Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,19.402524,4.435924,38.366818,37.794734,2.273968e+07,,,41.470171
1,16,Thüringen,Thüringen,18.109447,5.166604,42.793793,33.930156,6.223697e+07,,,23.429499
2,12,Brandenburg,Brandenburg,10.237775,18.196733,54.070553,17.494939,1.853040e+08,,,20.836697
3,8,Baden-Württemberg,Baden-Württemberg,8.903675,5.661642,55.085986,30.348697,2.703744e+08,,,14.170586
4,15,Sachsen-Anhalt,Sachsen-Anhalt,7.963333,9.980885,23.227930,58.827853,2.618106e+08,,,19.124589
5,6,Hessen,Hessen,4.369994,5.297397,48.587189,41.745420,1.189712e+08,,,11.013179
6,14,Sachsen,Sachsen,3.625151,2.877107,66.919557,26.578185,1.589058e+08,,,9.977345
7,3,Niedersachsen,Niedersachsen,1.913769,0.718475,25.043390,72.324366,3.757796e+08,,,22.507307
8,5,Nordrhein-Westfalen,Nordrhein-Westfalen,1.757968,26.890968,48.163761,23.187303,1.263838e+09,,,5.823425
9,7,Rheinland-Pfalz,Rheinland-Pfalz,1.641835,1.528496,44.458579,52.371090,3.036483e+08,,,14.531998
10,10,Saarland,Saarland,0.530663,50.033834,36.615167,12.820336,1.059797e+08,,,4.069594
11,2,Hamburg,Hamburg,0.033292,0.000000,31.086575,68.880132,6.892881e+07,,,5.639384
12,1,Schleswig-Holstein,Schleswig-Holstein,NaN,2.135283,18.202897,79.661820,8.464664e+07,,,29.882406
13,4,Bremen,Bremen,NaN,0.193507,10.484845,89.321648,7.806551e+07,,,7.684384
14,9,Bayern,Bayern,NaN,5.430847,35.479654,59.089499,3.749460e+08,,,20.126032
15,11,Berlin,Berlin,NaN,0.000000,55.952654,44.047346,1.093438e+07,,,6.109197
0,0,Deutschland,Deutschland,4.099327,17.211819,47.499251,31.189602,3.747109e+09,,,16.576821

## 3. Merge both datasets and sort by AGS

In [366]:
complete_df = pd.concat([blenr_final,enr_merged], ignore_index=True).copy()
final_df = complete_df.sort_values('AGS').reset_index(drop=True)
final_df

,AGS,Name,Bundesland,energy_Erneuerbare_Anteil,energy_Fossil_Anteil,energy_Andere_Anteil,energy_Geheim_Anteil,energy_Insgesamt,energy_rank,energy_third,energy_Anteil_Erneuerbar_Bundesland
0,0,Deutschland,Deutschland,4.099327,17.211819,47.499251,31.189602,3.747109e+09,,,16.576821
1,1,Schleswig-Holstein,Schleswig-Holstein,NaN,2.135283,18.202897,79.66182,8.464664e+07,,,29.882406
2,2,Hamburg,Hamburg,0.033292,0.000000,31.086575,68.880132,6.892881e+07,,,5.639384
3,3,Niedersachsen,Niedersachsen,1.913769,0.718475,25.043390,72.324366,3.757796e+08,,,22.507307
4,4,Bremen,Bremen,NaN,0.193507,10.484845,89.321648,7.806551e+07,,,7.684384
...,...,...,...,...,...,...,...,...,...,...,...
411,16073,Saalfeld-Rudolstadt,Thüringen,NaN,0.375819,69.222563,30.401618,6.902784e+06,,,23.429499
412,16074,Saale-Holzland-Kreis,Thüringen,NaN,2.547900,43.401248,54.050852,1.353703e+06,,,23.429499
413,16075,Saale-Orla-Kreis,Thüringen,NaN,0.381048,15.394034,84.224918,1.246615e+07,,,23.429499
414,16076,Greiz,Thüringen,NaN,1.167292,28.477055,70.355653,2.254106e+06,,,23.429499
415,16077,Altenburger Land,Thüringen,0.000000,3.076786,58.877127,38.046087,9.667880e+05,,,23.429499

In [367]:
#save dataframe to file
final_df.to_csv("data/final_postcard_data_energy.csv")