In [2]:
### Download heating time series data for Germany and Bundesländer
### from wohngebaeude.info and compile into one csv with Regions as rows
### and years as columns.

In [3]:
# Data URL https://www.wohngebaeude.info/daten/#/heizen/bundesweit;main=allgemein;sub=entwicklung
# set Witterungsbereinigung to "mit"
# download separate .csv sheets for each Bundesland and for Germany

In [4]:
# import necessary libraries

import pandas as pd
import numpy as np

In [5]:
#list of regions

regions = {"Deutschland":0,
           "Baden-Württemberg":8,
           "Bayern":9,"Berlin":11,
           "Brandenburg":12,
           "Bremen":4,
           "Hamburg":2,
           "Hessen":6,
           "Mecklenburg-Vorpommern":13,
           "Niedersachsen":3,
           "Nordrhein-Westfalen":5,
           "Rheinland-Pfalz":7,"Saarland":10,"Sachsen":14,"Sachsen-Anhalt":15,"Schleswig-Holstein":1,"Thüringen":16}

regions

{'Deutschland': 0,
 'Baden-Württemberg': 8,
 'Bayern': 9,
 'Berlin': 11,
 'Brandenburg': 12,
 'Bremen': 4,
 'Hamburg': 2,
 'Hessen': 6,
 'Mecklenburg-Vorpommern': 13,
 'Niedersachsen': 3,
 'Nordrhein-Westfalen': 5,
 'Rheinland-Pfalz': 7,
 'Saarland': 10,
 'Sachsen': 14,
 'Sachsen-Anhalt': 15,
 'Schleswig-Holstein': 1,
 'Thüringen': 16}

In [6]:
#iterate over data files

all_df = pd.DataFrame()
all_df['Jahr'] = np.arange(2002,2021,1)

for region in regions.keys():
    #create file path for each region
    if region == "Deutschland":
        land = "bundesweit"
    else:
        land = region.lower().replace('ü' , 'ue')
    path = "data/co2online/gebaeudedaten-heizenergieverbrauch_allgemein_entwicklung-" + land + ".csv"

    #read data and create temporary dataframe
    temp = pd.read_csv(path,delimiter=",")
    
    #rename default column label to region
    temp.rename(columns={'barlabel.gesamt':region},inplace=True)
    
    #append to all_df
    all_df[region]=temp[region]

all_df

,Jahr,Deutschland,Baden-Württemberg,Bayern,Berlin,Brandenburg,Bremen,Hamburg,Hessen,Mecklenburg-Vorpommern,Niedersachsen,Nordrhein-Westfalen,Rheinland-Pfalz,Saarland,Sachsen,Sachsen-Anhalt,Schleswig-Holstein,Thüringen
0,2002,150.84,149.45,145.76,152.23,145.56,154.03,171.08,154.04,152.01,155.90,154.65,146.97,158.81,141.72,142.97,165.51,136.75
1,2003,147.75,142.22,142.64,152.86,142.85,158.62,172.84,150.37,139.60,151.88,154.18,148.05,156.72,138.53,143.14,156.88,140.35
2,2004,144.36,142.87,139.65,142.21,141.79,143.47,167.16,148.17,135.89,149.14,148.50,141.18,149.17,136.60,143.53,149.41,137.10
3,2005,141.83,138.66,134.47,140.50,139.46,142.46,166.80,146.22,134.72,146.14,148.56,141.17,149.64,135.55,140.52,147.44,131.87
4,2006,138.50,134.60,129.84,140.33,136.20,147.58,160.50,143.02,135.09,143.25,143.87,138.48,148.60,132.34,139.07,145.95,131.82
5,2007,137.12,135.45,130.52,134.83,133.83,142.61,154.84,141.59,136.70,139.79,141.19,136.65,146.20,129.59,140.56,141.06,133.44
6,2008,133.07,129.77,126.67,134.76,134.30,136.08,147.19,136.65,135.88,135.56,135.65,132.24,139.44,130.90,136.04,136.96,133.23
7,2009,130.25,128.68,124.48,134.46,129.37,129.94,146.12,133.59,126.27,133.80,133.63,130.44,138.14,125.60,131.26,132.27,123.80
8,2010,120.29,117.88,114.63,124.98,123.18,123.98,134.56,121.92,119.29,122.35,124.28,119.12,127.84,115.61,123.09,124.63,114.18
9,2011,131.91,129.67,125.30,140.03,135.34,130.84,149.35,133.70,129.63,133.97,135.54,132.43,141.44,128.50,134.09,135.78,126.02
10,2012,126.31,123.18,120.67,133.01,128.12,125.87,144.41,128.33,121.10,129.20,130.28,124.90,133.30,122.55,130.65,129.10,121.79
11,2013,120.58,117.01,115.00,128.47,125.71,125.52,137.16,123.13,121.71,123.67,121.87,117.64,124.19,119.00,125.44,125.67,117.01
12,2014,128.40,127.35,122.46,126.99,130.97,138.66,144.55,129.51,122.75,130.47,130.11,128.87,139.91,126.10,134.36,132.16,123.27
13,2015,124.33,123.57,120.84,125.51,122.45,126.98,141.68,128.05,125.13,126.19,123.72,122.35,128.96,122.48,128.91,127.02,122.79
14,2016,122.86,120.85,117.92,120.40,124.81,125.40,133.57,126.16,122.50,125.74,123.79,121.66,126.58,122.91,125.76,126.54,119.16
15,2017,121.85,118.41,115.94,122.48,124.41,127.31,132.67,122.36,122.89,125.82,124.33,121.75,129.00,119.80,123.39,125.30,121.96
16,2018,126.64,126.25,124.46,123.52,128.60,127.90,138.91,127.95,126.02,126.65,126.78,126.72,137.71,125.93,126.91,127.29,124.80
17,2019,124.51,121.60,119.96,124.52,127.88,125.78,138.14,124.72,130.94,126.71,125.72,123.13,135.62,123.83,128.01,126.00,124.69
18,2020,128.34,126.83,122.61,125.42,144.32,124.85,141.22,128.03,125.07,130.12,130.29,129.72,142.87,122.10,131.93,129.76,124.52

In [11]:
#transpose dataframe and rename columns
trans_df = all_df.set_index('Jahr').transpose()
new_columns = ["heating_"+x for x in trans_df.columns.astype(str)]
trans_df.columns = new_columns

#add AGS ids from the regions dictionary using the region names
trans_df['AGS']=trans_df.index.map(regions)

#set AGS as index and copy region names to first column
first_column=trans_df.index
trans_df.set_index('AGS', inplace=True)
trans_df.insert(0,'Name',first_column)

#sort the dataframe by AGS id
trans_df.sort_index(inplace=True)

trans_df

,Name,heating_2002,heating_2003,heating_2004,heating_2005,heating_2006,heating_2007,heating_2008,heating_2009,heating_2010,heating_2011,heating_2012,heating_2013,heating_2014,heating_2015,heating_2016,heating_2017,heating_2018,heating_2019,heating_2020
AGS,,,,,,,,,,,,,,,,,,,,
0,Deutschland,150.84,147.75,144.36,141.83,138.50,137.12,133.07,130.25,120.29,131.91,126.31,120.58,128.40,124.33,122.86,121.85,126.64,124.51,128.34
1,Schleswig-Holstein,165.51,156.88,149.41,147.44,145.95,141.06,136.96,132.27,124.63,135.78,129.10,125.67,132.16,127.02,126.54,125.30,127.29,126.00,129.76
2,Hamburg,171.08,172.84,167.16,166.80,160.50,154.84,147.19,146.12,134.56,149.35,144.41,137.16,144.55,141.68,133.57,132.67,138.91,138.14,141.22
3,Niedersachsen,155.90,151.88,149.14,146.14,143.25,139.79,135.56,133.80,122.35,133.97,129.20,123.67,130.47,126.19,125.74,125.82,126.65,126.71,130.12
4,Bremen,154.03,158.62,143.47,142.46,147.58,142.61,136.08,129.94,123.98,130.84,125.87,125.52,138.66,126.98,125.40,127.31,127.90,125.78,124.85
5,Nordrhein-Westfalen,154.65,154.18,148.50,148.56,143.87,141.19,135.65,133.63,124.28,135.54,130.28,121.87,130.11,123.72,123.79,124.33,126.78,125.72,130.29
6,Hessen,154.04,150.37,148.17,146.22,143.02,141.59,136.65,133.59,121.92,133.70,128.33,123.13,129.51,128.05,126.16,122.36,127.95,124.72,128.03
7,Rheinland-Pfalz,146.97,148.05,141.18,141.17,138.48,136.65,132.24,130.44,119.12,132.43,124.90,117.64,128.87,122.35,121.66,121.75,126.72,123.13,129.72
8,Baden-Württemberg,149.45,142.22,142.87,138.66,134.60,135.45,129.77,128.68,117.88,129.67,123.18,117.01,127.35,123.57,120.85,118.41,126.25,121.60,126.83
9,Bayern,145.76,142.64,139.65,134.47,129.84,130.52,126.67,124.48,114.63,125.30,120.67,115.00,122.46,120.84,117.92,115.94,124.46,119.96,122.61
10,Saarland,158.81,156.72,149.17,149.64,148.60,146.20,139.44,138.14,127.84,141.44,133.30,124.19,139.91,128.96,126.58,129.00,137.71,135.62,142.87
11,Berlin,152.23,152.86,142.21,140.50,140.33,134.83,134.76,134.46,124.98,140.03,133.01,128.47,126.99,125.51,120.40,122.48,123.52,124.52,125.42
12,Brandenburg,145.56,142.85,141.79,139.46,136.20,133.83,134.30,129.37,123.18,135.34,128.12,125.71,130.97,122.45,124.81,124.41,128.60,127.88,144.32
13,Mecklenburg-Vorpommern,152.01,139.60,135.89,134.72,135.09,136.70,135.88,126.27,119.29,129.63,121.10,121.71,122.75,125.13,122.50,122.89,126.02,130.94,125.07
14,Sachsen,141.72,138.53,136.60,135.55,132.34,129.59,130.90,125.60,115.61,128.50,122.55,119.00,126.10,122.48,122.91,119.80,125.93,123.83,122.10
15,Sachsen-Anhalt,142.97,143.14,143.53,140.52,139.07,140.56,136.04,131.26,123.09,134.09,130.65,125.44,134.36,128.91,125.76,123.39,126.91,128.01,131.93
16,Thüringen,136.75,140.35,137.10,131.87,131.82,133.44,133.23,123.80,114.18,126.02,121.79,117.01,123.27,122.79,119.16,121.96,124.80,124.69,124.52

In [13]:
#save dataframe to file
trans_df.to_csv("data/final_data_bundesland_heating.csv")