In [493]:
#pull data from all the ranking csvs
#generate the five postcard texts and save to file

In [494]:
#import necessary libraries
import pandas as pd

In [495]:
#import gerics landkreis data and standardize columns
gerics_landkreis = pd.read_csv('other/gerics/gerics_original_data/final_gerics_rcp45_2036_2065_heisze_tage_median.csv')
gerics_landkreis.drop(columns=['Unnamed: 0'],inplace=True)
gerics_landkreis.columns=['AGS', 'Name', 'Bundesland', '1971-2000','2036-2065', 'percentage change']
gerics_landkreis =  gerics_landkreis[(gerics_landkreis['AGS'] != 11000) & (gerics_landkreis['AGS'] != 2000)]
gerics_landkreis

,AGS,Name,Bundesland,1971-2000,2036-2065,percentage change
0,5124,Wuppertal,Nordrhein-Westfalen,4.0,6.3,57.500000
1,16073,Saalfeld-Rudolstadt,Thüringen,2.9,5.0,72.413793
2,16072,Sonneberg,Thüringen,1.7,2.9,70.588235
3,16071,Weimarer Land,Thüringen,5.1,8.1,58.823529
4,16070,Ilm-Kreis,Thüringen,2.3,4.3,86.956522
...,...,...,...,...,...,...
396,5116,Mönchengladbach,Nordrhein-Westfalen,6.1,9.8,60.655738
397,5562,Recklinghausen,Nordrhein-Westfalen,5.8,9.1,56.896552
398,7338,Rhein-Pfalz-Kreis,Rheinland-Pfalz,9.0,16.4,82.222222
399,5162,Rhein-Kreis Neuss,Nordrhein-Westfalen,6.8,10.5,54.411765
400,5166,Viersen,Nordrhein-Westfalen,6.1,10.0,63.934426

In [496]:
#import gerics bundesland data and standardize columns
gerics_bundesland = pd.read_csv('other/gerics/gerics_original_data/final_gerics_rcp45_2036_2065_heisze_tage_median_de_bundesland.csv')
gerics_bundesland.drop(columns=['Unnamed: 0','Median','Postcard Intro'],inplace=True)
gerics_bundesland['Bundesland'] = gerics_bundesland['Name']
gerics_bundesland

,AGS,Name,1971-2000,2036-2065,percentage change,Bundesland
0,0,Deutschland,4.4,7.4,68.181818,Deutschland
1,1,Schleswig-Holstein,2.0,3.0,50.000000,Schleswig-Holstein
2,2,Hamburg,3.7,5.7,54.054054,Hamburg
3,3,Niedersachsen,3.9,5.9,51.282051,Niedersachsen
4,4,Bremen,3.8,5.8,52.631579,Bremen
5,5,Nordrhein-Westfalen,4.4,6.4,45.454545,Nordrhein-Westfalen
6,6,Hessen,4.3,7.3,69.767442,Hessen
7,7,Rheinland-Pfalz,5.0,9.0,80.000000,Rheinland-Pfalz
8,8,Baden-Württemberg,4.3,9.3,116.279070,Baden-Württemberg
9,9,Bayern,4.0,9.0,125.000000,Bayern
10,10,Saarland,4.7,8.7,85.106383,Saarland
11,11,Berlin,8.0,12.0,50.000000,Berlin
12,12,Brandenburg,6.9,10.9,57.971014,Brandenburg
13,13,Mecklenburg-Vorpommern,2.7,3.7,37.037037,Mecklenburg-Vorpommern
14,14,Sachsen,5.3,9.3,75.471698,Sachsen
15,15,Sachsen-Anhalt,6.6,10.6,60.606061,Sachsen-Anhalt
16,16,Thüringen,3.6,6.6,83.333333,Thüringen

In [497]:
#merge both datasets into one dataframe
gerics_df = gerics_landkreis.append(gerics_bundesland).sort_values('AGS').copy()
gerics_df

,AGS,Name,Bundesland,1971-2000,2036-2065,percentage change
0,0,Deutschland,Deutschland,4.4,7.4,68.181818
1,1,Schleswig-Holstein,Schleswig-Holstein,2.0,3.0,50.000000
2,2,Hamburg,Hamburg,3.7,5.7,54.054054
3,3,Niedersachsen,Niedersachsen,3.9,5.9,51.282051
4,4,Bremen,Bremen,3.8,5.8,52.631579
...,...,...,...,...,...,...
1,16073,Saalfeld-Rudolstadt,Thüringen,2.9,5.0,72.413793
8,16074,Saale-Holzland-Kreis,Thüringen,5.3,8.7,64.150943
7,16075,Saale-Orla-Kreis,Thüringen,2.8,4.8,71.428571
6,16076,Greiz,Thüringen,4.2,7.2,71.428571
5,16077,Altenburger Land,Thüringen,5.9,10.2,72.881356

In [498]:
#create base dataframe for postcard texts
postcards_df = gerics_df[['AGS','Name']].copy()
postcards_df['gerics_text'] = gerics_df.agg(lambda x: f'''Hallo!\n\nIch schicke dir Grüße aus dem schönen <span className='location-name'>{x['Name']}</span>. Derzeit wird es hier an durchschnittlich <span className="gerics-data">{str(round(x['1971-2000'],1)).replace(".", ",")} Tagen</span> im Jahr über 30 Grad, aber wenn wir so weitermachen, könnten es Mitte des Jahrhunderts schon <span className="gerics-data">{str(round(x['2036-2065'],1)).replace(".", ",")}</span> sein. <span className="gerics-data">{round(x['percentage change'])} Prozent mehr!</span>\n\n''',
                                            axis=1)
postcards_df

,AGS,Name,gerics_text
0,0,Deutschland,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
1,1,Schleswig-Holstein,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
2,2,Hamburg,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
3,3,Niedersachsen,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
4,4,Bremen,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
...,...,...,...
1,16073,Saalfeld-Rudolstadt,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
8,16074,Saale-Holzland-Kreis,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
7,16075,Saale-Orla-Kreis,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
6,16076,Greiz,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
5,16077,Altenburger Land,Hallo!\n\nIch schicke dir Grüße aus dem schöne...

## Energy

In [499]:
#load energy data and create postcard texts
#add to postcards_df

In [500]:
energy_df = pd.read_csv("energy/data/final_postcard_data_energy.csv")
energy_df.drop(columns=['Unnamed: 0'],inplace=True)
energy_df

,AGS,Name,Bundesland,energy_Erneuerbare_Anteil,energy_Fossil_Anteil,energy_Andere_Anteil,energy_Geheim_Anteil,energy_Insgesamt,energy_Anteil_Erneuerbar_Bundesland,energy_rank,energy_third
0,0,Deutschland,Deutschland,4.099327,17.211819,47.499251,31.189602,3.747109e+09,16.576821,NaN,NaN
1,1,Schleswig-Holstein,Schleswig-Holstein,NaN,2.135283,18.202897,79.661820,8.464664e+07,29.882406,2.0,oberen Drittel
2,2,Hamburg,Hamburg,0.033292,0.000000,31.086575,68.880132,6.892881e+07,5.639384,15.0,unteren Drittel
3,3,Niedersachsen,Niedersachsen,1.913769,0.718475,25.043390,72.324366,3.757796e+08,22.507307,4.0,oberen Drittel
4,4,Bremen,Bremen,NaN,0.193507,10.484845,89.321648,7.806551e+07,7.684384,12.0,unteren Drittel
...,...,...,...,...,...,...,...,...,...,...,...
411,16073,Saalfeld-Rudolstadt,Thüringen,NaN,0.375819,69.222563,30.401618,6.902784e+06,23.429499,3.0,oberen Drittel
412,16074,Saale-Holzland-Kreis,Thüringen,NaN,2.547900,43.401248,54.050852,1.353703e+06,23.429499,3.0,oberen Drittel
413,16075,Saale-Orla-Kreis,Thüringen,NaN,0.381048,15.394034,84.224918,1.246615e+07,23.429499,3.0,oberen Drittel
414,16076,Greiz,Thüringen,NaN,1.167292,28.477055,70.355653,2.254106e+06,23.429499,3.0,oberen Drittel
415,16077,Altenburger Land,Thüringen,0.000000,3.076786,58.877127,38.046087,9.667880e+05,23.429499,3.0,oberen Drittel

In [501]:
en_deutschland = energy_df.iloc[0].copy()
en_deutschland

AGS                                               0
Name                                    Deutschland
Bundesland                              Deutschland
energy_Erneuerbare_Anteil                  4.099327
energy_Fossil_Anteil                      17.211819
energy_Andere_Anteil                      47.499251
energy_Geheim_Anteil                      31.189602
energy_Insgesamt                       3747109390.0
energy_Anteil_Erneuerbar_Bundesland       16.576821
energy_rank                                     NaN
energy_third                                    NaN
Name: 0, dtype: object

In [502]:
#write energy deutschland postcard text
en_deutschland['energy_postcard'] = f"Wir könnten etwas dagegen tun, zum Beispiel bei der Energieerzeugung. In <span className='location-name'>Deutschland</span> kommen etwa <span className='energy-data'>{round(energy_df['energy_Fossil_Anteil'][0])} Prozent</span> der von der Industrie genutzten Primärenergie aus fossilen Quellen. <span className='energy-data'>{round(energy_df['energy_Geheim_Anteil'][0])} Prozent</span> sind unbekannt oder geheimgehalten, um Rückschlüsse auf einzelne Firmen zu verhindern.\n\nIn Deutschland insgesamt waren zuletzt <span className='energy-data'>{round(energy_df['energy_Anteil_Erneuerbar_Bundesland'][0])} Prozent</span> der genutzten Primärenergie aus erneuerbaren Quellen.\n\nUm die Erderhitzung zu stoppen, muss unser gesamter Energiebedarf durch erneuerbare Quellen gedeckt werden. Schaffen wir das?\n\nViele Grüße!"
en_deutschland

AGS                                                                                    0
Name                                                                         Deutschland
Bundesland                                                                   Deutschland
energy_Erneuerbare_Anteil                                                       4.099327
energy_Fossil_Anteil                                                           17.211819
energy_Andere_Anteil                                                           47.499251
energy_Geheim_Anteil                                                           31.189602
energy_Insgesamt                                                            3747109390.0
energy_Anteil_Erneuerbar_Bundesland                                            16.576821
energy_rank                                                                          NaN
energy_third                                                                         NaN
energy_postcard                        Wir könnten etwas dagegen tun, zum Beispiel be...
Name: 0, dtype: object

In [503]:
en_bundesland = energy_df.iloc[1:17].copy()
en_bundesland

,AGS,Name,Bundesland,energy_Erneuerbare_Anteil,energy_Fossil_Anteil,energy_Andere_Anteil,energy_Geheim_Anteil,energy_Insgesamt,energy_Anteil_Erneuerbar_Bundesland,energy_rank,energy_third
1,1,Schleswig-Holstein,Schleswig-Holstein,NaN,2.135283,18.202897,79.661820,8.464664e+07,29.882406,2.0,oberen Drittel
2,2,Hamburg,Hamburg,0.033292,0.000000,31.086575,68.880132,6.892881e+07,5.639384,15.0,unteren Drittel
3,3,Niedersachsen,Niedersachsen,1.913769,0.718475,25.043390,72.324366,3.757796e+08,22.507307,4.0,oberen Drittel
4,4,Bremen,Bremen,NaN,0.193507,10.484845,89.321648,7.806551e+07,7.684384,12.0,unteren Drittel
5,5,Nordrhein-Westfalen,Nordrhein-Westfalen,1.757968,26.890968,48.163761,23.187303,1.263838e+09,5.823425,14.0,unteren Drittel
6,6,Hessen,Hessen,4.369994,5.297397,48.587189,41.745420,1.189712e+08,11.013179,10.0,mittleren Drittel
7,7,Rheinland-Pfalz,Rheinland-Pfalz,1.641835,1.528496,44.458579,52.371090,3.036483e+08,14.531998,8.0,mittleren Drittel
8,8,Baden-Württemberg,Baden-Württemberg,8.903675,5.661642,55.085986,30.348697,2.703744e+08,14.170586,9.0,mittleren Drittel
9,9,Bayern,Bayern,NaN,5.430847,35.479654,59.089499,3.749460e+08,20.126032,6.0,mittleren Drittel
10,10,Saarland,Saarland,0.530663,50.033834,36.615167,12.820336,1.059797e+08,4.069594,16.0,unteren Drittel
11,11,Berlin,Berlin,NaN,0.000000,55.952654,44.047346,1.093438e+07,6.109197,13.0,unteren Drittel
12,12,Brandenburg,Brandenburg,10.237775,18.196733,54.070553,17.494939,1.853040e+08,20.836697,5.0,oberen Drittel
13,13,Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,19.402524,4.435924,38.366818,37.794734,2.273968e+07,41.470171,1.0,oberen Drittel
14,14,Sachsen,Sachsen,3.625151,2.877107,66.919557,26.578185,1.589058e+08,9.977345,11.0,mittleren Drittel
15,15,Sachsen-Anhalt,Sachsen-Anhalt,7.963333,9.980885,23.227930,58.827853,2.618106e+08,19.124589,7.0,mittleren Drittel
16,16,Thüringen,Thüringen,18.109447,5.166604,42.793793,33.930156,6.223697e+07,23.429499,3.0,oberen Drittel

In [504]:
#write energy bundesland postcard text
en_bundesland['energy_postcard'] = en_bundesland.agg(lambda x: f'''Wir könnten etwas dagegen tun, zum Beispiel bei der Energieerzeugung. In <span className="location-name">{x['Name']}</span> kommen etwa <span className='energy-data-fossil'>{round(x['energy_Fossil_Anteil'])} Prozent</span> der von der Industrie genutzten Primärenergie aus fossilen Quellen. <span className='energy-data-geheim'>{round(x['energy_Geheim_Anteil'])} Prozent</span> sind unbekannt oder geheimgehalten, um Rückschlüsse auf einzelne Firmen zu verhindern.\n\nIm Bundesland <span className="location-name">{x['Bundesland']}</span> waren zuletzt <span className='energy-data-renewables'>{round(x['energy_Anteil_Erneuerbar_Bundesland'])} Prozent</span> der genutzten Primärenergie aus erneuerbaren Quellen. Damit ist das Bundesland im Vergleich im <span className='{x['energy_third']}'>{x['energy_third']}</span>.\n\nUm die Erderhitzung zu stoppen, muss unser gesamter Energiebedarf durch erneuerbare Quellen gedeckt werden. Schaffen wir das?\n\nViele Grüße!''', axis =1)
en_bundesland

,AGS,Name,Bundesland,energy_Erneuerbare_Anteil,energy_Fossil_Anteil,energy_Andere_Anteil,energy_Geheim_Anteil,energy_Insgesamt,energy_Anteil_Erneuerbar_Bundesland,energy_rank,energy_third,energy_postcard
1,1,Schleswig-Holstein,Schleswig-Holstein,NaN,2.135283,18.202897,79.661820,8.464664e+07,29.882406,2.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
2,2,Hamburg,Hamburg,0.033292,0.000000,31.086575,68.880132,6.892881e+07,5.639384,15.0,unteren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
3,3,Niedersachsen,Niedersachsen,1.913769,0.718475,25.043390,72.324366,3.757796e+08,22.507307,4.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
4,4,Bremen,Bremen,NaN,0.193507,10.484845,89.321648,7.806551e+07,7.684384,12.0,unteren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
5,5,Nordrhein-Westfalen,Nordrhein-Westfalen,1.757968,26.890968,48.163761,23.187303,1.263838e+09,5.823425,14.0,unteren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
6,6,Hessen,Hessen,4.369994,5.297397,48.587189,41.745420,1.189712e+08,11.013179,10.0,mittleren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
7,7,Rheinland-Pfalz,Rheinland-Pfalz,1.641835,1.528496,44.458579,52.371090,3.036483e+08,14.531998,8.0,mittleren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
8,8,Baden-Württemberg,Baden-Württemberg,8.903675,5.661642,55.085986,30.348697,2.703744e+08,14.170586,9.0,mittleren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
9,9,Bayern,Bayern,NaN,5.430847,35.479654,59.089499,3.749460e+08,20.126032,6.0,mittleren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
10,10,Saarland,Saarland,0.530663,50.033834,36.615167,12.820336,1.059797e+08,4.069594,16.0,unteren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
11,11,Berlin,Berlin,NaN,0.000000,55.952654,44.047346,1.093438e+07,6.109197,13.0,unteren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
12,12,Brandenburg,Brandenburg,10.237775,18.196733,54.070553,17.494939,1.853040e+08,20.836697,5.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
13,13,Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,19.402524,4.435924,38.366818,37.794734,2.273968e+07,41.470171,1.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
14,14,Sachsen,Sachsen,3.625151,2.877107,66.919557,26.578185,1.589058e+08,9.977345,11.0,mittleren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
15,15,Sachsen-Anhalt,Sachsen-Anhalt,7.963333,9.980885,23.227930,58.827853,2.618106e+08,19.124589,7.0,mittleren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
16,16,Thüringen,Thüringen,18.109447,5.166604,42.793793,33.930156,6.223697e+07,23.429499,3.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."

In [505]:
en_landkreis = energy_df.iloc[17:].copy()
en_landkreis

,AGS,Name,Bundesland,energy_Erneuerbare_Anteil,energy_Fossil_Anteil,energy_Andere_Anteil,energy_Geheim_Anteil,energy_Insgesamt,energy_Anteil_Erneuerbar_Bundesland,energy_rank,energy_third
17,1001,Flensburg,Schleswig-Holstein,0.0,1.513574,40.475246,58.011180,968172.0,29.882406,2.0,oberen Drittel
18,1002,Kiel,Schleswig-Holstein,NaN,NaN,NaN,100.000000,NaN,29.882406,2.0,oberen Drittel
19,1003,Lübeck,Schleswig-Holstein,0.0,2.307045,43.439537,54.253418,1639023.0,29.882406,2.0,oberen Drittel
20,1004,Neumünster,Schleswig-Holstein,NaN,0.329570,40.470015,59.200415,1209152.0,29.882406,2.0,oberen Drittel
21,1051,Dithmarschen,Schleswig-Holstein,NaN,0.000000,16.514060,83.485940,26326694.0,29.882406,2.0,oberen Drittel
...,...,...,...,...,...,...,...,...,...,...,...
411,16073,Saalfeld-Rudolstadt,Thüringen,NaN,0.375819,69.222563,30.401618,6902784.0,23.429499,3.0,oberen Drittel
412,16074,Saale-Holzland-Kreis,Thüringen,NaN,2.547900,43.401248,54.050852,1353703.0,23.429499,3.0,oberen Drittel
413,16075,Saale-Orla-Kreis,Thüringen,NaN,0.381048,15.394034,84.224918,12466154.0,23.429499,3.0,oberen Drittel
414,16076,Greiz,Thüringen,NaN,1.167292,28.477055,70.355653,2254106.0,23.429499,3.0,oberen Drittel
415,16077,Altenburger Land,Thüringen,0.0,3.076786,58.877127,38.046087,966788.0,23.429499,3.0,oberen Drittel

In [506]:
#write energy bundesland postcard text
en_landkreis['energy_postcard'] = en_landkreis.agg(lambda x: f'''Wir könnten etwas dagegen tun, zum Beispiel bei der Energieerzeugung. In <span className="location-name">{x['Name']}</span> kommen etwa <span className='energy-data-fossil'>{round(x['energy_Fossil_Anteil'])} Prozent</span> der von der Industrie genutzten Primärenergie aus fossilen Quellen. <span className='energy-data-geheim'>{round(x['energy_Geheim_Anteil'])} Prozent</span> sind unbekannt oder geheimgehalten, um Rückschlüsse auf einzelne Firmen zu verhindern.\n\nIm Bundesland <span className="location-name">{x['Bundesland']}</span> waren zuletzt <span className='energy-data-renewables'>{round(x['energy_Anteil_Erneuerbar_Bundesland'])} Prozent</span> der genutzten Primärenergie aus erneuerbaren Quellen. Damit ist das Bundesland im Vergleich im <span className='{x['energy_third']}'>{x['energy_third']}</span>.\n\nUm die Erderhitzung zu stoppen, muss unser gesamter Energiebedarf durch erneuerbare Quellen gedeckt werden. Schaffen wir das?\n\nViele Grüße!''' if pd.isna(x['energy_Fossil_Anteil']) is False
                                                   else f'''<span>{round(x['energy_Geheim_Anteil'])} Prozent</span> des Primärenergievebrauchs der Industrie im Landkreis sind unbekannt oder geheimgehalten, um Rückschlüsse auf einzelne Firmen zu verhindern.\n\nIm Bundesland <span className="location-name">{x['Bundesland']}</span> waren zuletzt <span>{round(x['energy_Anteil_Erneuerbar_Bundesland'])}</span> Prozent der genutzten Primärenergie aus erneuerbaren Quellen. Damit ist das Bundesland im Vergleich im <span className='{x['energy_third']}'>{x['energy_third']}</span>.\n\nUm die Erderhitzung zu stoppen, muss unser gesamter Energiebedarf durch erneuerbare Quellen gedeckt werden. Schaffen wir das?\n\nViele Grüße!''', axis =1)
en_landkreis

,AGS,Name,Bundesland,energy_Erneuerbare_Anteil,energy_Fossil_Anteil,energy_Andere_Anteil,energy_Geheim_Anteil,energy_Insgesamt,energy_Anteil_Erneuerbar_Bundesland,energy_rank,energy_third,energy_postcard
17,1001,Flensburg,Schleswig-Holstein,0.0,1.513574,40.475246,58.011180,968172.0,29.882406,2.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
18,1002,Kiel,Schleswig-Holstein,NaN,NaN,NaN,100.000000,NaN,29.882406,2.0,oberen Drittel,<span>100 Prozent</span> des Primärenergievebr...
19,1003,Lübeck,Schleswig-Holstein,0.0,2.307045,43.439537,54.253418,1639023.0,29.882406,2.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
20,1004,Neumünster,Schleswig-Holstein,NaN,0.329570,40.470015,59.200415,1209152.0,29.882406,2.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
21,1051,Dithmarschen,Schleswig-Holstein,NaN,0.000000,16.514060,83.485940,26326694.0,29.882406,2.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
...,...,...,...,...,...,...,...,...,...,...,...,...
411,16073,Saalfeld-Rudolstadt,Thüringen,NaN,0.375819,69.222563,30.401618,6902784.0,23.429499,3.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
412,16074,Saale-Holzland-Kreis,Thüringen,NaN,2.547900,43.401248,54.050852,1353703.0,23.429499,3.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
413,16075,Saale-Orla-Kreis,Thüringen,NaN,0.381048,15.394034,84.224918,12466154.0,23.429499,3.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
414,16076,Greiz,Thüringen,NaN,1.167292,28.477055,70.355653,2254106.0,23.429499,3.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."
415,16077,Altenburger Land,Thüringen,0.0,3.076786,58.877127,38.046087,966788.0,23.429499,3.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel be..."

In [507]:
#merge all levels together
en_postcards = en_landkreis[['AGS','energy_third','energy_postcard']]
en_postcards =en_postcards.append(en_bundesland[['AGS','energy_third','energy_postcard']])
en_postcards =en_postcards.append(en_deutschland[['AGS','energy_third','energy_postcard']])
en_postcards

     AGS       energy_third                                    energy_postcard
17  1001     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
18  1002     oberen Drittel  <span>100 Prozent</span> des Primärenergievebr...
19  1003     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
20  1004     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
21  1051     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
..   ...                ...                                                ...
13    13     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
14    14  mittleren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
15    15  mittleren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
16    16     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
0      0                NaN  Wir könnten etwas dagegen tun, zum Beispiel be...

[416 rows x 3 columns]

In [508]:
#merge energy postcards into base dataframe
postcards_df=postcards_df.merge(en_postcards, on='AGS',how='left')
postcards_df['energy_postcard'] = postcards_df['gerics_text']+postcards_df['energy_postcard']
postcards_df

,AGS,Name,gerics_text,energy_third,energy_postcard
0,0,Deutschland,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,NaN,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
1,1,Schleswig-Holstein,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
2,2,Hamburg,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
3,3,Niedersachsen,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
4,4,Bremen,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
...,...,...,...,...,...
411,16073,Saalfeld-Rudolstadt,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
412,16074,Saale-Holzland-Kreis,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
413,16075,Saale-Orla-Kreis,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
414,16076,Greiz,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
415,16077,Altenburger Land,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...

## Mobilität

In [509]:
mobility_df = pd.read_csv("mobility/data/final_postcard_data_mobility.csv")
mobility_df

,Unnamed: 0,AGS,Name,Bundesland,mobility_car_density,mobility_ev_hybrid,mobility_rank,mobility_third,mobility_pc_km_umweltfreundlich_2002,mobility_pc_km_umweltfreundlich_2017
0,0,0,Deutschland,Deutschland,58.301444,1.913849,0,NaN,17.920187,22.634244
1,1,1,Schleswig-Holstein,Schleswig-Holstein,58.964615,1.632304,10,mittleren Drittel,16.211493,23.762643
2,2,2,Hamburg,Hamburg,43.858711,2.044732,2,oberen Drittel,32.606087,38.240482
3,3,3,Niedersachsen,Niedersachsen,61.080990,1.795172,12,unteren Drittel,17.783738,21.924874
4,4,4,Bremen,Bremen,44.325558,1.549235,3,oberen Drittel,24.970653,30.888652
...,...,...,...,...,...,...,...,...,...,...
411,411,16073,Saalfeld-Rudolstadt,Thüringen,60.199665,1.207301,139,mittleren Drittel,15.502949,16.071021
412,412,16074,Saale-Holzland-Kreis,Thüringen,60.388060,1.462800,144,mittleren Drittel,15.502949,16.071021
413,413,16075,Saale-Orla-Kreis,Thüringen,64.259142,0.978110,246,mittleren Drittel,15.502949,16.071021
414,414,16076,Greiz,Thüringen,62.805145,1.197686,205,mittleren Drittel,15.502949,16.071021
415,415,16077,Altenburger Land,Thüringen,58.747025,1.012448,118,oberen Drittel,15.502949,16.071021

In [510]:
mo_deutschland = mobility_df.iloc[0].copy()
mo_deutschland

Unnamed: 0                                        0
AGS                                               0
Name                                    Deutschland
Bundesland                              Deutschland
mobility_car_density                      58.301444
mobility_ev_hybrid                         1.913849
mobility_rank                                     0
mobility_third                                  NaN
mobility_pc_km_umweltfreundlich_2002      17.920187
mobility_pc_km_umweltfreundlich_2017      22.634244
Name: 0, dtype: object

In [511]:
#write energy deutschland postcard text
mo_deutschland['mobility_postcard'] = f"Wir könnten etwas dagegen tun, zum Beispiel bei der Mobilität. In <span className='location-name'>Deutschland</span> kommen <span className='autos'>{round(mo_deutschland['mobility_car_density'])} Autos</span> auf 100 Menschen, davon haben <span className='hybrid'>{round(mo_deutschland['mobility_ev_hybrid'])} einen Elektro- oder Hybridantrieb</span>.\n\nIm Jahr 2017 wurden etwa <span className='mo-km-umweltfreundlich'>{str(round(mo_deutschland['mobility_pc_km_umweltfreundlich_2017'],1)).replace('.', ',')} Prozent</span> der gefahrenen Kilometer zu Fuß, mit dem Fahrrad oder dem ÖPNV zurückgelegt. 2002 waren es <span className='mo-km-umweltfreundlich'>{str(round(mo_deutschland['mobility_pc_km_umweltfreundlich_2002'],1)).replace('.', ',')} Prozent</span>.\n\nUm die Erderhitzung zu stoppen, muss der Verkehr emissionsfrei werden. Schaffen wir das?\n\nViele Grüße!"
mo_deutschland

Unnamed: 0                                                                              0
AGS                                                                                     0
Name                                                                          Deutschland
Bundesland                                                                    Deutschland
mobility_car_density                                                            58.301444
mobility_ev_hybrid                                                               1.913849
mobility_rank                                                                           0
mobility_third                                                                        NaN
mobility_pc_km_umweltfreundlich_2002                                            17.920187
mobility_pc_km_umweltfreundlich_2017                                            22.634244
mobility_postcard                       Wir könnten etwas dagegen tun, zum Beispiel be...
Name: 0, dtype: object

In [512]:
mo_bundesland = mobility_df.iloc[1:17].copy()
mo_bundesland

,Unnamed: 0,AGS,Name,Bundesland,mobility_car_density,mobility_ev_hybrid,mobility_rank,mobility_third,mobility_pc_km_umweltfreundlich_2002,mobility_pc_km_umweltfreundlich_2017
1,1,1,Schleswig-Holstein,Schleswig-Holstein,58.964615,1.632304,10,mittleren Drittel,16.211493,23.762643
2,2,2,Hamburg,Hamburg,43.858711,2.044732,2,oberen Drittel,32.606087,38.240482
3,3,3,Niedersachsen,Niedersachsen,61.080990,1.795172,12,unteren Drittel,17.783738,21.924874
4,4,4,Bremen,Bremen,44.325558,1.549235,3,oberen Drittel,24.970653,30.888652
5,5,5,Nordrhein-Westfalen,Nordrhein-Westfalen,58.172809,1.925751,9,mittleren Drittel,16.532446,21.401121
6,6,6,Hessen,Hessen,60.317137,2.203028,11,mittleren Drittel,19.563925,21.518747
7,7,7,Rheinland-Pfalz,Rheinland-Pfalz,63.331073,1.702721,15,unteren Drittel,14.824904,18.740223
8,8,8,Baden-Württemberg,Baden-Württemberg,61.616868,2.346161,13,unteren Drittel,20.482881,24.084543
9,9,9,Bayern,Bayern,62.397950,2.278905,14,unteren Drittel,17.898873,22.598620
10,10,10,Saarland,Saarland,66.164027,1.843949,16,unteren Drittel,14.543507,12.816284
11,11,11,Berlin,Berlin,33.820978,1.573227,1,oberen Drittel,32.870550,40.793596
12,12,12,Brandenburg,Brandenburg,57.624746,1.448145,8,mittleren Drittel,18.394902,21.336106
13,13,13,Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,54.552000,1.091636,5,oberen Drittel,11.567771,15.785969
14,14,14,Sachsen,Sachsen,54.061165,1.292703,4,oberen Drittel,14.347751,16.751224
15,15,15,Sachsen-Anhalt,Sachsen-Anhalt,56.530935,1.161644,6,mittleren Drittel,12.794277,15.191167
16,16,16,Thüringen,Thüringen,56.884350,1.337925,7,mittleren Drittel,15.502949,16.071021

In [513]:
#write mobility bundesland postcard text
mo_bundesland['mobility_postcard'] = mo_bundesland.agg(lambda x: f'''Wir könnten etwas dagegen tun, zum Beispiel bei der Mobilität. In <span className='location-name'>{x['Name']}</span> kommen <span className='autos'>{round(x['mobility_car_density'])} Autos</span> auf 100 Menschen, davon haben <span className='hybrid'>{round(x['mobility_ev_hybrid'])} einen Elektro- oder Hybridantrieb</span>. Damit liegt das Bundesland im Vergleich im <span className='{x['mobility_third']}'>{x['mobility_third']}</span>.\n\nIm Jahr 2017 wurden etwa <span className='mo-km-umweltfreundlich'>{str(round(x['mobility_pc_km_umweltfreundlich_2017'],1)).replace(".", ",")} Prozent</span> der gefahrenen Kilometer zu Fuß, mit dem Fahrrad oder dem ÖPNV zurückgelegt. 2002 waren es <span className='mo-km-umweltfreundlich'>{str(round(x['mobility_pc_km_umweltfreundlich_2002'],1)).replace(".", ",")} Prozent</span>.\n\nUm die Erderhitzung zu stoppen, muss der Verkehr emissionsfrei werden. Schaffen wir das?\n\nViele Grüße!'''
                                                     , axis =1)
mo_bundesland

,Unnamed: 0,AGS,Name,Bundesland,mobility_car_density,mobility_ev_hybrid,mobility_rank,mobility_third,mobility_pc_km_umweltfreundlich_2002,mobility_pc_km_umweltfreundlich_2017,mobility_postcard
1,1,1,Schleswig-Holstein,Schleswig-Holstein,58.964615,1.632304,10,mittleren Drittel,16.211493,23.762643,"Wir könnten etwas dagegen tun, zum Beispiel be..."
2,2,2,Hamburg,Hamburg,43.858711,2.044732,2,oberen Drittel,32.606087,38.240482,"Wir könnten etwas dagegen tun, zum Beispiel be..."
3,3,3,Niedersachsen,Niedersachsen,61.080990,1.795172,12,unteren Drittel,17.783738,21.924874,"Wir könnten etwas dagegen tun, zum Beispiel be..."
4,4,4,Bremen,Bremen,44.325558,1.549235,3,oberen Drittel,24.970653,30.888652,"Wir könnten etwas dagegen tun, zum Beispiel be..."
5,5,5,Nordrhein-Westfalen,Nordrhein-Westfalen,58.172809,1.925751,9,mittleren Drittel,16.532446,21.401121,"Wir könnten etwas dagegen tun, zum Beispiel be..."
6,6,6,Hessen,Hessen,60.317137,2.203028,11,mittleren Drittel,19.563925,21.518747,"Wir könnten etwas dagegen tun, zum Beispiel be..."
7,7,7,Rheinland-Pfalz,Rheinland-Pfalz,63.331073,1.702721,15,unteren Drittel,14.824904,18.740223,"Wir könnten etwas dagegen tun, zum Beispiel be..."
8,8,8,Baden-Württemberg,Baden-Württemberg,61.616868,2.346161,13,unteren Drittel,20.482881,24.084543,"Wir könnten etwas dagegen tun, zum Beispiel be..."
9,9,9,Bayern,Bayern,62.397950,2.278905,14,unteren Drittel,17.898873,22.598620,"Wir könnten etwas dagegen tun, zum Beispiel be..."
10,10,10,Saarland,Saarland,66.164027,1.843949,16,unteren Drittel,14.543507,12.816284,"Wir könnten etwas dagegen tun, zum Beispiel be..."
11,11,11,Berlin,Berlin,33.820978,1.573227,1,oberen Drittel,32.870550,40.793596,"Wir könnten etwas dagegen tun, zum Beispiel be..."
12,12,12,Brandenburg,Brandenburg,57.624746,1.448145,8,mittleren Drittel,18.394902,21.336106,"Wir könnten etwas dagegen tun, zum Beispiel be..."
13,13,13,Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,54.552000,1.091636,5,oberen Drittel,11.567771,15.785969,"Wir könnten etwas dagegen tun, zum Beispiel be..."
14,14,14,Sachsen,Sachsen,54.061165,1.292703,4,oberen Drittel,14.347751,16.751224,"Wir könnten etwas dagegen tun, zum Beispiel be..."
15,15,15,Sachsen-Anhalt,Sachsen-Anhalt,56.530935,1.161644,6,mittleren Drittel,12.794277,15.191167,"Wir könnten etwas dagegen tun, zum Beispiel be..."
16,16,16,Thüringen,Thüringen,56.884350,1.337925,7,mittleren Drittel,15.502949,16.071021,"Wir könnten etwas dagegen tun, zum Beispiel be..."

In [514]:
mo_landkreis = mobility_df.iloc[17:].copy()
mo_landkreis

,Unnamed: 0,AGS,Name,Bundesland,mobility_car_density,mobility_ev_hybrid,mobility_rank,mobility_third,mobility_pc_km_umweltfreundlich_2002,mobility_pc_km_umweltfreundlich_2017
17,17,1001,Flensburg,Schleswig-Holstein,49.712994,1.608991,33,oberen Drittel,16.211493,23.762643
18,18,1002,Kiel,Schleswig-Holstein,45.831963,1.546440,12,oberen Drittel,16.211493,23.762643
19,19,1003,Lübeck,Schleswig-Holstein,47.042913,1.440745,22,oberen Drittel,16.211493,23.762643
20,20,1004,Neumünster,Schleswig-Holstein,54.656838,1.786253,71,oberen Drittel,16.211493,23.762643
21,21,1051,Dithmarschen,Schleswig-Holstein,62.247983,1.217446,191,mittleren Drittel,16.211493,23.762643
...,...,...,...,...,...,...,...,...,...,...
411,411,16073,Saalfeld-Rudolstadt,Thüringen,60.199665,1.207301,139,mittleren Drittel,15.502949,16.071021
412,412,16074,Saale-Holzland-Kreis,Thüringen,60.388060,1.462800,144,mittleren Drittel,15.502949,16.071021
413,413,16075,Saale-Orla-Kreis,Thüringen,64.259142,0.978110,246,mittleren Drittel,15.502949,16.071021
414,414,16076,Greiz,Thüringen,62.805145,1.197686,205,mittleren Drittel,15.502949,16.071021
415,415,16077,Altenburger Land,Thüringen,58.747025,1.012448,118,oberen Drittel,15.502949,16.071021

In [515]:
#write mobility landkreis postcard text
mo_landkreis['mobility_postcard'] = mo_landkreis.agg(lambda x: f'''Wir könnten etwas dagegen tun, zum Beispiel bei der Mobilität. In <span className='location-name'>{x['Name']}</span> kommen <span className='autos'>{round(x['mobility_car_density'])} Autos</span> auf 100 Menschen, davon haben <span className='hybrid'>{round(x['mobility_ev_hybrid'])} einen Elektro- oder Hybridantrieb</span>. Damit liegt der Kreis im Vergleich im <span className='{x['mobility_third']}'>{x['mobility_third']}</span>.\n\nIm Jahr 2017 wurden in <span className='location-name'>{x['Bundesland']}</span> etwa <span className='mo-km-umweltfreundlich'>{round(x['mobility_pc_km_umweltfreundlich_2017'],1)} Prozent</span> der gefahrenen Kilometer zu Fuß, mit Fahrrad oder ÖPNV zurückgelegt. 2002 waren es <span className='mo-km-umweltfreundlich'>{round(x['mobility_pc_km_umweltfreundlich_2002'],1)} Prozent</span>.\n\nUm die Erderhitzung zu stoppen, muss der Verkehr emissionsfrei werden. Schaffen wir das?\n\nViele Grüße!'''
                                                     , axis =1)
mo_landkreis

,Unnamed: 0,AGS,Name,Bundesland,mobility_car_density,mobility_ev_hybrid,mobility_rank,mobility_third,mobility_pc_km_umweltfreundlich_2002,mobility_pc_km_umweltfreundlich_2017,mobility_postcard
17,17,1001,Flensburg,Schleswig-Holstein,49.712994,1.608991,33,oberen Drittel,16.211493,23.762643,"Wir könnten etwas dagegen tun, zum Beispiel be..."
18,18,1002,Kiel,Schleswig-Holstein,45.831963,1.546440,12,oberen Drittel,16.211493,23.762643,"Wir könnten etwas dagegen tun, zum Beispiel be..."
19,19,1003,Lübeck,Schleswig-Holstein,47.042913,1.440745,22,oberen Drittel,16.211493,23.762643,"Wir könnten etwas dagegen tun, zum Beispiel be..."
20,20,1004,Neumünster,Schleswig-Holstein,54.656838,1.786253,71,oberen Drittel,16.211493,23.762643,"Wir könnten etwas dagegen tun, zum Beispiel be..."
21,21,1051,Dithmarschen,Schleswig-Holstein,62.247983,1.217446,191,mittleren Drittel,16.211493,23.762643,"Wir könnten etwas dagegen tun, zum Beispiel be..."
...,...,...,...,...,...,...,...,...,...,...,...
411,411,16073,Saalfeld-Rudolstadt,Thüringen,60.199665,1.207301,139,mittleren Drittel,15.502949,16.071021,"Wir könnten etwas dagegen tun, zum Beispiel be..."
412,412,16074,Saale-Holzland-Kreis,Thüringen,60.388060,1.462800,144,mittleren Drittel,15.502949,16.071021,"Wir könnten etwas dagegen tun, zum Beispiel be..."
413,413,16075,Saale-Orla-Kreis,Thüringen,64.259142,0.978110,246,mittleren Drittel,15.502949,16.071021,"Wir könnten etwas dagegen tun, zum Beispiel be..."
414,414,16076,Greiz,Thüringen,62.805145,1.197686,205,mittleren Drittel,15.502949,16.071021,"Wir könnten etwas dagegen tun, zum Beispiel be..."
415,415,16077,Altenburger Land,Thüringen,58.747025,1.012448,118,oberen Drittel,15.502949,16.071021,"Wir könnten etwas dagegen tun, zum Beispiel be..."

In [516]:
#merge all levels together
mo_postcards = mo_landkreis[['AGS','mobility_third','mobility_postcard']]
mo_postcards = mo_postcards.append(mo_bundesland[['AGS','mobility_third','mobility_postcard']])
mo_postcards = mo_postcards.append(mo_deutschland[['AGS','mobility_third','mobility_postcard']])
mo_postcards

     AGS     mobility_third                                  mobility_postcard
17  1001     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
18  1002     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
19  1003     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
20  1004     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
21  1051  mittleren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
..   ...                ...                                                ...
13    13     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
14    14     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
15    15  mittleren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
16    16  mittleren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
0      0                NaN  Wir könnten etwas dagegen tun, zum Beispiel be...

[416 rows x 3 columns]

In [517]:
#merge energy postcards into base dataframe
postcards_df=postcards_df.merge(mo_postcards, on='AGS',how='left')
postcards_df['mobility_postcard'] = postcards_df['gerics_text']+postcards_df['mobility_postcard']
postcards_df

,AGS,Name,gerics_text,energy_third,energy_postcard,mobility_third,mobility_postcard
0,0,Deutschland,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,NaN,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,NaN,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
1,1,Schleswig-Holstein,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
2,2,Hamburg,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
3,3,Niedersachsen,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
4,4,Bremen,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
...,...,...,...,...,...,...,...
411,16073,Saalfeld-Rudolstadt,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
412,16074,Saale-Holzland-Kreis,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
413,16075,Saale-Orla-Kreis,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
414,16076,Greiz,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
415,16077,Altenburger Land,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...

## Landwirtschaft

In [518]:
agri_df = pd.read_csv("agriculture/data/final_postcard_data_agriculture.csv")
agri_df

,Unnamed: 0,AGS,Name,Bundesland,Landwirtschaft_Flaeche,Tierzahl_GV,GV_pro_Flaeche,agriculture_rank,agriculture_third,Anteil_unter_2GV_pro_Hektar,Anteil_oekolandbau
0,0,0,Deutschland,Deutschland,16595024.0,12016049.0,0.724075,0.0,NaN,64.254956,6.489779
1,1,1,Schleswig-Holstein,Schleswig-Holstein,982753.0,941807.0,0.958335,14.0,unteren Drittel,64.588817,4.032673
2,2,2,Hamburg,Hamburg,14563.0,7074.0,0.485752,7.0,mittleren Drittel,NaN,5.725191
3,3,3,Niedersachsen,Niedersachsen,2571337.0,2930734.0,1.139770,15.0,unteren Drittel,46.236984,2.084017
4,4,4,Bremen,Bremen,7923.0,7587.0,0.957592,13.0,unteren Drittel,82.153684,14.683010
...,...,...,...,...,...,...,...,...,...,...,...
411,411,16073,Saalfeld-Rudolstadt,Thüringen,33442.0,18751.0,0.560702,207.0,mittleren Drittel,78.749963,5.607522
412,412,16074,Saale-Holzland-Kreis,Thüringen,39254.0,22814.0,0.581189,219.0,mittleren Drittel,78.749963,5.607522
413,413,16075,Saale-Orla-Kreis,Thüringen,50401.0,30719.0,0.609492,228.0,mittleren Drittel,78.749963,5.607522
414,414,16076,Greiz,Thüringen,45767.0,28699.0,0.627068,232.0,mittleren Drittel,78.749963,5.607522
415,415,16077,Altenburger Land,Thüringen,36401.0,12267.0,0.336996,94.0,oberen Drittel,78.749963,5.607522

In [519]:
ag_deutschland = agri_df.iloc[0].copy()
ag_deutschland

Unnamed: 0                               0
AGS                                      0
Name                           Deutschland
Bundesland                     Deutschland
Landwirtschaft_Flaeche          16595024.0
Tierzahl_GV                     12016049.0
GV_pro_Flaeche                    0.724075
agriculture_rank                       0.0
agriculture_third                      NaN
Anteil_unter_2GV_pro_Hektar      64.254956
Anteil_oekolandbau                6.489779
Name: 0, dtype: object

In [520]:
ag_bundesland = agri_df.iloc[1:17].copy()
ag_bundesland

,Unnamed: 0,AGS,Name,Bundesland,Landwirtschaft_Flaeche,Tierzahl_GV,GV_pro_Flaeche,agriculture_rank,agriculture_third,Anteil_unter_2GV_pro_Hektar,Anteil_oekolandbau
1,1,1,Schleswig-Holstein,Schleswig-Holstein,982753.0,941807.0,0.958335,14.0,unteren Drittel,64.588817,4.032673
2,2,2,Hamburg,Hamburg,14563.0,7074.0,0.485752,7.0,mittleren Drittel,NaN,5.725191
3,3,3,Niedersachsen,Niedersachsen,2571337.0,2930734.0,1.139770,15.0,unteren Drittel,46.236984,2.084017
4,4,4,Bremen,Bremen,7923.0,7587.0,0.957592,13.0,unteren Drittel,82.153684,14.683010
5,5,5,Nordrhein-Westfalen,Nordrhein-Westfalen,1473157.0,1725424.0,1.171242,16.0,unteren Drittel,48.988712,3.312809
6,6,6,Hessen,Hessen,764705.0,411548.0,0.538179,10.0,mittleren Drittel,88.665964,15.309514
7,7,7,Rheinland-Pfalz,Rheinland-Pfalz,698763.0,306501.0,0.438634,5.0,oberen Drittel,90.142206,11.069415
8,8,8,Baden-Württemberg,Baden-Württemberg,1408063.0,942605.0,0.669434,11.0,mittleren Drittel,80.024294,10.162581
9,9,9,Bayern,Bayern,3107697.0,2608043.0,0.839220,12.0,unteren Drittel,72.622997,9.197279
10,10,10,Saarland,Saarland,74024.0,36861.0,0.497960,8.0,mittleren Drittel,95.453189,17.519872
11,11,11,Berlin,Berlin,1864.0,946.0,0.507511,9.0,mittleren Drittel,NaN,12.896406
12,12,12,Brandenburg,Brandenburg,1310361.0,488154.0,0.372534,3.0,oberen Drittel,80.929584,11.243788
13,13,13,Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,1343521.0,495566.0,0.368856,2.0,oberen Drittel,75.458365,14.061094
14,14,14,Sachsen,Sachsen,898375.0,430971.0,0.479723,6.0,mittleren Drittel,81.775572,5.441201
15,15,15,Sachsen-Anhalt,Sachsen-Anhalt,1162702.0,402474.0,0.346154,1.0,oberen Drittel,58.620681,5.149898
16,16,16,Thüringen,Thüringen,774830.0,307783.0,0.397226,4.0,oberen Drittel,78.749963,5.607522

In [521]:
ag_landkreis = agri_df.iloc[17:].copy()
ag_landkreis

,Unnamed: 0,AGS,Name,Bundesland,Landwirtschaft_Flaeche,Tierzahl_GV,GV_pro_Flaeche,agriculture_rank,agriculture_third,Anteil_unter_2GV_pro_Hektar,Anteil_oekolandbau
17,17,1001,Flensburg,Schleswig-Holstein,244.0,171.0,0.700820,255.0,mittleren Drittel,64.588817,4.032673
18,18,1002,Kiel,Schleswig-Holstein,2014.0,1553.0,0.771102,272.0,unteren Drittel,64.588817,4.032673
19,19,1003,Lübeck,Schleswig-Holstein,5386.0,2848.0,0.528778,193.0,mittleren Drittel,64.588817,4.032673
20,20,1004,Neumünster,Schleswig-Holstein,1487.0,1662.0,1.117687,331.0,unteren Drittel,64.588817,4.032673
21,21,1051,Dithmarschen,Schleswig-Holstein,100554.0,104009.0,1.034360,316.0,unteren Drittel,64.588817,4.032673
...,...,...,...,...,...,...,...,...,...,...,...
411,411,16073,Saalfeld-Rudolstadt,Thüringen,33442.0,18751.0,0.560702,207.0,mittleren Drittel,78.749963,5.607522
412,412,16074,Saale-Holzland-Kreis,Thüringen,39254.0,22814.0,0.581189,219.0,mittleren Drittel,78.749963,5.607522
413,413,16075,Saale-Orla-Kreis,Thüringen,50401.0,30719.0,0.609492,228.0,mittleren Drittel,78.749963,5.607522
414,414,16076,Greiz,Thüringen,45767.0,28699.0,0.627068,232.0,mittleren Drittel,78.749963,5.607522
415,415,16077,Altenburger Land,Thüringen,36401.0,12267.0,0.336996,94.0,oberen Drittel,78.749963,5.607522

In [522]:
#write agri deutschland postcard text
ag_deutschland['agriculture_postcard'] = f"Wir könnten etwas dagegen tun, zum Beispiel bei der Landwirtschaft. In <span className='location-name'>Deutschland</span> wurden 2020 <span className='land-data-unter'>{round(ag_deutschland['Anteil_unter_2GV_pro_Hektar'])} Prozent</span> der Tiere innerhalb der ökologischen Grenze von 2 Großvieheinheiten pro Hektar Land gehalten, <span className='land-data-oeko'>{round(ag_deutschland['Anteil_oekolandbau'])} Prozent</span> davon auf Biobauernhöfen.\n\nUm die Erderhitzung zu stoppen, müssen wir die Zahl der Tiere in der Landwirtschaft noch erheblich reduzieren. Schaffen wir das?\n\nViele Grüße!"
ag_deutschland

Unnamed: 0                                                                     0
AGS                                                                            0
Name                                                                 Deutschland
Bundesland                                                           Deutschland
Landwirtschaft_Flaeche                                                16595024.0
Tierzahl_GV                                                           12016049.0
GV_pro_Flaeche                                                          0.724075
agriculture_rank                                                             0.0
agriculture_third                                                            NaN
Anteil_unter_2GV_pro_Hektar                                            64.254956
Anteil_oekolandbau                                                      6.489779
agriculture_postcard           Wir könnten etwas dagegen tun, zum Beispiel be...
Name: 0, dtype: object

In [523]:
#write agri bundesland postcard text
ag_bundesland['agriculture_postcard'] = ag_bundesland.agg(lambda x: f'''Wir könnten etwas dagegen tun, zum Beispiel bei der Landwirtschaft. In <span className='location-name'>{x['Name']}</span> gibt es <span className='land-data-tierzahl'>{'{:,}'.format(round(x['Tierzahl_GV'])).replace(',', '.')} Großvieheinheiten</span>. Eine Großvieheinheit entspricht entspricht 500 kg also in etwa einem Rind, 8 Schweinen, 10 Schafen oder 640 Legehennen. Bezogen auf die landwirtschaftlich genutzte Fläche liegt das Bundesland damit im Vergleich im <span className='{x['agriculture_third']}'>{x['agriculture_third']}</span>.\n\nIn <span className='location-name'>{x['Bundesland']}</span> wurden 2020 <span className='land-data-unter'>{round(x['Anteil_unter_2GV_pro_Hektar'])}</span> Prozent der Tiere innerhalb der ökologischen Grenze von 2 Großvieheinheiten pro Hektar Land gehalten, <span className='land-data-oeko'>{round(x['Anteil_oekolandbau'])}</span> davon auf Biobauernhöfen.\n\nUm die Erderhitzung zu stoppen, müssen wir die Zahl der Tiere in der Landwirtschaft noch erheblich reduzieren. Schaffen wir das?\n\nViele Grüße!''' if pd.isna(x['Anteil_unter_2GV_pro_Hektar']) is False
                                                   else f'''Wir könnten etwas dagegen tun, zum Beispiel im Bereich Landwirtschaft. In <span className='location-name'>{x['Name']}</span> gibt es <span className='land-data-tierzahl'>{'{:,}'.format(round(x['Tierzahl_GV'])).replace(',', '.')} Großvieheinheiten</span>. Eine Großvieheinheit entspricht entspricht 500 kg also in etwa einem Rind, 8 Schweinen, 10 Schafen oder 640 Legehennen. Bezogen auf die landwirtschaftlich genutzte Fläche liegt das Bundesland damit im Vergleich im <span className='{x['agriculture_third']}'>{x['agriculture_third']}</span>.\n\nIn <span className='location-name'>{x['Bundesland']}</span> wurden 2020 <span span className='land-data-tierzahl'>{round(x['Anteil_oekolandbau'])}</span> der Tiere auf Biobauernhöfen gehalten.\n\nUm die Erderhitzung zu stoppen, müssen wir die Zahl der Tiere in der Landwirtschaft noch erheblich reduzieren. Schaffen wir das?\n\nViele Grüße!'''
                                                     , axis =1)
ag_bundesland

,Unnamed: 0,AGS,Name,Bundesland,Landwirtschaft_Flaeche,Tierzahl_GV,GV_pro_Flaeche,agriculture_rank,agriculture_third,Anteil_unter_2GV_pro_Hektar,Anteil_oekolandbau,agriculture_postcard
1,1,1,Schleswig-Holstein,Schleswig-Holstein,982753.0,941807.0,0.958335,14.0,unteren Drittel,64.588817,4.032673,"Wir könnten etwas dagegen tun, zum Beispiel be..."
2,2,2,Hamburg,Hamburg,14563.0,7074.0,0.485752,7.0,mittleren Drittel,NaN,5.725191,"Wir könnten etwas dagegen tun, zum Beispiel im..."
3,3,3,Niedersachsen,Niedersachsen,2571337.0,2930734.0,1.139770,15.0,unteren Drittel,46.236984,2.084017,"Wir könnten etwas dagegen tun, zum Beispiel be..."
4,4,4,Bremen,Bremen,7923.0,7587.0,0.957592,13.0,unteren Drittel,82.153684,14.683010,"Wir könnten etwas dagegen tun, zum Beispiel be..."
5,5,5,Nordrhein-Westfalen,Nordrhein-Westfalen,1473157.0,1725424.0,1.171242,16.0,unteren Drittel,48.988712,3.312809,"Wir könnten etwas dagegen tun, zum Beispiel be..."
6,6,6,Hessen,Hessen,764705.0,411548.0,0.538179,10.0,mittleren Drittel,88.665964,15.309514,"Wir könnten etwas dagegen tun, zum Beispiel be..."
7,7,7,Rheinland-Pfalz,Rheinland-Pfalz,698763.0,306501.0,0.438634,5.0,oberen Drittel,90.142206,11.069415,"Wir könnten etwas dagegen tun, zum Beispiel be..."
8,8,8,Baden-Württemberg,Baden-Württemberg,1408063.0,942605.0,0.669434,11.0,mittleren Drittel,80.024294,10.162581,"Wir könnten etwas dagegen tun, zum Beispiel be..."
9,9,9,Bayern,Bayern,3107697.0,2608043.0,0.839220,12.0,unteren Drittel,72.622997,9.197279,"Wir könnten etwas dagegen tun, zum Beispiel be..."
10,10,10,Saarland,Saarland,74024.0,36861.0,0.497960,8.0,mittleren Drittel,95.453189,17.519872,"Wir könnten etwas dagegen tun, zum Beispiel be..."
11,11,11,Berlin,Berlin,1864.0,946.0,0.507511,9.0,mittleren Drittel,NaN,12.896406,"Wir könnten etwas dagegen tun, zum Beispiel im..."
12,12,12,Brandenburg,Brandenburg,1310361.0,488154.0,0.372534,3.0,oberen Drittel,80.929584,11.243788,"Wir könnten etwas dagegen tun, zum Beispiel be..."
13,13,13,Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,1343521.0,495566.0,0.368856,2.0,oberen Drittel,75.458365,14.061094,"Wir könnten etwas dagegen tun, zum Beispiel be..."
14,14,14,Sachsen,Sachsen,898375.0,430971.0,0.479723,6.0,mittleren Drittel,81.775572,5.441201,"Wir könnten etwas dagegen tun, zum Beispiel be..."
15,15,15,Sachsen-Anhalt,Sachsen-Anhalt,1162702.0,402474.0,0.346154,1.0,oberen Drittel,58.620681,5.149898,"Wir könnten etwas dagegen tun, zum Beispiel be..."
16,16,16,Thüringen,Thüringen,774830.0,307783.0,0.397226,4.0,oberen Drittel,78.749963,5.607522,"Wir könnten etwas dagegen tun, zum Beispiel be..."

In [524]:
#write agri landkreis postcard text
ag_landkreis['agri_s1'] = ag_landkreis.agg(lambda x: f"Wir könnten etwas dagegen tun, zum Beispiel bei der Landwirtschaft. In <span className='location-name'>{x['Name']}</span> gibt es <span className='land-data-tierzahl'>{'{:,}'.format(round(x['Tierzahl_GV'])).replace(',', '.')} Großvieheinheiten</span>. Eine Großvieheinheit entspricht entspricht 500 kg also in etwa einem Rind, 8 Schweinen, 10 Schafen oder 640 Legehennen. Bezogen auf die landwirtschaftlich genutzte Fläche liegt <span className='location-name'>{x['Name']}</span> dabei im Vergleich der Landkreise und Städte im <span className='{x['agriculture_third']}'>{x['agriculture_third']}</span>.\n\n" if pd.isna(x['GV_pro_Flaeche']) == False
                                           else "Für diesen Kreis ist die Zahl der Tiere unbekannt oder geheim.\n\n"
                                           , axis =1)
ag_landkreis['agri_s2'] = ag_landkreis.agg(lambda x: f"Im Bundesland <span className='location-name'>{x['Bundesland']}</span> wurden <span className='land-data-unter'>{round(x['Anteil_unter_2GV_pro_Hektar'])} Prozent</span> der Tiere innerhalb der ökologischen Grenze von 2 Großvieheinheiten pro Hektar Land gehalten, <span className='land-data-oeko'>{round(x['Anteil_oekolandbau'])}</span> davon auf Biobauernhöfen.\n\nViele Grüße!" if pd.isna(x['Anteil_unter_2GV_pro_Hektar']) is False
                                           else f"In <span className='location-name'>{x['Bundesland']}</span> wurden 2020 <span className='land-data-oeko'>{round(x['Anteil_oekolandbau'])}</span> der Tiere auf Biobauernhöfen gehalten.\n\nUm die Erderhitzung zu stoppen, müssen wir die Zahl der Tiere in der Landwirtschaft noch erheblich reduzieren. Schaffen wir das?\n\nViele Grüße!"
                                                     , axis =1)
ag_landkreis['agriculture_postcard'] = ag_landkreis['agri_s1']+ag_landkreis['agri_s2']
ag_landkreis

,Unnamed: 0,AGS,Name,Bundesland,Landwirtschaft_Flaeche,Tierzahl_GV,GV_pro_Flaeche,agriculture_rank,agriculture_third,Anteil_unter_2GV_pro_Hektar,Anteil_oekolandbau,agri_s1,agri_s2,agriculture_postcard
17,17,1001,Flensburg,Schleswig-Holstein,244.0,171.0,0.700820,255.0,mittleren Drittel,64.588817,4.032673,"Wir könnten etwas dagegen tun, zum Beispiel be...",Im Bundesland <span className='location-name'>...,"Wir könnten etwas dagegen tun, zum Beispiel be..."
18,18,1002,Kiel,Schleswig-Holstein,2014.0,1553.0,0.771102,272.0,unteren Drittel,64.588817,4.032673,"Wir könnten etwas dagegen tun, zum Beispiel be...",Im Bundesland <span className='location-name'>...,"Wir könnten etwas dagegen tun, zum Beispiel be..."
19,19,1003,Lübeck,Schleswig-Holstein,5386.0,2848.0,0.528778,193.0,mittleren Drittel,64.588817,4.032673,"Wir könnten etwas dagegen tun, zum Beispiel be...",Im Bundesland <span className='location-name'>...,"Wir könnten etwas dagegen tun, zum Beispiel be..."
20,20,1004,Neumünster,Schleswig-Holstein,1487.0,1662.0,1.117687,331.0,unteren Drittel,64.588817,4.032673,"Wir könnten etwas dagegen tun, zum Beispiel be...",Im Bundesland <span className='location-name'>...,"Wir könnten etwas dagegen tun, zum Beispiel be..."
21,21,1051,Dithmarschen,Schleswig-Holstein,100554.0,104009.0,1.034360,316.0,unteren Drittel,64.588817,4.032673,"Wir könnten etwas dagegen tun, zum Beispiel be...",Im Bundesland <span className='location-name'>...,"Wir könnten etwas dagegen tun, zum Beispiel be..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,411,16073,Saalfeld-Rudolstadt,Thüringen,33442.0,18751.0,0.560702,207.0,mittleren Drittel,78.749963,5.607522,"Wir könnten etwas dagegen tun, zum Beispiel be...",Im Bundesland <span className='location-name'>...,"Wir könnten etwas dagegen tun, zum Beispiel be..."
412,412,16074,Saale-Holzland-Kreis,Thüringen,39254.0,22814.0,0.581189,219.0,mittleren Drittel,78.749963,5.607522,"Wir könnten etwas dagegen tun, zum Beispiel be...",Im Bundesland <span className='location-name'>...,"Wir könnten etwas dagegen tun, zum Beispiel be..."
413,413,16075,Saale-Orla-Kreis,Thüringen,50401.0,30719.0,0.609492,228.0,mittleren Drittel,78.749963,5.607522,"Wir könnten etwas dagegen tun, zum Beispiel be...",Im Bundesland <span className='location-name'>...,"Wir könnten etwas dagegen tun, zum Beispiel be..."
414,414,16076,Greiz,Thüringen,45767.0,28699.0,0.627068,232.0,mittleren Drittel,78.749963,5.607522,"Wir könnten etwas dagegen tun, zum Beispiel be...",Im Bundesland <span className='location-name'>...,"Wir könnten etwas dagegen tun, zum Beispiel be..."
415,415,16077,Altenburger Land,Thüringen,36401.0,12267.0,0.336996,94.0,oberen Drittel,78.749963,5.607522,"Wir könnten etwas dagegen tun, zum Beispiel be...",Im Bundesland <span className='location-name'>...,"Wir könnten etwas dagegen tun, zum Beispiel be..."

In [525]:
#merge all levels together
ag_postcards = ag_landkreis[['AGS','agriculture_third','agriculture_postcard']]
ag_postcards = ag_postcards.append(ag_bundesland[['AGS','agriculture_third','agriculture_postcard']])
ag_postcards = ag_postcards.append(ag_deutschland[['AGS','agriculture_third','agriculture_postcard']])
ag_postcards

     AGS  agriculture_third                               agriculture_postcard
17  1001  mittleren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
18  1002    unteren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
19  1003  mittleren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
20  1004    unteren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
21  1051    unteren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
..   ...                ...                                                ...
13    13     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
14    14  mittleren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
15    15     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
16    16     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
0      0                NaN  Wir könnten etwas dagegen tun, zum Beispiel be...

[416 rows x 3 columns]

In [526]:
#merge energy postcards into base dataframe
postcards_df=postcards_df.merge(ag_postcards, on='AGS',how='left')
postcards_df['agriculture_postcard'] = postcards_df['gerics_text']+postcards_df['agriculture_postcard']
postcards_df

,AGS,Name,gerics_text,energy_third,energy_postcard,mobility_third,mobility_postcard,agriculture_third,agriculture_postcard
0,0,Deutschland,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,NaN,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,NaN,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,NaN,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
1,1,Schleswig-Holstein,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
2,2,Hamburg,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
3,3,Niedersachsen,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
4,4,Bremen,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
...,...,...,...,...,...,...,...,...,...
411,16073,Saalfeld-Rudolstadt,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
412,16074,Saale-Holzland-Kreis,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
413,16075,Saale-Orla-Kreis,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
414,16076,Greiz,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
415,16077,Altenburger Land,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...

## Buildings

In [527]:
buildings_df = pd.read_csv("buildings/data/final_postcard_data_buildings.csv")
buildings_df

,Unnamed: 0,AGS,Name,Bundesland,buildings_anteil_erneuerbare_2016,buildings_anteil_erneuerbare_2020,buildings_rank,buildings_third,buildings_heating_2002,buildings_heating_2020
0,0,0,Deutschland,Deutschland,29.271487,37.250119,0,NaN,150.84,128.34
1,1,1,Schleswig-Holstein,Schleswig-Holstein,17.315705,26.782061,11,mittleren Drittel,165.51,129.76
2,2,2,Hamburg,Hamburg,7.976157,5.865467,16,unteren Drittel,171.08,141.22
3,3,3,Niedersachsen,Niedersachsen,15.535673,20.774876,13,unteren Drittel,155.90,130.12
4,4,4,Bremen,Bremen,4.927353,6.030856,15,unteren Drittel,154.03,124.85
...,...,...,...,...,...,...,...,...,...,...
411,411,16073,Saalfeld-Rudolstadt,Thüringen,46.666667,55.376344,130,oberen Drittel,136.75,124.52
412,412,16074,Saale-Holzland-Kreis,Thüringen,47.435897,70.992366,31,oberen Drittel,136.75,124.52
413,413,16075,Saale-Orla-Kreis,Thüringen,43.103448,42.028986,225,mittleren Drittel,136.75,124.52
414,414,16076,Greiz,Thüringen,61.818182,52.702703,157,mittleren Drittel,136.75,124.52
415,415,16077,Altenburger Land,Thüringen,20.792079,24.817518,324,unteren Drittel,136.75,124.52

In [528]:
bu_deutschland = buildings_df.iloc[0].copy()
bu_deutschland

Unnamed: 0                                     0
AGS                                            0
Name                                 Deutschland
Bundesland                           Deutschland
buildings_anteil_erneuerbare_2016      29.271487
buildings_anteil_erneuerbare_2020      37.250119
buildings_rank                                 0
buildings_third                              NaN
buildings_heating_2002                    150.84
buildings_heating_2020                    128.34
Name: 0, dtype: object

In [529]:
bu_bundesland = buildings_df.iloc[1:17].copy()
bu_bundesland

,Unnamed: 0,AGS,Name,Bundesland,buildings_anteil_erneuerbare_2016,buildings_anteil_erneuerbare_2020,buildings_rank,buildings_third,buildings_heating_2002,buildings_heating_2020
1,1,1,Schleswig-Holstein,Schleswig-Holstein,17.315705,26.782061,11,mittleren Drittel,165.51,129.76
2,2,2,Hamburg,Hamburg,7.976157,5.865467,16,unteren Drittel,171.08,141.22
3,3,3,Niedersachsen,Niedersachsen,15.535673,20.774876,13,unteren Drittel,155.90,130.12
4,4,4,Bremen,Bremen,4.927353,6.030856,15,unteren Drittel,154.03,124.85
5,5,5,Nordrhein-Westfalen,Nordrhein-Westfalen,27.602738,40.593871,7,mittleren Drittel,154.65,130.29
6,6,6,Hessen,Hessen,28.710400,35.131420,8,mittleren Drittel,154.04,128.03
7,7,7,Rheinland-Pfalz,Rheinland-Pfalz,36.154753,52.370872,3,oberen Drittel,146.97,129.72
8,8,8,Baden-Württemberg,Baden-Württemberg,46.136448,55.384876,2,oberen Drittel,149.45,126.83
9,9,9,Bayern,Bayern,39.046006,48.631496,5,oberen Drittel,145.76,122.61
10,10,10,Saarland,Saarland,37.296196,57.300454,1,oberen Drittel,158.81,142.87
11,11,11,Berlin,Berlin,8.765882,6.285632,14,unteren Drittel,152.23,125.42
12,12,12,Brandenburg,Brandenburg,23.664638,30.879479,9,mittleren Drittel,145.56,144.32
13,13,13,Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,18.805360,23.298616,12,unteren Drittel,152.01,125.07
14,14,14,Sachsen,Sachsen,31.825972,29.672183,10,mittleren Drittel,141.72,122.10
15,15,15,Sachsen-Anhalt,Sachsen-Anhalt,39.463087,50.301932,4,oberen Drittel,142.97,131.93
16,16,16,Thüringen,Thüringen,34.420168,41.644405,6,mittleren Drittel,136.75,124.52

In [530]:
bu_landkreis = buildings_df.iloc[17:].copy()
bu_landkreis

,Unnamed: 0,AGS,Name,Bundesland,buildings_anteil_erneuerbare_2016,buildings_anteil_erneuerbare_2020,buildings_rank,buildings_third,buildings_heating_2002,buildings_heating_2020
17,17,1001,Flensburg,Schleswig-Holstein,2.846975,1.363636,399,unteren Drittel,165.51,129.76
18,18,1002,Kiel,Schleswig-Holstein,16.194332,4.059041,394,unteren Drittel,165.51,129.76
19,19,1003,Lübeck,Schleswig-Holstein,17.380952,7.032967,389,unteren Drittel,165.51,129.76
20,20,1004,Neumünster,Schleswig-Holstein,0.000000,20.000000,345,unteren Drittel,165.51,129.76
21,21,1051,Dithmarschen,Schleswig-Holstein,24.343675,37.911025,252,mittleren Drittel,165.51,129.76
...,...,...,...,...,...,...,...,...,...,...
411,411,16073,Saalfeld-Rudolstadt,Thüringen,46.666667,55.376344,130,oberen Drittel,136.75,124.52
412,412,16074,Saale-Holzland-Kreis,Thüringen,47.435897,70.992366,31,oberen Drittel,136.75,124.52
413,413,16075,Saale-Orla-Kreis,Thüringen,43.103448,42.028986,225,mittleren Drittel,136.75,124.52
414,414,16076,Greiz,Thüringen,61.818182,52.702703,157,mittleren Drittel,136.75,124.52
415,415,16077,Altenburger Land,Thüringen,20.792079,24.817518,324,unteren Drittel,136.75,124.52

In [531]:
#write buildings deutschland postcard text
bu_deutschland['buildings_postcard'] = f"Wir könnten etwas dagegen tun, zum Beispiel bei den Gebäuden. In <span className='location-name'>Deutschland</span> verbrauchen Gebäude <span className='ge-data-heat'>{round(bu_deutschland['buildings_heating_2020'])} Kilowattstunden pro Quadratmeter</span> im Jahr um zu Heizen, 2002 waren es <span className='ge-data-heat'>{round(bu_deutschland['buildings_heating_2002'])}</span>.\n\nIm Jahr 2020 wurden <span className='ge-data-erneuerbare'>{round(bu_deutschland['buildings_anteil_erneuerbare_2020'])} Prozent</span> der neuen Gebäude mit erneuerbaren Energien geheizt, 2016 waren es <span className='ge-data-erneuerbare'>{round(bu_deutschland['buildings_anteil_erneuerbare_2016'])} Prozent</span>.\n\nUm die Erderhitzung zu stoppen, müssen Gebäude viel weniger Energie verbrauchen und emissionsfrei geheizt werden. Schaffen wir das?\n\nViele Grüße!"
bu_deutschland

Unnamed: 0                                                                           0
AGS                                                                                  0
Name                                                                       Deutschland
Bundesland                                                                 Deutschland
buildings_anteil_erneuerbare_2016                                            29.271487
buildings_anteil_erneuerbare_2020                                            37.250119
buildings_rank                                                                       0
buildings_third                                                                    NaN
buildings_heating_2002                                                          150.84
buildings_heating_2020                                                          128.34
buildings_postcard                   Wir könnten etwas dagegen tun, zum Beispiel be...
Name: 0, dtype: object

In [532]:
#write building bundesland postcard text
bu_bundesland['buildings_postcard'] = bu_bundesland.agg(lambda x: f"Wir könnten etwas dagegen tun, zum Beispiel bei den Gebäuden. In <span className='location-name'>{x['Name']}</span> verbrauchen Wohngebäude <span className='ge-data-heat'>{round(x['buildings_heating_2020'])} Kilowattstunden pro Quadratmeter</span> im Jahr um zu Heizen, 2002 waren es <span className='ge-data-heat'>{round(x['buildings_heating_2002'])}</span>.\n\nIm Jahr 2020 wurden <span className='ge-data-erneuerbare'>{round(x['buildings_anteil_erneuerbare_2020'])} Prozent</span> der neuen Wohngebäude mit erneuerbaren Energien geheizt, 2016 waren es <span className='ge-data-erneuerbare'>{round(x['buildings_anteil_erneuerbare_2016'])} Prozent</span>. Damit liegt das Bundesland im Vergleich im <span className='{x['buildings_third']}'>{x['buildings_third']}</span>.\n\nUm die Erderhitzung zu stoppen, müssen Gebäude viel weniger Energie verbrauchen und emissionsfrei geheizt werden. Schaffen wir das?\n\nViele Grüße!"
                                                     , axis =1)
bu_bundesland

,Unnamed: 0,AGS,Name,Bundesland,buildings_anteil_erneuerbare_2016,buildings_anteil_erneuerbare_2020,buildings_rank,buildings_third,buildings_heating_2002,buildings_heating_2020,buildings_postcard
1,1,1,Schleswig-Holstein,Schleswig-Holstein,17.315705,26.782061,11,mittleren Drittel,165.51,129.76,"Wir könnten etwas dagegen tun, zum Beispiel be..."
2,2,2,Hamburg,Hamburg,7.976157,5.865467,16,unteren Drittel,171.08,141.22,"Wir könnten etwas dagegen tun, zum Beispiel be..."
3,3,3,Niedersachsen,Niedersachsen,15.535673,20.774876,13,unteren Drittel,155.90,130.12,"Wir könnten etwas dagegen tun, zum Beispiel be..."
4,4,4,Bremen,Bremen,4.927353,6.030856,15,unteren Drittel,154.03,124.85,"Wir könnten etwas dagegen tun, zum Beispiel be..."
5,5,5,Nordrhein-Westfalen,Nordrhein-Westfalen,27.602738,40.593871,7,mittleren Drittel,154.65,130.29,"Wir könnten etwas dagegen tun, zum Beispiel be..."
6,6,6,Hessen,Hessen,28.710400,35.131420,8,mittleren Drittel,154.04,128.03,"Wir könnten etwas dagegen tun, zum Beispiel be..."
7,7,7,Rheinland-Pfalz,Rheinland-Pfalz,36.154753,52.370872,3,oberen Drittel,146.97,129.72,"Wir könnten etwas dagegen tun, zum Beispiel be..."
8,8,8,Baden-Württemberg,Baden-Württemberg,46.136448,55.384876,2,oberen Drittel,149.45,126.83,"Wir könnten etwas dagegen tun, zum Beispiel be..."
9,9,9,Bayern,Bayern,39.046006,48.631496,5,oberen Drittel,145.76,122.61,"Wir könnten etwas dagegen tun, zum Beispiel be..."
10,10,10,Saarland,Saarland,37.296196,57.300454,1,oberen Drittel,158.81,142.87,"Wir könnten etwas dagegen tun, zum Beispiel be..."
11,11,11,Berlin,Berlin,8.765882,6.285632,14,unteren Drittel,152.23,125.42,"Wir könnten etwas dagegen tun, zum Beispiel be..."
12,12,12,Brandenburg,Brandenburg,23.664638,30.879479,9,mittleren Drittel,145.56,144.32,"Wir könnten etwas dagegen tun, zum Beispiel be..."
13,13,13,Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,18.805360,23.298616,12,unteren Drittel,152.01,125.07,"Wir könnten etwas dagegen tun, zum Beispiel be..."
14,14,14,Sachsen,Sachsen,31.825972,29.672183,10,mittleren Drittel,141.72,122.10,"Wir könnten etwas dagegen tun, zum Beispiel be..."
15,15,15,Sachsen-Anhalt,Sachsen-Anhalt,39.463087,50.301932,4,oberen Drittel,142.97,131.93,"Wir könnten etwas dagegen tun, zum Beispiel be..."
16,16,16,Thüringen,Thüringen,34.420168,41.644405,6,mittleren Drittel,136.75,124.52,"Wir könnten etwas dagegen tun, zum Beispiel be..."

In [533]:
#write building landkreis postcard text
bu_landkreis['buildings_postcard'] = bu_landkreis.agg(lambda x: f"Wir könnten etwas dagegen tun, zum Beispiel bei den Gebäuden. In <span className='location-name'>{x['Name']}</span> wurden 2020 <span className='ge-data-erneuerbare'>{round(x['buildings_anteil_erneuerbare_2020'])} Prozent</span> der neuen Wohngebäude mit erneuerbaren Energien geheizt, 2016 waren es <span className='ge-data-erneuerbare'>{round(x['buildings_anteil_erneuerbare_2016'])} Prozent</span>. Aktuell liegt <span className='location-name'>{x['Name']}</span> im Vergleich der Landkreise und Städte im <span className='{x['buildings_third']}'>{x['buildings_third']}</span>. In <span className='location-name'>{x['Bundesland']}</span> verbrauchen Wohngebäude <span className='ge-data-heat'>{round(x['buildings_heating_2020'])} Kilowattstunden pro Quadratmeter</span> im Jahr um zu Heizen, 2002 waren es <span className='ge-data-heat'>{round(x['buildings_heating_2002'])}</span>.\n\nUm die Erderhitzung zu stoppen, müssen Gebäude viel weniger Energie verbrauchen und emissionsfrei geheizt werden. Schaffen wir das?\n\nViele Grüße!"
                                                     , axis =1)
bu_landkreis

,Unnamed: 0,AGS,Name,Bundesland,buildings_anteil_erneuerbare_2016,buildings_anteil_erneuerbare_2020,buildings_rank,buildings_third,buildings_heating_2002,buildings_heating_2020,buildings_postcard
17,17,1001,Flensburg,Schleswig-Holstein,2.846975,1.363636,399,unteren Drittel,165.51,129.76,"Wir könnten etwas dagegen tun, zum Beispiel be..."
18,18,1002,Kiel,Schleswig-Holstein,16.194332,4.059041,394,unteren Drittel,165.51,129.76,"Wir könnten etwas dagegen tun, zum Beispiel be..."
19,19,1003,Lübeck,Schleswig-Holstein,17.380952,7.032967,389,unteren Drittel,165.51,129.76,"Wir könnten etwas dagegen tun, zum Beispiel be..."
20,20,1004,Neumünster,Schleswig-Holstein,0.000000,20.000000,345,unteren Drittel,165.51,129.76,"Wir könnten etwas dagegen tun, zum Beispiel be..."
21,21,1051,Dithmarschen,Schleswig-Holstein,24.343675,37.911025,252,mittleren Drittel,165.51,129.76,"Wir könnten etwas dagegen tun, zum Beispiel be..."
...,...,...,...,...,...,...,...,...,...,...,...
411,411,16073,Saalfeld-Rudolstadt,Thüringen,46.666667,55.376344,130,oberen Drittel,136.75,124.52,"Wir könnten etwas dagegen tun, zum Beispiel be..."
412,412,16074,Saale-Holzland-Kreis,Thüringen,47.435897,70.992366,31,oberen Drittel,136.75,124.52,"Wir könnten etwas dagegen tun, zum Beispiel be..."
413,413,16075,Saale-Orla-Kreis,Thüringen,43.103448,42.028986,225,mittleren Drittel,136.75,124.52,"Wir könnten etwas dagegen tun, zum Beispiel be..."
414,414,16076,Greiz,Thüringen,61.818182,52.702703,157,mittleren Drittel,136.75,124.52,"Wir könnten etwas dagegen tun, zum Beispiel be..."
415,415,16077,Altenburger Land,Thüringen,20.792079,24.817518,324,unteren Drittel,136.75,124.52,"Wir könnten etwas dagegen tun, zum Beispiel be..."

In [534]:
#merge all levels together
bu_postcards = bu_landkreis[['AGS','buildings_third','buildings_postcard']]
bu_postcards = bu_postcards.append(bu_bundesland[['AGS','buildings_third','buildings_postcard']])
bu_postcards = bu_postcards.append(bu_deutschland[['AGS','buildings_third','buildings_postcard']])
bu_postcards

     AGS    buildings_third                                 buildings_postcard
17  1001    unteren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
18  1002    unteren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
19  1003    unteren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
20  1004    unteren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
21  1051  mittleren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
..   ...                ...                                                ...
13    13    unteren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
14    14  mittleren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
15    15     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
16    16  mittleren Drittel  Wir könnten etwas dagegen tun, zum Beispiel be...
0      0                NaN  Wir könnten etwas dagegen tun, zum Beispiel be...

[416 rows x 3 columns]

In [535]:
#merge energy postcards into base dataframe
postcards_df=postcards_df.merge(bu_postcards, on='AGS',how='left')
postcards_df['buildings_postcard'] = postcards_df['gerics_text']+postcards_df['buildings_postcard']
postcards_df

,AGS,Name,gerics_text,energy_third,energy_postcard,mobility_third,mobility_postcard,agriculture_third,agriculture_postcard,buildings_third,buildings_postcard
0,0,Deutschland,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,NaN,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,NaN,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,NaN,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,NaN,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
1,1,Schleswig-Holstein,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
2,2,Hamburg,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
3,3,Niedersachsen,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
4,4,Bremen,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
...,...,...,...,...,...,...,...,...,...,...,...
411,16073,Saalfeld-Rudolstadt,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
412,16074,Saale-Holzland-Kreis,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
413,16075,Saale-Orla-Kreis,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
414,16076,Greiz,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
415,16077,Altenburger Land,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...

## Waste

In [536]:
waste_df = pd.read_csv("waste/data/final_postcard_data_waste.csv")
waste_df

,Unnamed: 0,AGS,Name,Bundesland,kg_per_person_2016,kg_per_person_2020,waste_rank,waste_third
0,0,0,Deutschland,Deutschland,123.403127,127.883928,0.0,NaN
1,1,1,Schleswig-Holstein,Schleswig-Holstein,117.645630,122.787134,7.0,mittleren Drittel
2,2,2,Hamburg,Hamburg,51.313550,55.292964,15.0,unteren Drittel
3,3,3,Niedersachsen,Niedersachsen,163.231490,166.173440,2.0,oberen Drittel
4,4,4,Bremen,Bremen,85.839768,83.545793,13.0,unteren Drittel
...,...,...,...,...,...,...,...,...
411,411,16073,Saalfeld-Rudolstadt,Thüringen,151.576421,183.759387,101.0,oberen Drittel
412,412,16074,Saale-Holzland-Kreis,Thüringen,4.401065,8.223049,397.0,unteren Drittel
413,413,16075,Saale-Orla-Kreis,Thüringen,151.429057,183.757786,102.0,oberen Drittel
414,414,16076,Greiz,Thüringen,169.690223,128.812016,233.0,mittleren Drittel
415,415,16077,Altenburger Land,Thüringen,138.843102,152.451446,169.0,mittleren Drittel

In [537]:
wa_deutschland = waste_df.iloc[0].copy()
wa_deutschland

Unnamed: 0                      0
AGS                             0
Name                  Deutschland
Bundesland            Deutschland
kg_per_person_2016     123.403127
kg_per_person_2020     127.883928
waste_rank                    0.0
waste_third                   NaN
Name: 0, dtype: object

In [538]:
wa_bundesland = waste_df.iloc[1:17].copy()
wa_bundesland

,Unnamed: 0,AGS,Name,Bundesland,kg_per_person_2016,kg_per_person_2020,waste_rank,waste_third
1,1,1,Schleswig-Holstein,Schleswig-Holstein,117.645630,122.787134,7.0,mittleren Drittel
2,2,2,Hamburg,Hamburg,51.313550,55.292964,15.0,unteren Drittel
3,3,3,Niedersachsen,Niedersachsen,163.231490,166.173440,2.0,oberen Drittel
4,4,4,Bremen,Bremen,85.839768,83.545793,13.0,unteren Drittel
5,5,5,Nordrhein-Westfalen,Nordrhein-Westfalen,116.229591,116.276247,9.0,mittleren Drittel
6,6,6,Hessen,Hessen,138.456915,132.718824,5.0,oberen Drittel
7,7,7,Rheinland-Pfalz,Rheinland-Pfalz,171.978083,189.714695,1.0,oberen Drittel
8,8,8,Baden-Württemberg,Baden-Württemberg,140.292276,143.719699,4.0,oberen Drittel
9,9,9,Bayern,Bayern,153.394648,154.237806,3.0,oberen Drittel
10,10,10,Saarland,Saarland,135.637249,126.056031,6.0,mittleren Drittel
11,11,11,Berlin,Berlin,23.869387,36.244763,16.0,unteren Drittel
12,12,12,Brandenburg,Brandenburg,66.456270,88.139369,12.0,unteren Drittel
13,13,13,Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,74.593617,94.204401,11.0,mittleren Drittel
14,14,14,Sachsen,Sachsen,55.997342,79.786716,14.0,unteren Drittel
15,15,15,Sachsen-Anhalt,Sachsen-Anhalt,122.934267,122.280440,8.0,mittleren Drittel
16,16,16,Thüringen,Thüringen,105.397363,116.048347,10.0,mittleren Drittel

In [539]:
wa_landkreis = waste_df.iloc[17:].copy()
wa_landkreis

,Unnamed: 0,AGS,Name,Bundesland,kg_per_person_2016,kg_per_person_2020,waste_rank,waste_third
17,17,1001,Flensburg,Schleswig-Holstein,69.471132,67.271555,357.0,unteren Drittel
18,18,1002,Kiel,Schleswig-Holstein,65.470152,66.232497,360.0,unteren Drittel
19,19,1003,Lübeck,Schleswig-Holstein,86.732622,102.999361,297.0,unteren Drittel
20,20,1004,Neumünster,Schleswig-Holstein,133.948293,198.247919,70.0,oberen Drittel
21,21,1051,Dithmarschen,Schleswig-Holstein,131.371668,139.323532,203.0,mittleren Drittel
...,...,...,...,...,...,...,...,...
411,411,16073,Saalfeld-Rudolstadt,Thüringen,151.576421,183.759387,101.0,oberen Drittel
412,412,16074,Saale-Holzland-Kreis,Thüringen,4.401065,8.223049,397.0,unteren Drittel
413,413,16075,Saale-Orla-Kreis,Thüringen,151.429057,183.757786,102.0,oberen Drittel
414,414,16076,Greiz,Thüringen,169.690223,128.812016,233.0,mittleren Drittel
415,415,16077,Altenburger Land,Thüringen,138.843102,152.451446,169.0,mittleren Drittel

In [540]:
#write waste deutschland postcard text
wa_deutschland['waste_postcard'] = f"Wir könnten etwas dagegen tun, zum Beispiel im Umgang mit Abfall. In <span className='location-name'>{wa_deutschland['Name']}</span> wurden 2020 etwa <span className='ab-data-bio'>{round(wa_deutschland['kg_per_person_2020'])} Kilo Biomüll pro Person</span> getrennt gesammelt und so etwa <span className='ab-data-co'>{round(wa_deutschland['kg_per_person_2020']*0.1)}</span> bis <span className='ab-data-co'>{round(wa_deutschland['kg_per_person_2020']*0.2)} Kilo CO2</span> pro Person vermieden. 2016 wurden <span className='ab-data-bio'>{round(wa_deutschland['kg_per_person_2016'])} Kilo Bioabfall pro Person</span> gesammelt.\n\nSchon jetzt vermeidet der Bereich Abfall mehr Emissionen in den anderen Bereichen als er selbst produziert. Aber schaffen wir es im Umgang mit Abfall emissionsfrei zu werden?\n\nViele Grüße!"
wa_deutschland

Unnamed: 0                                                            0
AGS                                                                   0
Name                                                        Deutschland
Bundesland                                                  Deutschland
kg_per_person_2016                                           123.403127
kg_per_person_2020                                           127.883928
waste_rank                                                          0.0
waste_third                                                         NaN
waste_postcard        Wir könnten etwas dagegen tun, zum Beispiel im...
Name: 0, dtype: object

In [541]:
#write waste bundesland postcard text
wa_bundesland['waste_postcard'] = wa_bundesland.agg(lambda x: f"Wir könnten etwas dagegen tun, zum Beispiel im Umgang mit Abfall. In <span className='location-name'>{x['Name']}</span> wurden 2020 etwa <span className='ab-data-bio'>{round(x['kg_per_person_2020'])} Kilo Biomüll pro Person</span> getrennt gesammelt und so etwa <span className='ab-data-co'>{round(x['kg_per_person_2020']*0.1)}</span> bis <span className='ab-data-co'>{round(x['kg_per_person_2020']*0.2)} Kilo CO2 pro Person</span> vermieden. 2016 wurden <span className='ab-data-bio'>{round(x['kg_per_person_2016'])} Kilo Bioabfall pro Person</span> gesammelt. Damit liegt das Bundesland im Vergleich im <span className='{x['waste_third']}'>{x['waste_third']}</span>.\n\nSchon jetzt vermeidet der Bereich Abfall mehr Emissionen in den anderen Bereichen als er selbst produziert. Aber schaffen wir es im Umgang mit Abfall emissionsfrei zu werden?\n\nViele Grüße!"
                                                     , axis =1)
wa_bundesland

,Unnamed: 0,AGS,Name,Bundesland,kg_per_person_2016,kg_per_person_2020,waste_rank,waste_third,waste_postcard
1,1,1,Schleswig-Holstein,Schleswig-Holstein,117.645630,122.787134,7.0,mittleren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
2,2,2,Hamburg,Hamburg,51.313550,55.292964,15.0,unteren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
3,3,3,Niedersachsen,Niedersachsen,163.231490,166.173440,2.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
4,4,4,Bremen,Bremen,85.839768,83.545793,13.0,unteren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
5,5,5,Nordrhein-Westfalen,Nordrhein-Westfalen,116.229591,116.276247,9.0,mittleren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
6,6,6,Hessen,Hessen,138.456915,132.718824,5.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
7,7,7,Rheinland-Pfalz,Rheinland-Pfalz,171.978083,189.714695,1.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
8,8,8,Baden-Württemberg,Baden-Württemberg,140.292276,143.719699,4.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
9,9,9,Bayern,Bayern,153.394648,154.237806,3.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
10,10,10,Saarland,Saarland,135.637249,126.056031,6.0,mittleren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
11,11,11,Berlin,Berlin,23.869387,36.244763,16.0,unteren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
12,12,12,Brandenburg,Brandenburg,66.456270,88.139369,12.0,unteren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
13,13,13,Mecklenburg-Vorpommern,Mecklenburg-Vorpommern,74.593617,94.204401,11.0,mittleren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
14,14,14,Sachsen,Sachsen,55.997342,79.786716,14.0,unteren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
15,15,15,Sachsen-Anhalt,Sachsen-Anhalt,122.934267,122.280440,8.0,mittleren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
16,16,16,Thüringen,Thüringen,105.397363,116.048347,10.0,mittleren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."

In [542]:
#write waste bundesland postcard text
wa_landkreis['waste_postcard'] = wa_landkreis.agg(lambda x: f"Wir könnten etwas dagegen tun, zum Beispiel im Umgang mit Abfall. In <span className='location-name'>{x['Name']}</span> wurden 2020 etwa <span className='ab-data-bio'>{round(x['kg_per_person_2020'])} Kilo Biomüll pro Person</span> getrennt gesammelt und so etwa <span className='ab-data-co'>{round(x['kg_per_person_2020']*0.1)}</span> bis <span className='ab-data-co'>{round(x['kg_per_person_2020']*0.2)} Kilo CO2 pro Person</span> vermieden. 2016 wurden <span className='ab-data-bio'>{round(x['kg_per_person_2016'])} Kilo Bioabfall pro Person</span> gesammelt. Damit liegt der Landkreis im Vergleich im <span className='{x['waste_third']}'>{x['waste_third']}</span>.\n\nSchon jetzt vermeidet der Bereich Abfall mehr Emissionen in den anderen Bereichen als er selbst produziert. Aber schaffen wir es im Umgang mit Abfall emissionsfrei zu werden?\n\nViele Grüße!" if pd.isna(x['kg_per_person_2020']) == False
                                                  else "Für diesen Kreis ist das Bioabfallaufkommen unbekannt oder geheim.\n\nSchon jetzt vermeidet der Bereich Abfall mehr Emissionen in den anderen Bereichen als er selbst produziert. Aber schaffen wir es im Umgang mit Abfall emissionsfrei zu werden?\n\nViele Grüße!"
                                                  , axis =1)
wa_landkreis

,Unnamed: 0,AGS,Name,Bundesland,kg_per_person_2016,kg_per_person_2020,waste_rank,waste_third,waste_postcard
17,17,1001,Flensburg,Schleswig-Holstein,69.471132,67.271555,357.0,unteren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
18,18,1002,Kiel,Schleswig-Holstein,65.470152,66.232497,360.0,unteren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
19,19,1003,Lübeck,Schleswig-Holstein,86.732622,102.999361,297.0,unteren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
20,20,1004,Neumünster,Schleswig-Holstein,133.948293,198.247919,70.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
21,21,1051,Dithmarschen,Schleswig-Holstein,131.371668,139.323532,203.0,mittleren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
...,...,...,...,...,...,...,...,...,...
411,411,16073,Saalfeld-Rudolstadt,Thüringen,151.576421,183.759387,101.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
412,412,16074,Saale-Holzland-Kreis,Thüringen,4.401065,8.223049,397.0,unteren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
413,413,16075,Saale-Orla-Kreis,Thüringen,151.429057,183.757786,102.0,oberen Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
414,414,16076,Greiz,Thüringen,169.690223,128.812016,233.0,mittleren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."
415,415,16077,Altenburger Land,Thüringen,138.843102,152.451446,169.0,mittleren Drittel,"Wir könnten etwas dagegen tun, zum Beispiel im..."

In [543]:
#merge all levels together
wa_postcards = wa_landkreis[['AGS','waste_third','waste_postcard']]
wa_postcards = wa_postcards.append(wa_bundesland[['AGS','waste_third','waste_postcard']])
wa_postcards = wa_postcards.append(wa_deutschland[['AGS','waste_third','waste_postcard']])
wa_postcards

     AGS        waste_third                                     waste_postcard
17  1001    unteren Drittel  Wir könnten etwas dagegen tun, zum Beispiel im...
18  1002    unteren Drittel  Wir könnten etwas dagegen tun, zum Beispiel im...
19  1003    unteren Drittel  Wir könnten etwas dagegen tun, zum Beispiel im...
20  1004     oberen Drittel  Wir könnten etwas dagegen tun, zum Beispiel im...
21  1051  mittleren Drittel  Wir könnten etwas dagegen tun, zum Beispiel im...
..   ...                ...                                                ...
13    13  mittleren Drittel  Wir könnten etwas dagegen tun, zum Beispiel im...
14    14    unteren Drittel  Wir könnten etwas dagegen tun, zum Beispiel im...
15    15  mittleren Drittel  Wir könnten etwas dagegen tun, zum Beispiel im...
16    16  mittleren Drittel  Wir könnten etwas dagegen tun, zum Beispiel im...
0      0                NaN  Wir könnten etwas dagegen tun, zum Beispiel im...

[416 rows x 3 columns]

In [544]:
#merge energy postcards into base dataframe
postcards_df=postcards_df.merge(wa_postcards, on='AGS',how='left')
postcards_df['waste_postcard'] = postcards_df['gerics_text']+postcards_df['waste_postcard']
postcards_df

,AGS,Name,gerics_text,energy_third,energy_postcard,mobility_third,mobility_postcard,agriculture_third,agriculture_postcard,buildings_third,buildings_postcard,waste_third,waste_postcard
0,0,Deutschland,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,NaN,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,NaN,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,NaN,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,NaN,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,NaN,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
1,1,Schleswig-Holstein,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
2,2,Hamburg,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
3,3,Niedersachsen,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
4,4,Bremen,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,16073,Saalfeld-Rudolstadt,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
412,16074,Saale-Holzland-Kreis,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
413,16075,Saale-Orla-Kreis,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
414,16076,Greiz,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...
415,16077,Altenburger Land,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,oberen Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,unteren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...,mittleren Drittel,Hallo!\n\nIch schicke dir Grüße aus dem schöne...

## Save to File

In [545]:
#save to file
postcards_df.to_csv('final_postcard_texts.csv')