In [117]:
### Download waste data on household waste 
### from regionalstatistik.de and compile into csv with Regions as rows
### and indicators and years as columns.

In [118]:
#41141-03-01-4
#https://www.regionalstatistik.de/genesis//online?operation=table&code=32121-01-02-4-B&bypass=true&levelindex=0&levelid=1658850132846#abreadcrumb
#include years 2007-2020 and set regions to Landkreise, download as csv

In [119]:
# import necessary libraries

import pandas as pd
import numpy as np

In [121]:
#load dataset from local file
source_df = pd.read_csv("data/32121-01-02-4_flat_haushaltsabfaelle.csv",delimiter=";", encoding='latin1', low_memory=False)

# #remove subgroups of waste (everything except for organic waste total) Haus- und Sperrmüll, Getrennt erfasste organische Abfälle, Getrennt erfasste Wertstoffe, Sonstige Abfälle, Biotonne, abbaubare Garten- und Parkabfälle and Insgesamt
# source_df = source_df[(source_df['2_Auspraegung_Code'] != 'ABFALLART100') & (source_df['2_Auspraegung_Code'] != 'ABFALLART300') & (source_df['2_Auspraegung_Code'] != 'ABFALLART400') & (source_df['2_Auspraegung_Code'] != 'ABFALLART201') & (source_df['2_Auspraegung_Code'] != 'ABFALLART202') & (source_df['2_Auspraegung_Label'] != "Insgesamt")]

#remove subgroups of waste Haus- und Sperrmüll, Getrennt erfasste organische Abfälle, Getrennt erfasste Wertstoffe, Sonstige Abfälle and Insgesamt
source_df = source_df[(source_df['2_Auspraegung_Code'] != 'ABFALLART100') & (source_df['2_Auspraegung_Code'] != 'ABFALLART300') & (source_df['2_Auspraegung_Code'] != 'ABFALLART400') & (source_df['2_Auspraegung_Label'] != "Insgesamt") ]

source_df

,Statistik_Code,Statistik_Label,Zeit_Code,Zeit_Label,Zeit,1_Merkmal_Code,1_Merkmal_Label,1_Auspraegung_Code,1_Auspraegung_Label,2_Merkmal_Code,2_Merkmal_Label,2_Auspraegung_Code,2_Auspraegung_Label,AEW009__Aufkommen_an_Haushaltsabfaellen_(o.E-altgeraete)__t
2,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2020,KREISE,Kreise und kreisfreie Städte,DG,Deutschland,ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,10634192
3,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2020,KREISE,Kreise und kreisfreie Städte,DG,Deutschland,ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART201,Abfälle aus der Biotonne,5300612
4,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2020,KREISE,Kreise und kreisfreie Städte,DG,Deutschland,ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART202,biolog. abbaubare Garten- und Parkabfälle,5333580
9,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2020,KREISE,Kreise und kreisfreie Städte,01,Schleswig-Holstein,ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,357418
10,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2020,KREISE,Kreise und kreisfreie Städte,01,Schleswig-Holstein,ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART201,Abfälle aus der Biotonne,289453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64011,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2004,KREISE,Kreise und kreisfreie Städte,16076,"Greiz, Kreis",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART201,Abfälle aus der Biotonne,3845
64012,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2004,KREISE,Kreise und kreisfreie Städte,16076,"Greiz, Kreis",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART202,biolog. abbaubare Garten- und Parkabfälle,2168
64017,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2004,KREISE,Kreise und kreisfreie Städte,16077,"Altenburger Land, Kreis",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,11950
64018,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2004,KREISE,Kreise und kreisfreie Städte,16077,"Altenburger Land, Kreis",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART201,Abfälle aus der Biotonne,5435
64019,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2004,KREISE,Kreise und kreisfreie Städte,16077,"Altenburger Land, Kreis",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART202,biolog. abbaubare Garten- und Parkabfälle,6515

In [123]:
waste_df = source_df.copy()

#extract year from date
waste_df['Jahr']=waste_df['Zeit'].astype(str)

#drop unnecessary columns
waste_df.drop(columns=['Zeit','Statistik_Code', 'Statistik_Label', 'Zeit_Code', 'Zeit_Label', 
       '1_Merkmal_Code', '1_Merkmal_Label', 
       '2_Merkmal_Code', '2_Merkmal_Label',
       '2_Auspraegung_Code'],inplace=True)

#rename columns
waste_df.rename(columns={'1_Auspraegung_Code':'AGS','1_Auspraegung_Label':'Name','2_Auspraegung_Label':'Abfall','AEW009__Aufkommen_an_Haushaltsabfaellen_(o.E-altgeraete)__t':'weight'},inplace=True)

#replace '-' with 0 and '.' with 'NaN according to Zeichnerklärung
waste_df['weight'].replace('-','0',inplace=True)
waste_df['weight'] = waste_df['weight'].apply(pd.to_numeric,errors='coerce')

waste_df['AGS']=waste_df['AGS'].replace("DG",0)

waste_df

,AGS,Name,Abfall,weight,Jahr
2,0,Deutschland,Getrennt erfasste organische Abfälle,10634192.0,2020
3,0,Deutschland,Abfälle aus der Biotonne,5300612.0,2020
4,0,Deutschland,biolog. abbaubare Garten- und Parkabfälle,5333580.0,2020
9,01,Schleswig-Holstein,Getrennt erfasste organische Abfälle,357418.0,2020
10,01,Schleswig-Holstein,Abfälle aus der Biotonne,289453.0,2020
...,...,...,...,...,...
64011,16076,"Greiz, Kreis",Abfälle aus der Biotonne,3845.0,2004
64012,16076,"Greiz, Kreis",biolog. abbaubare Garten- und Parkabfälle,2168.0,2004
64017,16077,"Altenburger Land, Kreis",Getrennt erfasste organische Abfälle,11950.0,2004
64018,16077,"Altenburger Land, Kreis",Abfälle aus der Biotonne,5435.0,2004
64019,16077,"Altenburger Land, Kreis",biolog. abbaubare Garten- und Parkabfälle,6515.0,2004

In [124]:
#pivot dataframe to show waste and years as columns
pt_df = waste_df.pivot(index=['AGS','Name'],columns=['Abfall','Jahr'],values=['weight'])

#rename columns
pt_df.rename(columns={'Getrennt erfasste organische Abfälle':'sum'},inplace=True)

#rename columns sub groups organic waste
pt_df.rename(columns={'biolog. abbaubare Garten- und Parkabfälle':'gartenPark', 'Abfälle aus der Biotonne':'biotonne'},inplace=True)

pt_df

                                                          weight             \
Abfall                                                       sum   biotonne
Jahr                                                        2020       2020
AGS   Name
0     Deutschland                                     10634192.0  5300612.0
01      Schleswig-Holstein                              357418.0   289453.0
01001       Flensburg, kreisfreie Stadt                   6050.0     4753.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt     16333.0    12825.0
01003       Lübeck, Hansestadt, kreisfreie Stadt         22232.0    15850.0
...                                                          ...        ...
16073       Saalfeld-Rudolstadt, Kreis                   18769.0        0.0
16074       Saale-Holzland-Kreis                           681.0        0.0
16075       Saale-Orla-Kreis                             14633.0        0.0
16076       Greiz, Kreis                                 12452.0     4209.0
16077       Altenburger Land, Kreis                      13470.0     5606.0

                                                                             \
Abfall                                               gartenPark         sum
Jahr                                                       2020        2019
AGS   Name
0     Deutschland                                     5333580.0  10168446.0
01      Schleswig-Holstein                              67965.0    349582.0
01001       Flensburg, kreisfreie Stadt                  1297.0      5922.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt     3508.0     16035.0
01003       Lübeck, Hansestadt, kreisfreie Stadt         6383.0     20058.0
...                                                         ...         ...
16073       Saalfeld-Rudolstadt, Kreis                  18769.0     15470.0
16074       Saale-Holzland-Kreis                          681.0       337.0
16075       Saale-Orla-Kreis                            14633.0     12039.0
16076       Greiz, Kreis                                 8244.0     13994.0
16077       Altenburger Land, Kreis                      7863.0     14205.0

                                                                            \
Abfall                                                 biotonne gartenPark
Jahr                                                       2019       2019
AGS   Name
0     Deutschland                                     4974001.0  5194445.0
01      Schleswig-Holstein                             272217.0    77366.0
01001       Flensburg, kreisfreie Stadt                  4610.0     1311.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt    12231.0     3804.0
01003       Lübeck, Hansestadt, kreisfreie Stadt        15236.0     4823.0
...                                                         ...        ...
16073       Saalfeld-Rudolstadt, Kreis                      0.0    15470.0
16074       Saale-Holzland-Kreis                            0.0      337.0
16075       Saale-Orla-Kreis                                0.0    12039.0
16076       Greiz, Kreis                                 4122.0     9871.0
16077       Altenburger Land, Kreis                      5434.0     8771.0

                                                                            \
Abfall                                                      sum   biotonne
Jahr                                                       2018       2018
AGS   Name
0     Deutschland                                     9930936.0  4811882.0
01      Schleswig-Holstein                             329004.0   260503.0
01001       Flensburg, kreisfreie Stadt                  5764.0     4640.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt    15174.0    11696.0
01003       Lübeck, Hansestadt, kreisfreie Stadt        18789.0    14395.0
...                                                         ...        ...
16073       Saalfeld-Rudolstadt, Kreis                  17860.0        0.0
16074       Saale-Holzland-Kreis                          291.0        0.0
16075       Saale-Orla-Kreis                            13580.0        0.0
16076       Greiz, Kreis                                15448.0     4039.0
16077       Altenburger Land, Kreis                     12971.0     5255.0

                                                                             \
Abfall                                               gartenPark         sum
Jahr                                                       2018        2017
AGS   Name
0     Deutschland                                     5119053.0  10317997.0
01      Schleswig-Holstein                              68502.0    349171.0
01001       Flensburg, kreisfreie Stadt                  1124.0      5974.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt     3479.0     16425.0
01003       Lübeck, Hansestadt, kreisfreie Stadt         4394.0     19080.0
...                                                         ...         ...
16073       Saalfeld-Rudolstadt, Kreis                  17860.0     17208.0
16074       Saale-Holzland-Kreis                          291.0       268.0
16075       Saale-Orla-Kreis                            13580.0     13062.0
16076       Greiz, Kreis                                11409.0     16863.0
16077       Altenburger Land, Kreis                      7716.0     14383.0

                                                      ...             \
Abfall                                                ... gartenPark
Jahr                                                  ...       2007
AGS   Name                                            ...
0     Deutschland                                     ...  4565002.0
01      Schleswig-Holstein                            ...    71079.0
01001       Flensburg, kreisfreie Stadt               ...      388.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt  ...     2273.0
01003       Lübeck, Hansestadt, kreisfreie Stadt      ...     4423.0
...                                                   ...        ...
16073       Saalfeld-Rudolstadt, Kreis                ...    10394.0
16074       Saale-Holzland-Kreis                      ...        0.0
16075       Saale-Orla-Kreis                          ...     7774.0
16076       Greiz, Kreis                              ...     3050.0
16077       Altenburger Land, Kreis                   ...     7843.0

                                                                            \
Abfall                                                      sum   biotonne
Jahr                                                       2006       2006
AGS   Name
0     Deutschland                                     8449750.0  4150037.0
01      Schleswig-Holstein                             279705.0   199807.0
01001       Flensburg, kreisfreie Stadt                  5658.0     4865.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt    11872.0    10605.0
01003       Lübeck, Hansestadt, kreisfreie Stadt        20442.0    16406.0
...                                                         ...        ...
16073       Saalfeld-Rudolstadt, Kreis                   9314.0        0.0
16074       Saale-Holzland-Kreis                            0.0        0.0
16075       Saale-Orla-Kreis                             6945.0        0.0
16076       Greiz, Kreis                                 7711.0     6104.0
16077       Altenburger Land, Kreis                     11473.0     5013.0

                                                                            \
Abfall                                               gartenPark        sum
Jahr                                                       2006       2005
AGS   Name
0     Deutschland                                     4299713.0  8337073.0
01      Schleswig-Holstein                              79898.0   269548.0
01001       Flensburg, kreisfreie Stadt                   793.0     5731.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt     1267.0    12229.0
01003       Lübeck, Hansestadt, kreisfreie Stadt         4036.0    20012.0
...                                                         ...        ...
16073       Saalfeld-Rudolstadt, Kreis                   9314.0     8880.0
16074       Saale-Holzland-Kreis                            0.0        0.0
16075       Saale-Orla-Kreis                             6945.0     6622.0
16076       Greiz, Kreis                                 1607.0     6372.0
16077       Altenburger Land, Kreis                      6460.0    12038.0

                                                                            \
Abfall                                                 biotonne gartenPark
Jahr                                                       2005       2005
AGS   Name
0     Deutschland                                     4082797.0  4254278.0
01      Schleswig-Holstein                             199457.0    70091.0
01001       Flensburg, kreisfreie Stadt                  5008.0      723.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt    10346.0     1884.0
01003       Lübeck, Hansestadt, kreisfreie Stadt        16435.0     3577.0
...                                                         ...        ...
16073       Saalfeld-Rudolstadt, Kreis                      0.0     8880.0
16074       Saale-Holzland-Kreis                            0.0        0.0
16075       Saale-Orla-Kreis                                0.0     6622.0
16076       Greiz, Kreis                                 3922.0     2450.0
16077       Altenburger Land, Kreis                      5219.0     6819.0

                                                                            \
Abfall                                                      sum   biotonne
Jahr                                                       2004       2004
AGS   Name
0     Deutschland                                     8411408.0  4121133.0
01      Schleswig-Holstein                             280514.0   198751.0
01001       Flensburg, kreisfreie Stadt                  5647.0     5138.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt     9793.0     8759.0
01003       Lübeck, Hansestadt, kreisfreie Stadt        21755.0    16477.0
...                                                         ...        ...
16073       Saalfeld-Rudolstadt, Kreis                   9586.0        0.0
16074       Saale-Holzland-Kreis                            0.0        0.0
16075       Saale-Orla-Kreis                             7151.0        0.0
16076       Greiz, Kreis                                 6013.0     3845.0
16077       Altenburger Land, Kreis                     11950.0     5435.0


Abfall                                               gartenPark
Jahr                                                       2004
AGS   Name
0     Deutschland                                     4290276.0
01      Schleswig-Holstein                              81764.0
01001       Flensburg, kreisfreie Stadt                   509.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt     1033.0
01003       Lübeck, Hansestadt, kreisfreie Stadt         5279.0
...                                                         ...
16073       Saalfeld-Rudolstadt, Kreis                   9586.0
16074       Saale-Holzland-Kreis                            0.0
16075       Saale-Orla-Kreis                             7151.0
16076       Greiz, Kreis                                 2168.0
16077       Altenburger Land, Kreis                      6515.0

[538 rows x 51 columns]

In [125]:
#collapse levels of column names and join waste type to year
pt_df.columns = pt_df.columns.map('_'.join)

#sort columns so indicators are together
pt_df=pt_df[sorted(pt_df.columns)]

#prepend all columns with indicator name
pt_df=pt_df.add_prefix('waste_organicwaste_')

#convert AGS to numeric and set as new index
pt_df.reset_index(inplace=True)
pt_df['AGS'] = pd.to_numeric(pt_df['AGS'])
pt_df.set_index('AGS',inplace=True)
pt_df.sort_index(ascending=True,inplace=True)

#strip whitespace from region names
pt_df['Name']=pt_df['Name'].str.strip()

#unit of measure
pt_df["Unit"] = "Kg per person"


pt_df
#sorted(pt_df.columns)

,Name,waste_organicwaste_weight_biotonne_2004,waste_organicwaste_weight_biotonne_2005,waste_organicwaste_weight_biotonne_2006,waste_organicwaste_weight_biotonne_2007,waste_organicwaste_weight_biotonne_2008,waste_organicwaste_weight_biotonne_2009,waste_organicwaste_weight_biotonne_2010,waste_organicwaste_weight_biotonne_2011,waste_organicwaste_weight_biotonne_2012,...,waste_organicwaste_weight_sum_2012,waste_organicwaste_weight_sum_2013,waste_organicwaste_weight_sum_2014,waste_organicwaste_weight_sum_2015,waste_organicwaste_weight_sum_2016,waste_organicwaste_weight_sum_2017,waste_organicwaste_weight_sum_2018,waste_organicwaste_weight_sum_2019,waste_organicwaste_weight_sum_2020,Unit
AGS,,,,,,,,,,,,,,,,,,,,,
0,Deutschland,4121133.0,4082797.0,4150037.0,4215167.0,4212330.0,4324956.0,4204277.0,4349715.0,4358529.0,...,9095550.0,9056407.0,9831464.0,9665788.0,10183430.0,10317997.0,9930936.0,10168446.0,10634192.0,Kg per person
1,Schleswig-Holstein,198751.0,199457.0,199807.0,206930.0,205373.0,207825.0,202826.0,214194.0,215752.0,...,268689.0,268664.0,290647.0,317409.0,339046.0,349171.0,329004.0,349582.0,357418.0,Kg per person
2,Hamburg,27200.0,26200.0,25600.0,26800.0,25900.0,26700.0,28100.0,43200.0,53700.0,...,67900.0,71600.0,79300.0,87000.0,92900.0,97200.0,85630.0,91600.0,102429.0,Kg per person
3,Niedersachsen,497938.0,484742.0,484514.0,493127.0,485871.0,481892.0,473592.0,490789.0,485936.0,...,1173902.0,1142324.0,1278372.0,1261341.0,1296986.0,1324863.0,1271927.0,1258621.0,1329956.0,Kg per person
4,Bremen,24058.0,23721.0,23318.0,23942.0,23106.0,23135.0,22077.0,22778.0,22209.0,...,57770.0,55639.0,58544.0,57327.0,58264.0,58638.0,53216.0,56126.0,56822.0,Kg per person
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11008008,Berlin-Neukölln,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Kg per person
11009009,Berlin-Treptow-Köpenick,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Kg per person
11010010,Berlin-Marzahn-Hellersdorf,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Kg per person
11011011,Berlin-Lichtenberg,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Kg per person
11012012,Berlin-Reinickendorf,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Kg per person

In [147]:
#save dataframe to file
pt_df.to_csv("data/final_data_landkreis_waste_organicwaste.csv")

In [ ]:
## DATASNIPPET FOR TESTING

schweinfurt = waste_df[waste_df.AGS == "09678"]
schweinfurt.drop(["Name","AGS"],axis= 1,inplace=True)

schweinfurt.to_csv("data/snippet/organicwaste_schweinfurtLK.csv")

In [99]:
# convert column "a" of a DataFrame
waste_df["AGS"] = pd.to_numeric(waste_df["AGS"])
bundeslaender = waste_df[(waste_df["AGS"] <= 16) & (waste_df["AGS"] > 0)]
bundeslaender = bundeslaender[bundeslaender["Abfall"] == "Getrennt erfasste organische Abfälle"]
bundeslaender.drop(["AGS"],axis= 1,inplace=True)
bundeslaender = bundeslaender.reset_index(drop=True)
bundeslaender
bundeslaender.to_csv("data/snippet/organicwaste_bundeslaenderOhneDL.csv")

In [38]:
deutschland = waste_df[waste_df.Name == "Deutschland"]
deutschland.drop(["Name","AGS"],axis= 1,inplace=True)
deutschland
deutschland.to_csv("data/snippet/organicwaste_deutschland.csv")

/var/folders/dy/pr7w31xd5xnf1fpgcxmx8zrh0000gn/T/ipykernel_87196/3566189559.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  deutschland.drop(["Name","AGS"],axis= 1,inplace=True)

## Normalize waste_df by population

In [127]:
#copy waste_df
norm_wa = waste_df.copy()

#set variable types for merge
norm_wa['AGS'] = norm_wa['AGS'].astype(int)
norm_wa['Jahr'] = norm_wa['Jahr'].astype(int)
norm_wa

,AGS,Name,Abfall,weight,Jahr
2,0,Deutschland,Getrennt erfasste organische Abfälle,10634192.0,2020
3,0,Deutschland,Abfälle aus der Biotonne,5300612.0,2020
4,0,Deutschland,biolog. abbaubare Garten- und Parkabfälle,5333580.0,2020
9,1,Schleswig-Holstein,Getrennt erfasste organische Abfälle,357418.0,2020
10,1,Schleswig-Holstein,Abfälle aus der Biotonne,289453.0,2020
...,...,...,...,...,...
64011,16076,"Greiz, Kreis",Abfälle aus der Biotonne,3845.0,2004
64012,16076,"Greiz, Kreis",biolog. abbaubare Garten- und Parkabfälle,2168.0,2004
64017,16077,"Altenburger Land, Kreis",Getrennt erfasste organische Abfälle,11950.0,2004
64018,16077,"Altenburger Land, Kreis",Abfälle aus der Biotonne,5435.0,2004
64019,16077,"Altenburger Land, Kreis",biolog. abbaubare Garten- und Parkabfälle,6515.0,2004

In [128]:
# load population data from general data
pop_df = pd.read_csv("../general_data/population.csv",delimiter=";", encoding='latin1', low_memory=False)

#correct Germany AGS
pop_df['AGS'] = pop_df['1_Auspraegung_Code'].astype('string').str.replace('DG','0')

#extract year from time column
pop_df['Jahr'] = pop_df['Zeit'].astype('string').str[-4:]

#select only necessary coluns and rename
pop_df = pop_df[['AGS','Jahr','BEVSTD__Bevoelkerungsstand__Anzahl']]
pop_df.columns=['AGS','Jahr','Bevölkerung']

#set variable types for merge
pop_df['AGS'] = pop_df['AGS'].astype(int)
pop_df['Jahr'] = pop_df['Jahr'].astype(int)

pop_df

         AGS  Jahr Bevölkerung
0          0  1995    81817499
1          0  1996    82012162
2          0  1997    82057379
3          0  1998    82037011
4          0  1999    82163475
...      ...   ...         ...
13306  16073  2021      100969
13307  16074  2021       82513
13308  16075  2021       79030
13309  16076  2021       96102
13310  16077  2021       87807

[13311 rows x 3 columns]

In [130]:
#merge waste_df with population
merged_wa = norm_wa.merge(pop_df, on = ['AGS','Jahr'], how='left')
merged_wa['Bevölkerung'] =merged_wa['Bevölkerung'].apply(pd.to_numeric, errors='coerce')
merged_wa

,AGS,Name,Abfall,weight,Jahr,Bevölkerung
0,0,Deutschland,Getrennt erfasste organische Abfälle,10634192.0,2020,83155031.0
1,0,Deutschland,Abfälle aus der Biotonne,5300612.0,2020,83155031.0
2,0,Deutschland,biolog. abbaubare Garten- und Parkabfälle,5333580.0,2020,83155031.0
3,1,Schleswig-Holstein,Getrennt erfasste organische Abfälle,357418.0,2020,2910875.0
4,1,Schleswig-Holstein,Abfälle aus der Biotonne,289453.0,2020,2910875.0
...,...,...,...,...,...,...
27433,16076,"Greiz, Kreis",Abfälle aus der Biotonne,3845.0,2004,118053.0
27434,16076,"Greiz, Kreis",biolog. abbaubare Garten- und Parkabfälle,2168.0,2004,118053.0
27435,16077,"Altenburger Land, Kreis",Getrennt erfasste organische Abfälle,11950.0,2004,107893.0
27436,16077,"Altenburger Land, Kreis",Abfälle aus der Biotonne,5435.0,2004,107893.0
27437,16077,"Altenburger Land, Kreis",biolog. abbaubare Garten- und Parkabfälle,6515.0,2004,107893.0

In [131]:
merged_wa['kg_per_person'] = merged_wa['weight']/merged_wa['Bevölkerung']*1000
merged_wa['Name'] = merged_wa['Name'].str.strip()
merged_wa

,AGS,Name,Abfall,weight,Jahr,Bevölkerung,kg_per_person
0,0,Deutschland,Getrennt erfasste organische Abfälle,10634192.0,2020,83155031.0,127.883928
1,0,Deutschland,Abfälle aus der Biotonne,5300612.0,2020,83155031.0,63.743732
2,0,Deutschland,biolog. abbaubare Garten- und Parkabfälle,5333580.0,2020,83155031.0,64.140196
3,1,Schleswig-Holstein,Getrennt erfasste organische Abfälle,357418.0,2020,2910875.0,122.787134
4,1,Schleswig-Holstein,Abfälle aus der Biotonne,289453.0,2020,2910875.0,99.438485
...,...,...,...,...,...,...,...
27433,16076,"Greiz, Kreis",Abfälle aus der Biotonne,3845.0,2004,118053.0,32.570117
27434,16076,"Greiz, Kreis",biolog. abbaubare Garten- und Parkabfälle,2168.0,2004,118053.0,18.364633
27435,16077,"Altenburger Land, Kreis",Getrennt erfasste organische Abfälle,11950.0,2004,107893.0,110.757880
27436,16077,"Altenburger Land, Kreis",Abfälle aus der Biotonne,5435.0,2004,107893.0,50.373982
27437,16077,"Altenburger Land, Kreis",biolog. abbaubare Garten- und Parkabfälle,6515.0,2004,107893.0,60.383899

In [144]:
#convert year to string to facilitate collapsing column levels
merged_wa['Jahr']=merged_wa['Jahr'].astype(str)

#pivot dataframe to show waste and years as columns
nw_df = merged_wa.pivot(index=['AGS','Name'],columns=['Abfall','Jahr'],values=['kg_per_person'])

#rename columns
nw_df.rename(columns={'Getrennt erfasste organische Abfälle':'sum'},inplace=True)

#rename columns sub groups organic waste
nw_df.rename(columns={'biolog. abbaubare Garten- und Parkabfälle':'gartenPark', 'Abfälle aus der Biotonne':'biotonne'},inplace=True)

nw_df

                                    kg_per_person                        \
Abfall                                        sum   biotonne gartenPark
Jahr                                         2020       2020       2020
AGS      Name
0        Deutschland                   127.883928  63.743732  64.140196
1        Schleswig-Holstein            122.787134  99.438485  23.348649
2        Hamburg                        55.292964  41.324107  13.968857
3        Niedersachsen                 166.173440  71.586763  94.586677
4        Bremen                         83.545793  36.969403  46.576390
...                                           ...        ...        ...
11008008 Berlin-Neukölln                      NaN        NaN        NaN
11009009 Berlin-Treptow-Köpenick              NaN        NaN        NaN
11010010 Berlin-Marzahn-Hellersdorf           NaN        NaN        NaN
11011011 Berlin-Lichtenberg                   NaN        NaN        NaN
11012012 Berlin-Reinickendorf                 NaN        NaN        NaN

                                                                       \
Abfall                                      sum   biotonne gartenPark
Jahr                                       2019       2019       2019
AGS      Name
0        Deutschland                 122.265819  59.807595  62.458223
1        Schleswig-Holstein          120.388887  93.745964  26.643267
2        Hamburg                      49.587144  37.607193  11.979951
3        Niedersachsen               157.453430  66.720310  90.733121
4        Bremen                       82.392594  33.865138  48.527456
...                                         ...        ...        ...
11008008 Berlin-Neukölln                    NaN        NaN        NaN
11009009 Berlin-Treptow-Köpenick            NaN        NaN        NaN
11010010 Berlin-Marzahn-Hellersdorf         NaN        NaN        NaN
11011011 Berlin-Lichtenberg                 NaN        NaN        NaN
11012012 Berlin-Reinickendorf               NaN        NaN        NaN

                                                                       \
Abfall                                      sum   biotonne gartenPark
Jahr                                       2018       2018       2018
AGS      Name
0        Deutschland                 119.622141  57.961065  61.661064
1        Schleswig-Holstein          113.578430  89.930583  23.648191
2        Hamburg                      46.508243  34.363851  12.144392
3        Niedersachsen               159.340468  62.808928  96.531540
4        Bremen                       77.916678  32.794230  45.122448
...                                         ...        ...        ...
11008008 Berlin-Neukölln                    NaN        NaN        NaN
11009009 Berlin-Treptow-Köpenick            NaN        NaN        NaN
11010010 Berlin-Marzahn-Hellersdorf         NaN        NaN        NaN
11011011 Berlin-Lichtenberg                 NaN        NaN        NaN
11012012 Berlin-Reinickendorf               NaN        NaN        NaN

                                                 ...                         \
Abfall                                      sum  ... gartenPark         sum
Jahr                                       2017  ...       2007        2006
AGS      Name                                    ...
0        Deutschland                 124.625003  ...  55.523256  102.651517
1        Schleswig-Holstein          120.827899  ...  25.050989   98.687344
2        Hamburg                      53.097809  ...   6.212482   20.351366
3        Niedersachsen               166.382072  ...  89.713792  143.561346
4        Bremen                       86.101681  ...  53.470008   85.803918
...                                         ...  ...        ...         ...
11008008 Berlin-Neukölln                    NaN  ...        NaN         NaN
11009009 Berlin-Treptow-Köpenick            NaN  ...        NaN         NaN
11010010 Berlin-Marzahn-Hellersdorf         NaN  ...        NaN         NaN
11011011 Berlin-Lichtenberg                 NaN  ...        NaN         NaN
11012012 Berlin-Reinickendorf               NaN  ...        NaN         NaN

                                                                       \
Abfall                                biotonne gartenPark         sum
Jahr                                      2006       2006        2005
AGS      Name
0        Deutschland                 50.416592  52.234926  101.131438
1        Schleswig-Holstein          70.497210  28.190134   95.147461
2        Hamburg                     14.593697   5.757669   20.761321
3        Niedersachsen               60.695618  82.865853  140.303300
4        Bremen                      35.118581  50.685338   87.458758
...                                        ...        ...         ...
11008008 Berlin-Neukölln                   NaN        NaN         NaN
11009009 Berlin-Treptow-Köpenick           NaN        NaN         NaN
11010010 Berlin-Marzahn-Hellersdorf        NaN        NaN         NaN
11011011 Berlin-Lichtenberg                NaN        NaN         NaN
11012012 Berlin-Reinickendorf              NaN        NaN         NaN

                                                                       \
Abfall                                biotonne gartenPark         sum
Jahr                                      2005       2005        2004
AGS      Name
0        Deutschland                 49.525671  51.605792  101.955411
1        Schleswig-Holstein          70.406114  24.741347   99.165005
2        Hamburg                     15.026150   5.735172   21.500666
3        Niedersachsen               60.638638  79.664661  138.130430
4        Bremen                      35.753097  51.705661   85.957302
...                                        ...        ...         ...
11008008 Berlin-Neukölln                   NaN        NaN         NaN
11009009 Berlin-Treptow-Köpenick           NaN        NaN         NaN
11010010 Berlin-Marzahn-Hellersdorf        NaN        NaN         NaN
11011011 Berlin-Lichtenberg                NaN        NaN         NaN
11012012 Berlin-Reinickendorf              NaN        NaN         NaN


Abfall                                biotonne gartenPark
Jahr                                      2004       2004
AGS      Name
0        Deutschland                 49.952613  52.002810
1        Schleswig-Holstein          70.260821  28.904538
2        Hamburg                     15.678770   5.821896
3        Niedersachsen               62.235179  75.895251
4        Bremen                      36.274922  49.682380
...                                        ...        ...
11008008 Berlin-Neukölln                   NaN        NaN
11009009 Berlin-Treptow-Köpenick           NaN        NaN
11010010 Berlin-Marzahn-Hellersdorf        NaN        NaN
11011011 Berlin-Lichtenberg                NaN        NaN
11012012 Berlin-Reinickendorf              NaN        NaN

[538 rows x 51 columns]

In [145]:
#collapse levels of column names and join waste type to year
nw_df.columns = nw_df.columns.map('_'.join)

#sort columns so indicators are together
nw_df=nw_df[sorted(nw_df.columns)]

#prepend all columns with indicator name
nw_df=nw_df.add_prefix('waste_organicwaste_')

#convert AGS to numeric and set as new index
nw_df.reset_index(inplace=True)
nw_df['AGS'] = pd.to_numeric(nw_df['AGS'])
nw_df.set_index('AGS',inplace=True)
nw_df.sort_index(ascending=True,inplace=True)

#strip whitespace from region names
nw_df['Name']=nw_df['Name'].str.strip()

#unit of measure
nw_df["Unit"] = "Kg per person"

nw_df

,Name,waste_organicwaste_kg_per_person_biotonne_2004,waste_organicwaste_kg_per_person_biotonne_2005,waste_organicwaste_kg_per_person_biotonne_2006,waste_organicwaste_kg_per_person_biotonne_2007,waste_organicwaste_kg_per_person_biotonne_2008,waste_organicwaste_kg_per_person_biotonne_2009,waste_organicwaste_kg_per_person_biotonne_2010,waste_organicwaste_kg_per_person_biotonne_2011,waste_organicwaste_kg_per_person_biotonne_2012,...,waste_organicwaste_kg_per_person_sum_2012,waste_organicwaste_kg_per_person_sum_2013,waste_organicwaste_kg_per_person_sum_2014,waste_organicwaste_kg_per_person_sum_2015,waste_organicwaste_kg_per_person_sum_2016,waste_organicwaste_kg_per_person_sum_2017,waste_organicwaste_kg_per_person_sum_2018,waste_organicwaste_kg_per_person_sum_2019,waste_organicwaste_kg_per_person_sum_2020,Unit
AGS,,,,,,,,,,,,,,,,,,,,,
0,Deutschland,49.952613,49.525671,50.416592,51.268279,51.368402,52.870864,51.427457,54.149492,54.127251,...,112.954879,112.129398,121.080816,117.623457,123.403127,124.625003,119.622141,122.265819,127.883928,Kg per person
1,Schleswig-Holstein,70.260821,70.406114,70.497210,72.930136,72.460889,73.383834,71.562267,76.435999,76.874975,...,95.737050,95.407775,102.670775,111.032093,117.645630,120.827899,113.578430,120.388887,122.787134,Kg per person
2,Hamburg,15.678770,15.026150,14.593697,15.135864,14.615428,15.048833,15.729537,25.142781,30.964001,...,39.151875,40.999987,44.985480,48.673834,51.313550,53.097809,46.508243,49.587144,55.292964,Kg per person
3,Niedersachsen,62.235179,60.638638,60.695618,61.859828,61.137043,60.777304,59.809861,63.130052,62.467710,...,150.906640,146.629273,163.333925,159.127641,163.231490,166.382072,159.340468,157.453430,166.173440,Kg per person
4,Bremen,36.274922,35.753097,35.118581,36.107148,34.910390,34.962129,33.414257,34.925834,33.918573,...,88.228916,84.636084,88.450010,85.372955,85.839768,86.101681,77.916678,82.392594,83.545793,Kg per person
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11008008,Berlin-Neukölln,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kg per person
11009009,Berlin-Treptow-Köpenick,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kg per person
11010010,Berlin-Marzahn-Hellersdorf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kg per person
11011011,Berlin-Lichtenberg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kg per person
11012012,Berlin-Reinickendorf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kg per person

In [146]:
#save dataframe to file
nw_df.to_csv("data/final_data_landkreis_waste_organicwaste_normalized.csv")