In [10]:
### Download waste data on household waste 
### from regionalstatistik.de and compile into csv with Regions as rows
### and indicators and years as columns.

In [11]:
#41141-03-01-4
#https://www.regionalstatistik.de/genesis//online?operation=table&code=32121-01-02-4-B&bypass=true&levelindex=0&levelid=1658850132846#abreadcrumb
#include years 2007-2020 and set regions to Landkreise, download as csv

In [12]:
# import necessary libraries

import pandas as pd
import numpy as np

In [13]:
#load dataset from local file
source_df = pd.read_csv("data/32121-01-02-4_flat_haushaltsabfaelle.csv",delimiter=";", encoding='latin1', low_memory=False)

# #remove subgroups of waste (everything except for organic waste total) Haus- und Sperrmüll, Getrennt erfasste organische Abfälle, Getrennt erfasste Wertstoffe, Sonstige Abfälle, Biotonne, abbaubare Garten- und Parkabfälle and Insgesamt
# source_df = source_df[(source_df['2_Auspraegung_Code'] != 'ABFALLART100') & (source_df['2_Auspraegung_Code'] != 'ABFALLART300') & (source_df['2_Auspraegung_Code'] != 'ABFALLART400') & (source_df['2_Auspraegung_Code'] != 'ABFALLART201') & (source_df['2_Auspraegung_Code'] != 'ABFALLART202') & (source_df['2_Auspraegung_Label'] != "Insgesamt")]

#remove subgroups of waste Haus- und Sperrmüll, Getrennt erfasste organische Abfälle, Getrennt erfasste Wertstoffe, Sonstige Abfälle and Insgesamt
source_df = source_df[(source_df['2_Auspraegung_Code'] != 'ABFALLART100') & (source_df['2_Auspraegung_Code'] != 'ABFALLART300') & (source_df['2_Auspraegung_Code'] != 'ABFALLART400') & (source_df['2_Auspraegung_Label'] != "Insgesamt") ]

source_df

,Statistik_Code,Statistik_Label,Zeit_Code,Zeit_Label,Zeit,1_Merkmal_Code,1_Merkmal_Label,1_Auspraegung_Code,1_Auspraegung_Label,2_Merkmal_Code,2_Merkmal_Label,2_Auspraegung_Code,2_Auspraegung_Label,AEW009__Aufkommen_an_Haushaltsabfaellen_(o.E-altgeraete)__t
2,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2020,KREISE,Kreise und kreisfreie Städte,DG,Deutschland,ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,10634192
3,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2020,KREISE,Kreise und kreisfreie Städte,DG,Deutschland,ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART201,Abfälle aus der Biotonne,5300612
4,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2020,KREISE,Kreise und kreisfreie Städte,DG,Deutschland,ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART202,biolog. abbaubare Garten- und Parkabfälle,5333580
9,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2020,KREISE,Kreise und kreisfreie Städte,01,Schleswig-Holstein,ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,357418
10,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2020,KREISE,Kreise und kreisfreie Städte,01,Schleswig-Holstein,ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART201,Abfälle aus der Biotonne,289453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64011,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2004,KREISE,Kreise und kreisfreie Städte,16076,"Greiz, Kreis",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART201,Abfälle aus der Biotonne,3845
64012,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2004,KREISE,Kreise und kreisfreie Städte,16076,"Greiz, Kreis",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART202,biolog. abbaubare Garten- und Parkabfälle,2168
64017,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2004,KREISE,Kreise und kreisfreie Städte,16077,"Altenburger Land, Kreis",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART200,Getrennt erfasste organische Abfälle,11950
64018,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2004,KREISE,Kreise und kreisfreie Städte,16077,"Altenburger Land, Kreis",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART201,Abfälle aus der Biotonne,5435
64019,32121,Erhebung der öffentlich-rechtlichen Abfallents...,JAHR,Jahr,2004,KREISE,Kreise und kreisfreie Städte,16077,"Altenburger Land, Kreis",ABFA01,Abfallarten von Haushaltsabfällen,ABFALLART202,biolog. abbaubare Garten- und Parkabfälle,6515

In [14]:
waste_df = source_df.copy()

#extract year from date
waste_df['Jahr']=waste_df['Zeit'].astype(str)

#drop unnecessary columns
waste_df.drop(columns=['Zeit','Statistik_Code', 'Statistik_Label', 'Zeit_Code', 'Zeit_Label', 
       '1_Merkmal_Code', '1_Merkmal_Label', 
       '2_Merkmal_Code', '2_Merkmal_Label',
       '2_Auspraegung_Code'],inplace=True)

#rename columns
waste_df.rename(columns={'1_Auspraegung_Code':'AGS','1_Auspraegung_Label':'Name','2_Auspraegung_Label':'Abfall','AEW009__Aufkommen_an_Haushaltsabfaellen_(o.E-altgeraete)__t':'weight'},inplace=True)

#replace '-' with 0 and '.' with 'NaN according to Zeichnerklärung
waste_df['weight'].replace('-','0',inplace=True)
waste_df['weight'] = waste_df['weight'].apply(pd.to_numeric,errors='coerce')

waste_df['AGS']=waste_df['AGS'].replace("DG",0)

waste_df

,AGS,Name,Abfall,weight,Jahr
2,0,Deutschland,Getrennt erfasste organische Abfälle,10634192.0,2020
3,0,Deutschland,Abfälle aus der Biotonne,5300612.0,2020
4,0,Deutschland,biolog. abbaubare Garten- und Parkabfälle,5333580.0,2020
9,01,Schleswig-Holstein,Getrennt erfasste organische Abfälle,357418.0,2020
10,01,Schleswig-Holstein,Abfälle aus der Biotonne,289453.0,2020
...,...,...,...,...,...
64011,16076,"Greiz, Kreis",Abfälle aus der Biotonne,3845.0,2004
64012,16076,"Greiz, Kreis",biolog. abbaubare Garten- und Parkabfälle,2168.0,2004
64017,16077,"Altenburger Land, Kreis",Getrennt erfasste organische Abfälle,11950.0,2004
64018,16077,"Altenburger Land, Kreis",Abfälle aus der Biotonne,5435.0,2004
64019,16077,"Altenburger Land, Kreis",biolog. abbaubare Garten- und Parkabfälle,6515.0,2004

In [15]:
#pivot dataframe to show waste and years as columns
pt_df = waste_df.pivot(index=['AGS','Name'],columns=['Abfall','Jahr'],values=['weight'])

#rename columns
pt_df.rename(columns={'Getrennt erfasste organische Abfälle':'sum'},inplace=True)

#rename columns sub groups organic waste
pt_df.rename(columns={'biolog. abbaubare Garten- und Parkabfälle':'gartenPark', 'Abfälle aus der Biotonne':'biotonne'},inplace=True)

pt_df

                                                          weight             \
Abfall                                                       sum   biotonne
Jahr                                                        2020       2020
AGS   Name
0     Deutschland                                     10634192.0  5300612.0
01      Schleswig-Holstein                              357418.0   289453.0
01001       Flensburg, kreisfreie Stadt                   6050.0     4753.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt     16333.0    12825.0
01003       Lübeck, Hansestadt, kreisfreie Stadt         22232.0    15850.0
...                                                          ...        ...
16073       Saalfeld-Rudolstadt, Kreis                   18769.0        0.0
16074       Saale-Holzland-Kreis                           681.0        0.0
16075       Saale-Orla-Kreis                             14633.0        0.0
16076       Greiz, Kreis                                 12452.0     4209.0
16077       Altenburger Land, Kreis                      13470.0     5606.0

                                                                             \
Abfall                                               gartenPark         sum
Jahr                                                       2020        2019
AGS   Name
0     Deutschland                                     5333580.0  10168446.0
01      Schleswig-Holstein                              67965.0    349582.0
01001       Flensburg, kreisfreie Stadt                  1297.0      5922.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt     3508.0     16035.0
01003       Lübeck, Hansestadt, kreisfreie Stadt         6383.0     20058.0
...                                                         ...         ...
16073       Saalfeld-Rudolstadt, Kreis                  18769.0     15470.0
16074       Saale-Holzland-Kreis                          681.0       337.0
16075       Saale-Orla-Kreis                            14633.0     12039.0
16076       Greiz, Kreis                                 8244.0     13994.0
16077       Altenburger Land, Kreis                      7863.0     14205.0

                                                                            \
Abfall                                                 biotonne gartenPark
Jahr                                                       2019       2019
AGS   Name
0     Deutschland                                     4974001.0  5194445.0
01      Schleswig-Holstein                             272217.0    77366.0
01001       Flensburg, kreisfreie Stadt                  4610.0     1311.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt    12231.0     3804.0
01003       Lübeck, Hansestadt, kreisfreie Stadt        15236.0     4823.0
...                                                         ...        ...
16073       Saalfeld-Rudolstadt, Kreis                      0.0    15470.0
16074       Saale-Holzland-Kreis                            0.0      337.0
16075       Saale-Orla-Kreis                                0.0    12039.0
16076       Greiz, Kreis                                 4122.0     9871.0
16077       Altenburger Land, Kreis                      5434.0     8771.0

                                                                            \
Abfall                                                      sum   biotonne
Jahr                                                       2018       2018
AGS   Name
0     Deutschland                                     9930936.0  4811882.0
01      Schleswig-Holstein                             329004.0   260503.0
01001       Flensburg, kreisfreie Stadt                  5764.0     4640.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt    15174.0    11696.0
01003       Lübeck, Hansestadt, kreisfreie Stadt        18789.0    14395.0
...                                                         ...        ...
16073       Saalfeld-Rudolstadt, Kreis                  17860.0        0.0
16074       Saale-Holzland-Kreis                          291.0        0.0
16075       Saale-Orla-Kreis                            13580.0        0.0
16076       Greiz, Kreis                                15448.0     4039.0
16077       Altenburger Land, Kreis                     12971.0     5255.0

                                                                             \
Abfall                                               gartenPark         sum
Jahr                                                       2018        2017
AGS   Name
0     Deutschland                                     5119053.0  10317997.0
01      Schleswig-Holstein                              68502.0    349171.0
01001       Flensburg, kreisfreie Stadt                  1124.0      5974.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt     3479.0     16425.0
01003       Lübeck, Hansestadt, kreisfreie Stadt         4394.0     19080.0
...                                                         ...         ...
16073       Saalfeld-Rudolstadt, Kreis                  17860.0     17208.0
16074       Saale-Holzland-Kreis                          291.0       268.0
16075       Saale-Orla-Kreis                            13580.0     13062.0
16076       Greiz, Kreis                                11409.0     16863.0
16077       Altenburger Land, Kreis                      7716.0     14383.0

                                                      ...             \
Abfall                                                ... gartenPark
Jahr                                                  ...       2007
AGS   Name                                            ...
0     Deutschland                                     ...  4565002.0
01      Schleswig-Holstein                            ...    71079.0
01001       Flensburg, kreisfreie Stadt               ...      388.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt  ...     2273.0
01003       Lübeck, Hansestadt, kreisfreie Stadt      ...     4423.0
...                                                   ...        ...
16073       Saalfeld-Rudolstadt, Kreis                ...    10394.0
16074       Saale-Holzland-Kreis                      ...        0.0
16075       Saale-Orla-Kreis                          ...     7774.0
16076       Greiz, Kreis                              ...     3050.0
16077       Altenburger Land, Kreis                   ...     7843.0

                                                                            \
Abfall                                                      sum   biotonne
Jahr                                                       2006       2006
AGS   Name
0     Deutschland                                     8449750.0  4150037.0
01      Schleswig-Holstein                             279705.0   199807.0
01001       Flensburg, kreisfreie Stadt                  5658.0     4865.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt    11872.0    10605.0
01003       Lübeck, Hansestadt, kreisfreie Stadt        20442.0    16406.0
...                                                         ...        ...
16073       Saalfeld-Rudolstadt, Kreis                   9314.0        0.0
16074       Saale-Holzland-Kreis                            0.0        0.0
16075       Saale-Orla-Kreis                             6945.0        0.0
16076       Greiz, Kreis                                 7711.0     6104.0
16077       Altenburger Land, Kreis                     11473.0     5013.0

                                                                            \
Abfall                                               gartenPark        sum
Jahr                                                       2006       2005
AGS   Name
0     Deutschland                                     4299713.0  8337073.0
01      Schleswig-Holstein                              79898.0   269548.0
01001       Flensburg, kreisfreie Stadt                   793.0     5731.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt     1267.0    12229.0
01003       Lübeck, Hansestadt, kreisfreie Stadt         4036.0    20012.0
...                                                         ...        ...
16073       Saalfeld-Rudolstadt, Kreis                   9314.0     8880.0
16074       Saale-Holzland-Kreis                            0.0        0.0
16075       Saale-Orla-Kreis                             6945.0     6622.0
16076       Greiz, Kreis                                 1607.0     6372.0
16077       Altenburger Land, Kreis                      6460.0    12038.0

                                                                            \
Abfall                                                 biotonne gartenPark
Jahr                                                       2005       2005
AGS   Name
0     Deutschland                                     4082797.0  4254278.0
01      Schleswig-Holstein                             199457.0    70091.0
01001       Flensburg, kreisfreie Stadt                  5008.0      723.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt    10346.0     1884.0
01003       Lübeck, Hansestadt, kreisfreie Stadt        16435.0     3577.0
...                                                         ...        ...
16073       Saalfeld-Rudolstadt, Kreis                      0.0     8880.0
16074       Saale-Holzland-Kreis                            0.0        0.0
16075       Saale-Orla-Kreis                                0.0     6622.0
16076       Greiz, Kreis                                 3922.0     2450.0
16077       Altenburger Land, Kreis                      5219.0     6819.0

                                                                            \
Abfall                                                      sum   biotonne
Jahr                                                       2004       2004
AGS   Name
0     Deutschland                                     8411408.0  4121133.0
01      Schleswig-Holstein                             280514.0   198751.0
01001       Flensburg, kreisfreie Stadt                  5647.0     5138.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt     9793.0     8759.0
01003       Lübeck, Hansestadt, kreisfreie Stadt        21755.0    16477.0
...                                                         ...        ...
16073       Saalfeld-Rudolstadt, Kreis                   9586.0        0.0
16074       Saale-Holzland-Kreis                            0.0        0.0
16075       Saale-Orla-Kreis                             7151.0        0.0
16076       Greiz, Kreis                                 6013.0     3845.0
16077       Altenburger Land, Kreis                     11950.0     5435.0


Abfall                                               gartenPark
Jahr                                                       2004
AGS   Name
0     Deutschland                                     4290276.0
01      Schleswig-Holstein                              81764.0
01001       Flensburg, kreisfreie Stadt                   509.0
01002       Kiel, Landeshauptstadt, kreisfreie Stadt     1033.0
01003       Lübeck, Hansestadt, kreisfreie Stadt         5279.0
...                                                         ...
16073       Saalfeld-Rudolstadt, Kreis                   9586.0
16074       Saale-Holzland-Kreis                            0.0
16075       Saale-Orla-Kreis                             7151.0
16076       Greiz, Kreis                                 2168.0
16077       Altenburger Land, Kreis                      6515.0

[538 rows x 51 columns]

In [16]:
#collapse levels of column names and join waste type to year
pt_df.columns = pt_df.columns.map('_'.join)

#sort columns so indicators are together
pt_df=pt_df[sorted(pt_df.columns)]

#prepend all columns with indicator name
pt_df=pt_df.add_prefix('waste_organicwaste_')

#convert AGS to numeric and set as new index
pt_df.reset_index(inplace=True)
pt_df['AGS'] = pd.to_numeric(pt_df['AGS'])
pt_df.set_index('AGS',inplace=True)
pt_df.sort_index(ascending=True,inplace=True)

#strip whitespace from region names
pt_df['Name']=pt_df['Name'].str.strip()

#unit of measure
pt_df["Unit"] = "Kg per person"


pt_df
#sorted(pt_df.columns)

,Name,waste_organicwaste_weight_biotonne_2004,waste_organicwaste_weight_biotonne_2005,waste_organicwaste_weight_biotonne_2006,waste_organicwaste_weight_biotonne_2007,waste_organicwaste_weight_biotonne_2008,waste_organicwaste_weight_biotonne_2009,waste_organicwaste_weight_biotonne_2010,waste_organicwaste_weight_biotonne_2011,waste_organicwaste_weight_biotonne_2012,...,waste_organicwaste_weight_sum_2012,waste_organicwaste_weight_sum_2013,waste_organicwaste_weight_sum_2014,waste_organicwaste_weight_sum_2015,waste_organicwaste_weight_sum_2016,waste_organicwaste_weight_sum_2017,waste_organicwaste_weight_sum_2018,waste_organicwaste_weight_sum_2019,waste_organicwaste_weight_sum_2020,Unit
AGS,,,,,,,,,,,,,,,,,,,,,
0,Deutschland,4121133.0,4082797.0,4150037.0,4215167.0,4212330.0,4324956.0,4204277.0,4349715.0,4358529.0,...,9095550.0,9056407.0,9831464.0,9665788.0,10183430.0,10317997.0,9930936.0,10168446.0,10634192.0,Kg per person
1,Schleswig-Holstein,198751.0,199457.0,199807.0,206930.0,205373.0,207825.0,202826.0,214194.0,215752.0,...,268689.0,268664.0,290647.0,317409.0,339046.0,349171.0,329004.0,349582.0,357418.0,Kg per person
2,Hamburg,27200.0,26200.0,25600.0,26800.0,25900.0,26700.0,28100.0,43200.0,53700.0,...,67900.0,71600.0,79300.0,87000.0,92900.0,97200.0,85630.0,91600.0,102429.0,Kg per person
3,Niedersachsen,497938.0,484742.0,484514.0,493127.0,485871.0,481892.0,473592.0,490789.0,485936.0,...,1173902.0,1142324.0,1278372.0,1261341.0,1296986.0,1324863.0,1271927.0,1258621.0,1329956.0,Kg per person
4,Bremen,24058.0,23721.0,23318.0,23942.0,23106.0,23135.0,22077.0,22778.0,22209.0,...,57770.0,55639.0,58544.0,57327.0,58264.0,58638.0,53216.0,56126.0,56822.0,Kg per person
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11008008,Berlin-Neukölln,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Kg per person
11009009,Berlin-Treptow-Köpenick,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Kg per person
11010010,Berlin-Marzahn-Hellersdorf,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Kg per person
11011011,Berlin-Lichtenberg,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Kg per person
11012012,Berlin-Reinickendorf,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,Kg per person

In [17]:
pt_df[pt_df["waste_organicwaste_weight_biotonne_2010"].isna()]
#kreise ohne abfalldaten: Oberbergischer Kreis, Rheinisch-Bergischer Kreis, alle Landkreise im Saarland

,Name,waste_organicwaste_weight_biotonne_2004,waste_organicwaste_weight_biotonne_2005,waste_organicwaste_weight_biotonne_2006,waste_organicwaste_weight_biotonne_2007,waste_organicwaste_weight_biotonne_2008,waste_organicwaste_weight_biotonne_2009,waste_organicwaste_weight_biotonne_2010,waste_organicwaste_weight_biotonne_2011,waste_organicwaste_weight_biotonne_2012,...,waste_organicwaste_weight_sum_2012,waste_organicwaste_weight_sum_2013,waste_organicwaste_weight_sum_2014,waste_organicwaste_weight_sum_2015,waste_organicwaste_weight_sum_2016,waste_organicwaste_weight_sum_2017,waste_organicwaste_weight_sum_2018,waste_organicwaste_weight_sum_2019,waste_organicwaste_weight_sum_2020,Unit
AGS,,,,,,,,,,,,,,,,,,,,,
5374,Oberbergischer Kreis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kg per person
5378,Rheinisch-Bergischer Kreis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kg per person
10041,"Saarbrücken, Regionalverband",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kg per person
10042,"Merzig-Wadern, Landkreis",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kg per person
10043,"Neunkirchen, Landkreis",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kg per person
10044,"Saarlouis, Landkreis",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kg per person
10045,Saarpfalz-Kreis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kg per person
10046,"St. Wendel, Landkreis",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kg per person
3241001,"Hannover, Landeshauptstadt",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,Kg per person

In [18]:
#save dataframe to file
pt_df.to_csv("data/final_data_landkreis_waste_organicwaste.csv")

In [19]:
## DATASNIPPET FOR TESTING

schweinfurt = waste_df[waste_df.AGS == "09678"]
schweinfurt.drop(["Name","AGS"],axis= 1,inplace=True)

schweinfurt.to_csv("data/snippet/organicwaste_schweinfurtLK.csv")

/var/folders/6w/mz49x3ds0b18vg8p9jx7wg0r0000gn/T/ipykernel_6565/2019023097.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schweinfurt.drop(["Name","AGS"],axis= 1,inplace=True)

In [20]:
# convert column "a" of a DataFrame
waste_df["AGS"] = pd.to_numeric(waste_df["AGS"])
bundeslaender = waste_df[(waste_df["AGS"] <= 16) & (waste_df["AGS"] > 0)]
bundeslaender = bundeslaender[bundeslaender["Abfall"] == "Getrennt erfasste organische Abfälle"]
bundeslaender.drop(["AGS"],axis= 1,inplace=True)
bundeslaender = bundeslaender.reset_index(drop=True)
bundeslaender
bundeslaender.to_csv("data/snippet/organicwaste_bundeslaenderOhneDL.csv")

In [21]:
deutschland = waste_df[waste_df.Name == "Deutschland"]
deutschland.drop(["Name","AGS"],axis= 1,inplace=True)
deutschland
deutschland.to_csv("data/snippet/organicwaste_deutschland.csv")

/var/folders/6w/mz49x3ds0b18vg8p9jx7wg0r0000gn/T/ipykernel_6565/3566189559.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  deutschland.drop(["Name","AGS"],axis= 1,inplace=True)

## Normalize waste_df by population

In [22]:
#copy waste_df
norm_wa = waste_df.copy()

#set variable types for merge
norm_wa['AGS'] = norm_wa['AGS'].astype(int)
norm_wa['Jahr'] = norm_wa['Jahr'].astype(int)
norm_wa

,AGS,Name,Abfall,weight,Jahr
2,0,Deutschland,Getrennt erfasste organische Abfälle,10634192.0,2020
3,0,Deutschland,Abfälle aus der Biotonne,5300612.0,2020
4,0,Deutschland,biolog. abbaubare Garten- und Parkabfälle,5333580.0,2020
9,1,Schleswig-Holstein,Getrennt erfasste organische Abfälle,357418.0,2020
10,1,Schleswig-Holstein,Abfälle aus der Biotonne,289453.0,2020
...,...,...,...,...,...
64011,16076,"Greiz, Kreis",Abfälle aus der Biotonne,3845.0,2004
64012,16076,"Greiz, Kreis",biolog. abbaubare Garten- und Parkabfälle,2168.0,2004
64017,16077,"Altenburger Land, Kreis",Getrennt erfasste organische Abfälle,11950.0,2004
64018,16077,"Altenburger Land, Kreis",Abfälle aus der Biotonne,5435.0,2004
64019,16077,"Altenburger Land, Kreis",biolog. abbaubare Garten- und Parkabfälle,6515.0,2004

In [23]:
# load population data from general data
pop_df = pd.read_csv("../general_data/population.csv",delimiter=";", encoding='latin1', low_memory=False)

#correct Germany AGS
pop_df['AGS'] = pop_df['1_Auspraegung_Code'].astype('string').str.replace('DG','0')

#extract year from time column
pop_df['Jahr'] = pop_df['Zeit'].astype('string').str[-4:]

#select only necessary coluns and rename
pop_df = pop_df[['AGS','Jahr','BEVSTD__Bevoelkerungsstand__Anzahl']]
pop_df.columns=['AGS','Jahr','Bevölkerung']

#set variable types for merge
pop_df['AGS'] = pop_df['AGS'].astype(int)
pop_df['Jahr'] = pop_df['Jahr'].astype(int)


pop_df.set_index(['AGS','Jahr'], inplace=True)
pop_df['Bevölkerung'] = pop_df['Bevölkerung']
pop_df

           Bevölkerung
AGS   Jahr
0     1995    81817499
      1996    82012162
      1997    82057379
      1998    82037011
      1999    82163475
...                ...
16073 2021      100969
16074 2021       82513
16075 2021       79030
16076 2021       96102
16077 2021       87807

[13311 rows x 1 columns]

In [24]:
abfallzw_kreise = [7211,7231,7232,7233]
jahre = [2016,2017,2018,2019,2020]

for i in jahre:
    for j in abfallzw_kreise:
        pop_df.loc[(7235,i),'Bevölkerung'] = int(pop_df.loc[(7235,i),'Bevölkerung'])+int(pop_df.loc[(j,i),'Bevölkerung'])
pop_df.loc[(7235,2018)]

Bevölkerung    531007
Name: (7235, 2018), dtype: object

In [25]:
pop_df.loc[(7235,)]

/var/folders/6w/mz49x3ds0b18vg8p9jx7wg0r0000gn/T/ipykernel_6565/1442721325.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  pop_df.loc[(7235,)]

     Bevölkerung
Jahr
1995      134077
1996      134653
1997      135460
1998      136422
1999      137330
2000      137610
2001      138196
2002      138836
2003      139280
2004      139613
2005      139932
2006      140265
2007      141009
2008      141201
2009      141481
2010      141646
2011      142494
2012      143893
2013      144337
2014      145227
2015      147999
2016      528728
2017      529597
2018      531007
2019      533113
2020      534438
2021      151167

In [26]:
pop_df.reset_index(inplace=True)
pop_df[pop_df['AGS']==7235]

        AGS  Jahr Bevölkerung
622    7235  1995      134077
1098   7235  1996      134653
1574   7235  1997      135460
2050   7235  1998      136422
2526   7235  1999      137330
3002   7235  2000      137610
3478   7235  2001      138196
3954   7235  2002      138836
4430   7235  2003      139280
4906   7235  2004      139613
5382   7235  2005      139932
5858   7235  2006      140265
6334   7235  2007      141009
6810   7235  2008      141201
7286   7235  2009      141481
7762   7235  2010      141646
8238   7235  2011      142494
8714   7235  2012      143893
9190   7235  2013      144337
9666   7235  2014      145227
10142  7235  2015      147999
10618  7235  2016      528728
11094  7235  2017      529597
11570  7235  2018      531007
12046  7235  2019      533113
12522  7235  2020      534438
12998  7235  2021      151167

In [27]:
#merge waste_df with population
merged_wa = norm_wa.merge(pop_df, on = ['AGS','Jahr'], how='left')
merged_wa['Bevölkerung'] =merged_wa['Bevölkerung'].apply(pd.to_numeric, errors='coerce')
merged_wa

,AGS,Name,Abfall,weight,Jahr,Bevölkerung
0,0,Deutschland,Getrennt erfasste organische Abfälle,10634192.0,2020,83155031.0
1,0,Deutschland,Abfälle aus der Biotonne,5300612.0,2020,83155031.0
2,0,Deutschland,biolog. abbaubare Garten- und Parkabfälle,5333580.0,2020,83155031.0
3,1,Schleswig-Holstein,Getrennt erfasste organische Abfälle,357418.0,2020,2910875.0
4,1,Schleswig-Holstein,Abfälle aus der Biotonne,289453.0,2020,2910875.0
...,...,...,...,...,...,...
27433,16076,"Greiz, Kreis",Abfälle aus der Biotonne,3845.0,2004,118053.0
27434,16076,"Greiz, Kreis",biolog. abbaubare Garten- und Parkabfälle,2168.0,2004,118053.0
27435,16077,"Altenburger Land, Kreis",Getrennt erfasste organische Abfälle,11950.0,2004,107893.0
27436,16077,"Altenburger Land, Kreis",Abfälle aus der Biotonne,5435.0,2004,107893.0
27437,16077,"Altenburger Land, Kreis",biolog. abbaubare Garten- und Parkabfälle,6515.0,2004,107893.0

In [30]:
merged_wa['kg_per_person'] = merged_wa['weight']/merged_wa['Bevölkerung']*1000
merged_wa['Name'] = merged_wa['Name'].str.strip()
merged_wa

#merged_wa[]

,AGS,Name,Abfall,weight,Jahr,Bevölkerung,kg_per_person
0,0,Deutschland,Getrennt erfasste organische Abfälle,10634192.0,2020,83155031.0,127.883928
1,0,Deutschland,Abfälle aus der Biotonne,5300612.0,2020,83155031.0,63.743732
2,0,Deutschland,biolog. abbaubare Garten- und Parkabfälle,5333580.0,2020,83155031.0,64.140196
3,1,Schleswig-Holstein,Getrennt erfasste organische Abfälle,357418.0,2020,2910875.0,122.787134
4,1,Schleswig-Holstein,Abfälle aus der Biotonne,289453.0,2020,2910875.0,99.438485
...,...,...,...,...,...,...,...
27433,16076,"Greiz, Kreis",Abfälle aus der Biotonne,3845.0,2004,118053.0,32.570117
27434,16076,"Greiz, Kreis",biolog. abbaubare Garten- und Parkabfälle,2168.0,2004,118053.0,18.364633
27435,16077,"Altenburger Land, Kreis",Getrennt erfasste organische Abfälle,11950.0,2004,107893.0,110.757880
27436,16077,"Altenburger Land, Kreis",Abfälle aus der Biotonne,5435.0,2004,107893.0,50.373982
27437,16077,"Altenburger Land, Kreis",biolog. abbaubare Garten- und Parkabfälle,6515.0,2004,107893.0,60.383899

In [31]:
#convert year to string to facilitate collapsing column levels
merged_wa['Jahr']=merged_wa['Jahr'].astype(str)

#pivot dataframe to show waste and years as columns
nw_df = merged_wa.pivot(index=['AGS','Name'],columns=['Abfall','Jahr'],values=['kg_per_person'])

#rename columns
nw_df.rename(columns={'Getrennt erfasste organische Abfälle':'sum'},inplace=True)

#rename columns sub groups organic waste
nw_df.rename(columns={'biolog. abbaubare Garten- und Parkabfälle':'gartenPark', 'Abfälle aus der Biotonne':'biotonne'},inplace=True)

nw_df

                                    kg_per_person                        \
Abfall                                        sum   biotonne gartenPark
Jahr                                         2020       2020       2020
AGS      Name
0        Deutschland                   127.883928  63.743732  64.140196
1        Schleswig-Holstein            122.787134  99.438485  23.348649
2        Hamburg                        55.292964  41.324107  13.968857
3        Niedersachsen                 166.173440  71.586763  94.586677
4        Bremen                         83.545793  36.969403  46.576390
...                                           ...        ...        ...
11008008 Berlin-Neukölln                      NaN        NaN        NaN
11009009 Berlin-Treptow-Köpenick              NaN        NaN        NaN
11010010 Berlin-Marzahn-Hellersdorf           NaN        NaN        NaN
11011011 Berlin-Lichtenberg                   NaN        NaN        NaN
11012012 Berlin-Reinickendorf                 NaN        NaN        NaN

                                                                       \
Abfall                                      sum   biotonne gartenPark
Jahr                                       2019       2019       2019
AGS      Name
0        Deutschland                 122.265819  59.807595  62.458223
1        Schleswig-Holstein          120.388887  93.745964  26.643267
2        Hamburg                      49.587144  37.607193  11.979951
3        Niedersachsen               157.453430  66.720310  90.733121
4        Bremen                       82.392594  33.865138  48.527456
...                                         ...        ...        ...
11008008 Berlin-Neukölln                    NaN        NaN        NaN
11009009 Berlin-Treptow-Köpenick            NaN        NaN        NaN
11010010 Berlin-Marzahn-Hellersdorf         NaN        NaN        NaN
11011011 Berlin-Lichtenberg                 NaN        NaN        NaN
11012012 Berlin-Reinickendorf               NaN        NaN        NaN

                                                                       \
Abfall                                      sum   biotonne gartenPark
Jahr                                       2018       2018       2018
AGS      Name
0        Deutschland                 119.622141  57.961065  61.661064
1        Schleswig-Holstein          113.578430  89.930583  23.648191
2        Hamburg                      46.508243  34.363851  12.144392
3        Niedersachsen               159.340468  62.808928  96.531540
4        Bremen                       77.916678  32.794230  45.122448
...                                         ...        ...        ...
11008008 Berlin-Neukölln                    NaN        NaN        NaN
11009009 Berlin-Treptow-Köpenick            NaN        NaN        NaN
11010010 Berlin-Marzahn-Hellersdorf         NaN        NaN        NaN
11011011 Berlin-Lichtenberg                 NaN        NaN        NaN
11012012 Berlin-Reinickendorf               NaN        NaN        NaN

                                                 ...                         \
Abfall                                      sum  ... gartenPark         sum
Jahr                                       2017  ...       2007        2006
AGS      Name                                    ...
0        Deutschland                 124.625003  ...  55.523256  102.651517
1        Schleswig-Holstein          120.827899  ...  25.050989   98.687344
2        Hamburg                      53.097809  ...   6.212482   20.351366
3        Niedersachsen               166.382072  ...  89.713792  143.561346
4        Bremen                       86.101681  ...  53.470008   85.803918
...                                         ...  ...        ...         ...
11008008 Berlin-Neukölln                    NaN  ...        NaN         NaN
11009009 Berlin-Treptow-Köpenick            NaN  ...        NaN         NaN
11010010 Berlin-Marzahn-Hellersdorf         NaN  ...        NaN         NaN
11011011 Berlin-Lichtenberg                 NaN  ...        NaN         NaN
11012012 Berlin-Reinickendorf               NaN  ...        NaN         NaN

                                                                       \
Abfall                                biotonne gartenPark         sum
Jahr                                      2006       2006        2005
AGS      Name
0        Deutschland                 50.416592  52.234926  101.131438
1        Schleswig-Holstein          70.497210  28.190134   95.147461
2        Hamburg                     14.593697   5.757669   20.761321
3        Niedersachsen               60.695618  82.865853  140.303300
4        Bremen                      35.118581  50.685338   87.458758
...                                        ...        ...         ...
11008008 Berlin-Neukölln                   NaN        NaN         NaN
11009009 Berlin-Treptow-Köpenick           NaN        NaN         NaN
11010010 Berlin-Marzahn-Hellersdorf        NaN        NaN         NaN
11011011 Berlin-Lichtenberg                NaN        NaN         NaN
11012012 Berlin-Reinickendorf              NaN        NaN         NaN

                                                                       \
Abfall                                biotonne gartenPark         sum
Jahr                                      2005       2005        2004
AGS      Name
0        Deutschland                 49.525671  51.605792  101.955411
1        Schleswig-Holstein          70.406114  24.741347   99.165005
2        Hamburg                     15.026150   5.735172   21.500666
3        Niedersachsen               60.638638  79.664661  138.130430
4        Bremen                      35.753097  51.705661   85.957302
...                                        ...        ...         ...
11008008 Berlin-Neukölln                   NaN        NaN         NaN
11009009 Berlin-Treptow-Köpenick           NaN        NaN         NaN
11010010 Berlin-Marzahn-Hellersdorf        NaN        NaN         NaN
11011011 Berlin-Lichtenberg                NaN        NaN         NaN
11012012 Berlin-Reinickendorf              NaN        NaN         NaN


Abfall                                biotonne gartenPark
Jahr                                      2004       2004
AGS      Name
0        Deutschland                 49.952613  52.002810
1        Schleswig-Holstein          70.260821  28.904538
2        Hamburg                     15.678770   5.821896
3        Niedersachsen               62.235179  75.895251
4        Bremen                      36.274922  49.682380
...                                        ...        ...
11008008 Berlin-Neukölln                   NaN        NaN
11009009 Berlin-Treptow-Köpenick           NaN        NaN
11010010 Berlin-Marzahn-Hellersdorf        NaN        NaN
11011011 Berlin-Lichtenberg                NaN        NaN
11012012 Berlin-Reinickendorf              NaN        NaN

[538 rows x 51 columns]

In [32]:
#collapse levels of column names and join waste type to year
nw_df.columns = nw_df.columns.map('_'.join)

#sort columns so indicators are together
nw_df=nw_df[sorted(nw_df.columns)]

#prepend all columns with indicator name
nw_df=nw_df.add_prefix('waste_organicwaste_')

#convert AGS to numeric and set as new index
nw_df.reset_index(inplace=True)
nw_df['AGS'] = pd.to_numeric(nw_df['AGS'])
nw_df.set_index('AGS',inplace=True)
nw_df.sort_index(ascending=True,inplace=True)

#strip whitespace from region names
nw_df['Name']=nw_df['Name'].str.strip()

#unit of measure
nw_df["Unit"] = "Kg per person"

#nw_df[(nw_df.index>10000)&(nw_df.index<11000)]
nw_df.loc[7235,]

Name                                                Trier-Saarburg, Landkreis
waste_organicwaste_kg_per_person_biotonne_2004                            0.0
waste_organicwaste_kg_per_person_biotonne_2005                            0.0
waste_organicwaste_kg_per_person_biotonne_2006                            0.0
waste_organicwaste_kg_per_person_biotonne_2007                            0.0
waste_organicwaste_kg_per_person_biotonne_2008                            0.0
waste_organicwaste_kg_per_person_biotonne_2009                            0.0
waste_organicwaste_kg_per_person_biotonne_2010                            0.0
waste_organicwaste_kg_per_person_biotonne_2011                            0.0
waste_organicwaste_kg_per_person_biotonne_2012                            0.0
waste_organicwaste_kg_per_person_biotonne_2013                            0.0
waste_organicwaste_kg_per_person_biotonne_2014                            0.0
waste_organicwaste_kg_per_person_biotonne_2015                            0.0
waste_organicwaste_kg_per_person_biotonne_2016                       7.506695
waste_organicwaste_kg_per_person_biotonne_2017                       7.375419
waste_organicwaste_kg_per_person_biotonne_2018                      15.796402
waste_organicwaste_kg_per_person_biotonne_2019                      11.113966
waste_organicwaste_kg_per_person_biotonne_2020                      19.268839
waste_organicwaste_kg_per_person_gartenPark_2004                    76.303783
waste_organicwaste_kg_per_person_gartenPark_2005                    65.310294
waste_organicwaste_kg_per_person_gartenPark_2006                    86.500553
waste_organicwaste_kg_per_person_gartenPark_2007                   117.566964
waste_organicwaste_kg_per_person_gartenPark_2008                   141.514579
waste_organicwaste_kg_per_person_gartenPark_2009                   171.846396
waste_organicwaste_kg_per_person_gartenPark_2010                   190.919617
waste_organicwaste_kg_per_person_gartenPark_2011                   200.261064
waste_organicwaste_kg_per_person_gartenPark_2012                   171.210552
waste_organicwaste_kg_per_person_gartenPark_2013                   215.793594
waste_organicwaste_kg_per_person_gartenPark_2014                   246.248976
waste_organicwaste_kg_per_person_gartenPark_2015                   289.718174
waste_organicwaste_kg_per_person_gartenPark_2016                   167.335568
waste_organicwaste_kg_per_person_gartenPark_2017                    173.81896
waste_organicwaste_kg_per_person_gartenPark_2018                    182.06163
waste_organicwaste_kg_per_person_gartenPark_2019                   179.798654
waste_organicwaste_kg_per_person_gartenPark_2020                   218.947754
waste_organicwaste_kg_per_person_sum_2004                           76.303783
waste_organicwaste_kg_per_person_sum_2005                           65.310294
waste_organicwaste_kg_per_person_sum_2006                           86.500553
waste_organicwaste_kg_per_person_sum_2007                          117.566964
waste_organicwaste_kg_per_person_sum_2008                          141.514579
waste_organicwaste_kg_per_person_sum_2009                          171.846396
waste_organicwaste_kg_per_person_sum_2010                          190.919617
waste_organicwaste_kg_per_person_sum_2011                          200.261064
waste_organicwaste_kg_per_person_sum_2012                          171.210552
waste_organicwaste_kg_per_person_sum_2013                          215.793594
waste_organicwaste_kg_per_person_sum_2014                          246.248976
waste_organicwaste_kg_per_person_sum_2015                          289.718174
waste_organicwaste_kg_per_person_sum_2016                          174.844154
waste_organicwaste_kg_per_person_sum_2017                          181.196268
waste_organicwaste_kg_per_person_sum_2018                          197.858032
waste_organicwaste_kg_per_person_sum_2019                          190.910745
waste_organicwaste_kg_per_person_sum_2020                          238.214723
Unit                                                            Kg per person
Name: 7235, dtype: object

In [33]:
for i in range(10041,10047):
    nw_df.loc[i,'waste_organicwaste_kg_per_person_biotonne_2004':'waste_organicwaste_kg_per_person_sum_2020']=nw_df.loc[10,'waste_organicwaste_kg_per_person_biotonne_2004':'waste_organicwaste_kg_per_person_sum_2020']
nw_df.loc[10000:11000]

,Name,waste_organicwaste_kg_per_person_biotonne_2004,waste_organicwaste_kg_per_person_biotonne_2005,waste_organicwaste_kg_per_person_biotonne_2006,waste_organicwaste_kg_per_person_biotonne_2007,waste_organicwaste_kg_per_person_biotonne_2008,waste_organicwaste_kg_per_person_biotonne_2009,waste_organicwaste_kg_per_person_biotonne_2010,waste_organicwaste_kg_per_person_biotonne_2011,waste_organicwaste_kg_per_person_biotonne_2012,...,waste_organicwaste_kg_per_person_sum_2012,waste_organicwaste_kg_per_person_sum_2013,waste_organicwaste_kg_per_person_sum_2014,waste_organicwaste_kg_per_person_sum_2015,waste_organicwaste_kg_per_person_sum_2016,waste_organicwaste_kg_per_person_sum_2017,waste_organicwaste_kg_per_person_sum_2018,waste_organicwaste_kg_per_person_sum_2019,waste_organicwaste_kg_per_person_sum_2020,Unit
AGS,,,,,,,,,,,,,,,,,,,,,
10041,"Saarbrücken, Regionalverband",53.371917,51.096218,50.913229,51.403726,51.208164,52.495392,49.117159,55.861824,54.831251,...,138.497235,142.933711,145.180909,143.367246,135.637249,142.208659,127.307273,126.661918,126.056031,Kg per person
10042,"Merzig-Wadern, Landkreis",53.371917,51.096218,50.913229,51.403726,51.208164,52.495392,49.117159,55.861824,54.831251,...,138.497235,142.933711,145.180909,143.367246,135.637249,142.208659,127.307273,126.661918,126.056031,Kg per person
10043,"Neunkirchen, Landkreis",53.371917,51.096218,50.913229,51.403726,51.208164,52.495392,49.117159,55.861824,54.831251,...,138.497235,142.933711,145.180909,143.367246,135.637249,142.208659,127.307273,126.661918,126.056031,Kg per person
10044,"Saarlouis, Landkreis",53.371917,51.096218,50.913229,51.403726,51.208164,52.495392,49.117159,55.861824,54.831251,...,138.497235,142.933711,145.180909,143.367246,135.637249,142.208659,127.307273,126.661918,126.056031,Kg per person
10045,Saarpfalz-Kreis,53.371917,51.096218,50.913229,51.403726,51.208164,52.495392,49.117159,55.861824,54.831251,...,138.497235,142.933711,145.180909,143.367246,135.637249,142.208659,127.307273,126.661918,126.056031,Kg per person
10046,"St. Wendel, Landkreis",53.371917,51.096218,50.913229,51.403726,51.208164,52.495392,49.117159,55.861824,54.831251,...,138.497235,142.933711,145.180909,143.367246,135.637249,142.208659,127.307273,126.661918,126.056031,Kg per person

In [37]:
for k in [5374,5378]:
    nw_df.loc[k,'waste_organicwaste_kg_per_person_biotonne_2004':'waste_organicwaste_kg_per_person_sum_2020']=nw_df.loc[5,'waste_organicwaste_kg_per_person_biotonne_2004':'waste_organicwaste_kg_per_person_sum_2020']

nw_df.loc[5374:5378]

,Name,waste_organicwaste_kg_per_person_biotonne_2004,waste_organicwaste_kg_per_person_biotonne_2005,waste_organicwaste_kg_per_person_biotonne_2006,waste_organicwaste_kg_per_person_biotonne_2007,waste_organicwaste_kg_per_person_biotonne_2008,waste_organicwaste_kg_per_person_biotonne_2009,waste_organicwaste_kg_per_person_biotonne_2010,waste_organicwaste_kg_per_person_biotonne_2011,waste_organicwaste_kg_per_person_biotonne_2012,...,waste_organicwaste_kg_per_person_sum_2012,waste_organicwaste_kg_per_person_sum_2013,waste_organicwaste_kg_per_person_sum_2014,waste_organicwaste_kg_per_person_sum_2015,waste_organicwaste_kg_per_person_sum_2016,waste_organicwaste_kg_per_person_sum_2017,waste_organicwaste_kg_per_person_sum_2018,waste_organicwaste_kg_per_person_sum_2019,waste_organicwaste_kg_per_person_sum_2020,Unit
AGS,,,,,,,,,,,,,,,,,,,,,
5374,Oberbergischer Kreis,62.273365,62.858589,63.854694,64.792385,66.041475,68.676007,66.613042,69.365705,68.040823,...,108.632577,107.454557,120.280599,112.745806,116.229591,115.095108,111.933088,112.369597,116.276247,Kg per person
5378,Rheinisch-Bergischer Kreis,62.273365,62.858589,63.854694,64.792385,66.041475,68.676007,66.613042,69.365705,68.040823,...,108.632577,107.454557,120.280599,112.745806,116.229591,115.095108,111.933088,112.369597,116.276247,Kg per person

In [36]:
for j in abfallzw_kreise:
    nw_df.loc[j,'waste_organicwaste_kg_per_person_biotonne_2016':'waste_organicwaste_kg_per_person_biotonne_2020']=nw_df.loc[7235,'waste_organicwaste_kg_per_person_biotonne_2016':'waste_organicwaste_kg_per_person_biotonne_2020']
    nw_df.loc[j,'waste_organicwaste_kg_per_person_gartenPark_2016':'waste_organicwaste_kg_per_person_gartenPark_2020']=nw_df.loc[7235,'waste_organicwaste_kg_per_person_gartenPark_2016':'waste_organicwaste_kg_per_person_gartenPark_2020']    
    nw_df.loc[j,'waste_organicwaste_kg_per_person_sum_2016':'waste_organicwaste_kg_per_person_sum_2020']=nw_df.loc[7235,'waste_organicwaste_kg_per_person_sum_2016':'waste_organicwaste_kg_per_person_sum_2020']    
nw_df.loc[7211:7236]

,Name,waste_organicwaste_kg_per_person_biotonne_2004,waste_organicwaste_kg_per_person_biotonne_2005,waste_organicwaste_kg_per_person_biotonne_2006,waste_organicwaste_kg_per_person_biotonne_2007,waste_organicwaste_kg_per_person_biotonne_2008,waste_organicwaste_kg_per_person_biotonne_2009,waste_organicwaste_kg_per_person_biotonne_2010,waste_organicwaste_kg_per_person_biotonne_2011,waste_organicwaste_kg_per_person_biotonne_2012,...,waste_organicwaste_kg_per_person_sum_2012,waste_organicwaste_kg_per_person_sum_2013,waste_organicwaste_kg_per_person_sum_2014,waste_organicwaste_kg_per_person_sum_2015,waste_organicwaste_kg_per_person_sum_2016,waste_organicwaste_kg_per_person_sum_2017,waste_organicwaste_kg_per_person_sum_2018,waste_organicwaste_kg_per_person_sum_2019,waste_organicwaste_kg_per_person_sum_2020,Unit
AGS,,,,,,,,,,,,,,,,,,,,,
7211,"Trier, kreisfreie Stadt",0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,174.844154,181.196268,197.858032,190.910745,238.214723,Kg per person
7231,"Bernkastel-Wittlich, Landkreis",0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0000,0.000000,0.000000,...,151.128274,170.367759,243.519161,263.404514,174.844154,181.196268,197.858032,190.910745,238.214723,Kg per person
7232,Eifelkreis Bitburg-Prüm,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0000,0.000000,0.000000,...,107.570925,107.011377,80.314912,106.184400,174.844154,181.196268,197.858032,190.910745,238.214723,Kg per person
7233,"Vulkaneifel, Landkreis",74.686395,73.987368,74.903817,74.841195,74.050256,74.49546,71.9637,70.661271,66.068475,...,140.422118,146.992512,208.062526,183.439155,174.844154,181.196268,197.858032,190.910745,238.214723,Kg per person
7235,"Trier-Saarburg, Landkreis",0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0000,0.000000,0.000000,...,171.210552,215.793594,246.248976,289.718174,174.844154,181.196268,197.858032,190.910745,238.214723,Kg per person

In [38]:
#save dataframe to file
nw_df.to_csv("data/final_data_landkreis_waste_organicwaste_normalized.csv")